Add additional Pylontech CAN protocol fields
helgeerbe/OpenDTU-OnBattery pull request #1213
Opened 2024-08-31 13:57 UTC by ranma

I noticed that these are missing while looking at dissassembly of the Pytes implementation of the protocol. I also found Pylontech sample CAN messages] which match the Pytes implementation [1]:

```
CAN ID – followed by 2 to 8 bytes of data:
0x351 – 14 02 74 0E 74 0E CC 01 – Battery voltage + current limits
                          ^^^^^ discharge cutoff voltage 46.0V
0x355 – 1A 00 64 00 – State of Health (SOH) / State of Charge (SOC)
0x356 – 4e 13 02 03 04 05 – Voltage / Current / Temp
0x359 – 00 00 00 00 0A 50 4E – Protection & Alarm flags
                       ^^^^^ always 0x50 0x4e in Pytes implementation
                    ^^ module count (matches the blog article image)
0x35C – C0 00 – Battery charge request flags
        ^^ two possible additional flags (bit 3 and bit 4)
0x35E – 50 59 4C 4F 4E 20 20 20 – Manufacturer name (“PYLON “)
        ^^^^^^^^^^^^^^ Note: Pytes sends a 5-byte message "PYTES" instead
                       padding with spaces
```

The extra charge request flag is "bit4: SOC low" (Seems to be SoC < 10% threshold for Pytes), I haven't bothered adding that as it provides little value.

[1] https://www.setfirelabs.com/green-energy/pylontech-can-reading-can-replication

2024-08-31 13:59 UTC, ranma commented
![image showing 10 Pylontech modules](https://github.com/user-attachments/assets/50af7b2f-fbb3-4667-8388-4bc6f0d90dad)

2024-08-31 14:02 UTC, ranma commented
```
int can_msg_pylontech_FUN_0802a2c8
              (int param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4)

{
  struct can_battery_state_1 *batteryState;
  int stateOfHealth;
  uint batTemp;
  int tmp;
  int stateOfCharge;
  uint batVolt;
  uint batCurrent;
  byte *pbVar1;
  uint alarms0;
  int iVar2;
  uint alarms1;
  int numModules;
  byte bVar3;
  
  iVar2 = 0;
  batteryState = can_get_ptr_to_battery_state_struct_at_20000194_FUN_080087ec();
  pbVar1 = *(byte **)(param_1 + 0x20);
  alarms0 = batteryState->field12_0x30_alarms0;
  alarms1 = batteryState->field13_0x34_alarms1;
  numModules = batteryState->field2_num_modules;
  switch(param_2) {
  case 0:
                    /* msg 0x359 */
    bVar3 = 0;
    if ((alarms1 & 1 | alarms0 & 1) != 0) {
      bVar3 = 2;
    }
    if (((int)(alarms1 << 0x1b) < 0) || ((int)(alarms0 << 0x1b) < 0)) {
      bVar3 = bVar3 | 4;
    }
    if (((int)(alarms1 << 0x17) < 0) || ((int)(alarms0 << 0x17) < 0)) {
      bVar3 = bVar3 | 8;
    }
    if (((int)(alarms1 << 0x13) < 0) || ((int)(alarms0 << 0x13) < 0)) {
      bVar3 = bVar3 | 0x10;
    }
    if ((alarms0 & 0x60000) != 0) {
      bVar3 = bVar3 | 0x80;
    }
    *pbVar1 = bVar3;
    bVar3 = (alarms0 & 0x180000) != 0;
    if ((int)(alarms0 << 3) < 0) {
      bVar3 = bVar3 | 8;
    }
    pbVar1[1] = bVar3;
    bVar3 = 0;
    if (((int)(alarms1 << 0x1e) < 0) || ((int)(alarms0 << 0x1e) < 0)) {
      bVar3 = 2;
    }
    if (((int)(alarms1 << 0x1c) < 0) || ((int)(alarms0 << 0x1c) < 0)) {
      bVar3 = bVar3 | 4;
    }
    if (((int)(alarms1 << 0x16) < 0) || ((int)(alarms0 << 0x16) < 0)) {
      bVar3 = bVar3 | 8;
    }
    if (((int)(alarms1 << 0x14) < 0) || ((int)(alarms0 << 0x14) < 0)) {
      bVar3 = bVar3 | 0x10;
    }
    if ((int)(alarms0 << 10) < 0) {
      bVar3 = bVar3 | 0x80;
    }
    pbVar1[2] = bVar3;
    if ((int)(alarms0 << 9) < 0) {
      bVar3 = bVar3 | 1;
    }
    if ((int)(batteryState->field14_alarms2 << 0x16) < 0) {
      bVar3 = bVar3 | 8;
    }
    pbVar1[3] = bVar3;
    pbVar1[4] = (byte)numModules;
    pbVar1[5] = 0x50;
    pbVar1[6] = 0x59;
    iVar2 = 7;
    break;
  case 1:
                    /* msg 0x351 */
    alarms0 = (uint)batteryState->field55_charge_end_mV / 100;
    *pbVar1 = (byte)alarms0;
    pbVar1[1] = (byte)(alarms0 >> 8);
    alarms0 = (uint)batteryState->field53_charge_mA / 100;
    pbVar1[2] = (byte)alarms0;
    pbVar1[3] = (byte)(alarms0 >> 8);
    alarms0 = (uint)batteryState->field54_discharge_mA / 100;
    pbVar1[4] = (byte)alarms0;
    pbVar1[5] = (byte)(alarms0 >> 8);
    alarms0 = (uint)batteryState->field56_discharge_end_mV / 100;
    pbVar1[6] = (byte)alarms0;
    pbVar1[7] = (byte)(alarms0 >> 8);
    iVar2 = 8;
    break;
  case 2:
                    /* msg 0x355 */
    stateOfCharge = batteryState->field10_state_of_charge;
    *pbVar1 = (byte)stateOfCharge;
    pbVar1[1] = (byte)((uint)stateOfCharge >> 8);
    stateOfHealth = batteryState->field11_state_of_health;
    pbVar1[2] = (byte)stateOfHealth;
    pbVar1[3] = (byte)((uint)stateOfHealth >> 8);
    iVar2 = 4;
    break;
  case 3:
                    /* msg 0x356 */
    batVolt = (uint)batteryState->field29_battery_voltage_precision5 / 10;
    *pbVar1 = (byte)batVolt;
    pbVar1[1] = (byte)(batVolt >> 8);
    batCurrent = (uint)batteryState->field30_battery_current_precision6 / 100;
    pbVar1[2] = (byte)batCurrent;
    pbVar1[3] = (byte)(batCurrent >> 8);
    batTemp = (uint)batteryState->field41_battery_temperature_precision3 / 100;
    pbVar1[4] = (byte)batTemp;
    pbVar1[5] = (byte)(batTemp >> 8);
    iVar2 = 6;
    break;
  case 4:
                    /* msg 0x35c */
    bVar3 = 0;
    if (batteryState->field44_flag_charge_enabled != 0) {
      bVar3 = 0x80;
    }
    if (batteryState->field45_flag_discharge_enabled != 0) {
      bVar3 = bVar3 | 0x40;
    }
    if (batteryState->field49_flag_charge_immediately != 0) {
      bVar3 = bVar3 | 0x20;
    }
    if (batteryState->field50_flag_soc_below_10percent != 0) {
      bVar3 = bVar3 | 0x10;
    }
    if (batteryState->field51_flag_0xcc_maybe_soc_above_x_threshold != 0) {
      bVar3 = bVar3 | 8;
    }
    *pbVar1 = bVar3;
    pbVar1[1] = 0;
    iVar2 = 2;
    break;
  case 5:
                    /* msg 0x35e */
    for (tmp = 0; tmp < 5; tmp = tmp + 1) {
      *pbVar1 = s__PYTES_0802a4db[tmp + 1];
      pbVar1 = pbVar1 + 1;
    }
    iVar2 = 5;
  }
  return iVar2;
}
```

2024-09-01 15:29 UTC, ranma commented
Liveview test using replayed CAN packets:
![Pylontech Liveview](https://github.com/user-attachments/assets/f1e0a6fe-a941-4213-ac18-3c5bbd075da6)

2024-09-01 15:32 UTC, ranma commented
CAN message simulator (connect Pi GPIO 10 (MOSI) to ESP32 CAN rx input):
```
#!/usr/bin/env python3

import struct
import time
import pigpio


pi = pigpio.pi()
spi = pi.spi_open(0, 500000, 0)


def addbits(l: bytearray, v: int, n: int):
  for i in range(n):
    mask = 1 << (n - i - 1)
    if (v & mask):
      l.append(1)
    else:
      l.append(0)


def can_crc15(bits: bytearray) -> int:
  crc = 0
  for bit in bits:
    crcout = crc >> 14
    crc = (crc << 1) & 0x7fff
    if bit ^ crcout:
      crc ^= 0x4599
  return crc


def can_stuff(bits: bytearray) -> bytearray:
  stuffed = bytearray()
  ones = 0
  zeroes = 0
  for bit in bits:
    stuffed.append(bit)
    if bit:
      ones += 1
      zeroes = 0
    else:
      zeroes += 1
      ones = 0
    if ones >= 5:
      stuffed.append(0)
      ones = 0
      zeroes = 1
    elif zeroes >= 5:
      stuffed.append(1)
      zeroes = 0
      ones = 1
  return stuffed


def can_msg(msg: int, payload: bytes) -> bytearray:
  if msg >= 0x800:
    raise ValueError('msg id out of range 0x000:0x7ff')
  if len(payload) > 8:
    raise ValueError('payload len out of range 0:7')

  leader = (msg << 7) | len(payload)
  acked_trailer = 0x2ff

  bits = bytearray()
  addbits(bits, leader, 19)
  for b in payload:
    addbits(bits, b, 8)

  crc = can_crc15(bits)
  addbits(bits, crc, 15)
  stuffed = can_stuff(bits)

  addbits(stuffed, acked_trailer, 10)
  return stuffed


def make_bytes(bits: bytearray) -> bytearray:
  x = 0
  i = 0
  data = bytearray()

  def add_bit(bit):
    nonlocal x, i
    x = (x << 1) & 0xff
    x |= bool(bit)
    i += 1
    if i >= 8:
      i = 0
      data.append(x)

  for bit in bits:
    add_bit(bit)

  # pad with ones
  while i > 0:
    add_bit(1)

  return data


def send_msg(msg: int, payload: bytes):
  bits = can_msg(msg, payload)
  data = make_bytes(bits)
  # RPI MOSI line idles at zero in between transactions, add extra padding.
  pad1 = 16 * b'\xff'
  pad2 = 8 * b'\xff'
  pi.spi_write(spi, pad1 + data + pad2)



def send_pylontech_msgs():
  # 0x351 14 02 74 0E 74 0E CC 01    Battery voltage + current limits
  # 0x355 1A 00 64 00                State of Health (SOH) / State of Charge (SOC)
  # 0x356 4e 13 02 03 04 05          Voltage / Current / Temp
  # 0x359 00 00 00 00 0A 50 4E       Protection & Alarm flags
  # 0x35C C0 00                      Battery charge request flags
  # 0x35E 50 59 4C 4F 4E 20 20 20    Manufacturer name
  send_msg(0x351, b'\x14\x02\x74\x0e\x74\x0e\xcc\x01') 
  send_msg(0x355, b'\x1a\x00\x64\x00') 
  send_msg(0x356, b'\x4e\x13\x02\x03\x04\x05') 
  send_msg(0x359, b'\x00\x00\x00\x00\x0a\x50\x4e') 
  send_msg(0x35c, b'\xc0\x00') 
  send_msg(0x35e, b'PYLON   ') 


while True:
  send_pylontech_msgs()
  time.sleep(0.1)
```

2024-09-04 14:46 UTC, schlimmchen requested changes
The new data points are interpreted and added to the live view, but please also publish them to the MQTT broker and add them to HASS auto-discovery.

2024-09-04 14:46 UTC, schlimmchen commented on src/BatteryStats.cpp
> +    addLiveViewValue(root, "dischargeVoltageLimitation", _dischargeVoltageLimitation, "V", 1);
Please also add to `PylontechBatteryStats::mqttPublish()` as well as `MqttHandleBatteryHass.cpp` for HASS auto-discovery.

2024-09-04 14:46 UTC, schlimmchen commented on src/BatteryStats.cpp
> +    addLiveViewValue(root, "modules", _moduleCount, "", 0);
Please also add to `PylontechBatteryStats::mqttPublish()` as well as `MqttHandleBatteryHass.cpp` for HASS auto-discovery.

2024-09-04 20:53 UTC, ranma commented on src/BatteryStats.cpp
> +    addLiveViewValue(root, "modules", _moduleCount, "", 0);
Done.

2024-09-09 12:26 UTC, AndreasBoehm commented
@DerHavey1994 @Snusme83
Habt ihr Zeit und Lust zu probieren ob diese Änderung die zwei neuen Felder `Entladespannungs Limit` und `Modul Anzahl` für eure Pylontech Batterie korrekt anzeigt?

Die entsprechenden builds findet ihr hier: https://github.com/helgeerbe/OpenDTU-OnBattery/actions/runs/10709343648?pr=1213

Danke vorab.

2024-09-09 12:48 UTC, DerHavey1994 commented
@AndreasBoehm läuft!
![Screenshot 2024-09-09 144635](https://github.com/user-attachments/assets/5acc4df9-8fed-427f-b25d-b795060c43a6)

2024-09-09 12:55 UTC, AndreasBoehm commented
Danke @DerHavey1994 fürs testen!

Great job @ranma! 
Checking the actual of code that run on the batteries was an awesome idea.

2024-09-09 16:25 UTC, Snusme83 commented
> @DerHavey1994 @Snusme83 Habt ihr Zeit und Lust zu probieren ob diese Änderung die zwei neuen Felder `Entladespannungs Limit` und `Modul Anzahl` für eure Pylontech Batterie korrekt anzeigt?
> 
> Die entsprechenden builds findet ihr hier: https://github.com/helgeerbe/OpenDTU-OnBattery/actions/runs/10709343648?pr=1213
> 
> Danke vorab.

Servus, soll ich noch testen? Kann ich das hier: 
![IMG_2346](https://github.com/user-attachments/assets/6171545c-5a19-4864-ae31-472089269397) machen oder muss da wieder neu geflasht werden?

2024-09-09 16:29 UTC, AndreasBoehm commented
@Snusme83 Genau da wo du gerade bist kannst du das verlinkte build als update hochladen.

2024-09-09 16:41 UTC, Snusme83 commented
Schaut gut aus. Hab zwei US3000C!

![IMG_2347](https://github.com/user-attachments/assets/ccbfdcc6-bb00-46d5-a5e5-ee9f2be0cba1)

2024-09-09 20:01 UTC, schlimmchen commented
> Blöde Frage: Könnte ich auf diese Art und Weise auch wieder auf das Release 2024.08.18 zurückgehen?🤔

@Snusme83 Ja.

2024-09-09 20:02 UTC, schlimmchen approved these changes

2024-09-25 12:45 UTC, merged