Add "Victron Smart Battery Sense" to list of battery provider
helgeerbe/OpenDTU-OnBattery pull request #1214
Opened 2024-09-01 08:24 UTC by SW-Niko

Smart Battery Sense

Endlich kann ich den fehlenden Teil der „Smart Battery Sense“ Integration nachliefen.
Snoopy-HSS hat eine gute Vorlage geliefert.
Thanks @Snoopy-HSS for the blueprint.
Die „Smart Battery Sense“ liefert nur Batterie-Spannung und Batterie-Temperatur. Die Anzeige konnte ich auf diese beiden Werte begrenzen. Das Meldungs Feld konnte ich nicht ausblenden. Vermutlich müsste ich dazu die UI (Java-Script) anfassen und das übersteigt meine Kenntnisse. Von meiner Seite kann man das aber auch so lassen.

Die ID für den Provider habe ich gleich auf 6 gesetzt damit ich mit Snoopy-HSS PR #1199 nicht in Konflikt komme. Er verwendet bereits 5.

Weil du diesen PR vermutlich wegen fehlender Hardware nicht testen kannst, habe ich ein paar Screenshots gemacht.

Aktivieren als Datenanbieter
![grafik](https://github.com/user-attachments/assets/50c47a28-0781-40ab-822b-51780e6c370e)

Anzeige der Spannung
![grafik](https://github.com/user-attachments/assets/70435b0a-d27b-4706-87be-b5717656bb75)

Anzeige der Daten
![grafik](https://github.com/user-attachments/assets/07bedb79-8768-414d-bbb8-d7b575569941)

Anzeige im Fehlerfall
![grafik](https://github.com/user-attachments/assets/c21d60df-aa24-443b-a4d3-aff204ec1bf5)

Getestet habe ich folgende Fälle:
- Aktivieren und Deaktivieren (Wenn Smart Batterie Sense vorhanden ist)
- Aktivieren und Deaktivieren (Wenn Smart Batterie Sense nicht vorhanden ist)
- Ausfall im laufenden Betrieb (Smart Batterie Sense abstecken)
- Das fehlen von SoC und Batteriestrom führt in anderen Programmteilen zu keinem Problem (Nur im Code überprüft)

Ansonsten fällt mir jetzt auch nichts mehr ein was noch fehlen würde.

2024-09-02 15:26 UTC, schlimmchen requested changes

2024-09-02 19:18 UTC, SW-Niko commented on webapp/src/locales/en.json
> +        "ProviderSmartSense": "Victron SmartBatterySense using MPPT interface",
Yep, sounds better

2024-09-02 19:23 UTC, SW-Niko commented on webapp/src/views/BatteryAdminView.vue
> +                { key: 6, value: 'SmartSense' },
Done

2024-09-02 19:28 UTC, SW-Niko commented on src/VictronSmartBatterySense.cpp
> +    int32_t temp {0};
Ok..

2024-09-02 19:30 UTC, SW-Niko commented on src/VictronSmartBatterySense.cpp
> +}
Done

2024-09-02 19:37 UTC, SW-Niko commented on src/VictronSmartBatterySense.cpp
> +    }
Hmmm... Done

2024-09-02 19:39 UTC, SW-Niko commented on src/BatteryStats.cpp
> +
Done

2024-09-03 16:56 UTC, SW-Niko commented on src/BatteryStats.cpp
> +    _manufacturer = "Smart Battery Sense";
Makes sense. Done

2024-09-03 16:59 UTC, SW-Niko commented on src/BatteryStats.cpp
> +}
Ok, done. By the way .. I do not have HA or Mqtt server .. So I can not test this function.

2024-09-03 17:52 UTC, SW-Niko commented
Ich habe die Änderungen gemacht und die Tests (die ich machen kann) wiederholt. Ich konnte nichts Negatives feststellen.
Aber mir ist noch der Punkt "Verbose Logging" aufgefallen. 
Das Aktivieren von "Verbose Logging" im Batterie Dialog macht keinen Sinn. Es wird ja die VE.Direct Schnittstelle vom MPPT verwendet. 
Eine Lösung wäre das automatische Verstecken und Deaktivieren von "Verbose Logging". Muss man dazu Java-Script anfassen?

2024-09-03 19:39 UTC, schlimmchen commented
Danke für die Anpassungen. Genau hingeschaut habe ich noch nicht. Mich quält dieses Feature ein wenig: Ich verstehe, dass es nett ist, aber es ist andererseits auch redundant. Wenn ein Smart Battery Sense da ist, werden dessen Werte ja ins MQTT übertragen und die Spannung wird dann auch berücksichtigt im DPL (über VictronMppt). Auch im live view ist es redundant, denn die Werte tauchen auch in der Karte für den MPPT auf.

Das habe ich alles ignoriert und wohlwollend auf die Sache geschaut, weil es nett ist wenn man diesen Provider ausdrücklich als Batterieschnittstelle auswählen kann.

Mir fällt aber jetzt noch etwas auf: Wenn man diese Schnittstelle nutzt, dann sollte man im DPL keine SoC Schwellwerte einstellen können. Denn die Battery Smart Sense liefert die ja nicht. Man kann das in die Metadaten für den DPL AdminView aufnehmen und entsprechend handeln. Es ist aber eine Sonderlocke, die mir eigentlich nicht gefällt. Die Annahme war mal, dass jeder Battery Provider wenigstens SoC bereitstellt.

Ich bin da echt zwiegespalten. @spcqike @AndreasBoehm @swingstate Was ist eure Meinung hierzu? Verbose Logging im BatteryAdminView der UI ausblenden, wenn man BatterySmartSense wählt, und im DPL die SoC Schwellwerte ausblenden? Ist das dann ein rundes Feature oder ist es redundant? Ein kleiner Vorteil wäre, dass man dann in den DPL Logs erkennen kann, ob die Spannung vom BatterySmartSense oder vom Ladereglerausgang gemessen wurde. Was gibt's noch?

2024-09-03 19:54 UTC, spcqike commented
> Die Annahme war mal, dass jeder Battery Provider wenigstens SoC bereitstellt.

Muss das jeder Provider? Unter dem Aspekt, dass man den SoC auch bewusst ignorieren kann, weil er oft driftet und die Spannung letzten Endes verlässlicher ist, sollte es doch egal sein, oder? 

Ich find die Idee und den Provider gut. (Auch wenn ich, sofern ich mal eine Batterie habe, wohl eine größere Luftpost mit integriertem BMS ala pylontech und co holen werde) 
Immerhin stellt er die Spannung der Batterie ohne belastete Leitungen zur Verfügung. Der MPPT und auch der inverter haben ja ggf. immer leicht niedrigere Spannungen, weil die Leitung irgendwie belastet sein kann. (Ok beim MPPT nachts wohl nicht, da ist das Problem ja nur beim Laden) 

damit wäre die Priorität der spannungsquellen ja BMS/Shunt(mit sense Leitung), battery sense, MPPT, inverter. Oder?

2024-09-03 20:25 UTC, SW-Niko commented
>Mir fällt aber jetzt noch etwas auf: Wenn man diese Schnittstelle nutzt, dann sollte man im DPL keine SoC Schwellwerte einstellen können

Ja, das ist jetzt schon etwas doof. Wenn ich es richtig im Kopf habe dann passiert nichts. Bei fehlenden SoC Daten wird automatisch nach der Spannung geregelt. 
Aber ich bin auch kein Fan von verwirrenden oder überfordernden Konfigurationen.

>Verbose Logging im BatteryAdminView der UI ausblenden, wenn man BatterySmartSense wählt, und im DPL die SoC Schwellwerte ausblenden? 

Zum ändern der UI reichen meine Kenntnisse (noch) nicht und ich will hier auch niemanden unnötig aufhalten. Es ist wie @schlimmchen sagt, eine nette aber nicht zwingend notwendige Erweiterung.

2024-09-04 07:11 UTC, spcqike commented
> Was ist eure Meinung hierzu? Verbose Logging im BatteryAdminView der UI ausblenden, wenn man BatterySmartSense wählt, und im DPL die SoC Schwellwerte ausblenden? Ist das dann ein rundes Feature oder ist es redundant? Ein kleiner Vorteil wäre, dass man dann in den DPL Logs erkennen kann, ob die Spannung vom BatterySmartSense oder vom Ladereglerausgang gemessen wurde. Was gibt's noch?

ich finde den battery sense an der Stelle nicht redundant. wie gesagt, er misst die Batteriespannung, direkt. ohne eventuell belastete Leitungen. Je näher an der Batterie die Spannung gemessen werden kann, um so besser. der Laderegler kann das auch, aber nur, wenn er selbst grade nicht lädt. und auch nur, wenn er direkt an der Batterie angeschlossen ist. hat man eine Busbar dazwischen, auf der sich Batterie, Laderegler und Wechselrichter "treffen", kann auch der Laderegler die Batteriespannung nicht genau ermitteln, solange der Wechselrichter Strom zieht. 


> damit wäre die Priorität der spannungsquellen ja BMS/Shunt(mit sense Leitung), battery sense, MPPT, inverter. Oder?

Nach einer Nacht drüber schlafen würd ich die Reihenfolge der Verlässlichkeit dann doch anders beschreiben, und den BatterySense auf die gleiche Stufe wie das BMS setzen, den SmartShunt eine Stufe darunter. Beim SmartShunt können Spannungsabfälle in der DC(-) Verbindung zur Batterie nicht ausgeschlossen werden, da die DC(-) Leitung zur Batterie, so kurz sie auch sein mag, immer belastet ist (sofern Strom fließt).
Nur das BMS und der BatterySense können die Spannung aufgrund der Nähe (BMS) und der unbelasteten Senseleitung (BatterySense) ohne nennenswerten Spannungsabfall ermitteln.
1. BMS/BatterySense
2. SmartShunt
3. Laderegler/Inverter (wobei der Laderegler ohne aktiver PV, also nachts, zu bevorzugen wäre)

wie gesagt, rein auf die Spannung bezogen. ein BMS ist den anderen Quellen in vielen weiteren Belangen natürlich weit überlegen 😄 

> Wenn man diese Schnittstelle nutzt, dann sollte man im DPL keine SoC Schwellwerte einstellen können. 

Ja, das stimmt. Die sollte man ausblenden.

Wenn ich meine Gedanken zum Umgang mit den Batteriezielwerten / -thresholds nochmal auskramen darf:
https://github.com/helgeerbe/OpenDTU-OnBattery/pull/1198#issuecomment-2308764874

> As I said somewhere else, on thinking run I think it would be good to move all battery stats to the battery menu (also desired voltages, SoCs and things) and let the DPL just query the battery class and check, if the battery is available and how much power it allows to be drawn.

Ich fänd es immer noch smart, wenn die Parameter aus dem DPL verschwinden und ins Batteriemenü kommen. So würde man, je nach gewählten Batterieprovider, die erlaubten Parameter auswählen und einstellen können. Der DPL würde letzten Endes die Batterie fragen, ob sie denn zur Zeit überhaupt verfügbar ist und wie viel Leistung sie liefern kann. 
Das einzige, was mir da noch Kopfschmerzen bereitet, ist der Fall ohne auswertbarem Provider, also wenn die Spannung tatsächlich vom Eingang des Wechselrichters abgegriffen werden muss.

2024-09-04 07:22 UTC, AndreasBoehm commented
Mir ist der Nutzen des neuen Battery Providers nicht ganz klar.

Soweit ich das verstanden habe wird die Batteriespannung des ersten MPPT genutzt der Battery Sense Temperatur liefert.

Das ist exakt das gleiche was der DPL aktuell bereits macht wenn ein MPPT verfügbar ist. Oder täusche ich mich?

Ich sehe deshalb BMS und BatterySense auch nicht auf der gleichen Stufe wenn ich ehrlich bin.

2024-09-04 07:32 UTC, spcqike commented
> Moment. BatterySense stellt den MPPTs die Batteriespannung zur Verfügung und deshalb nutzen wir dann die Spannung die der MPPT reported weil das die BatterySense Spannung ist?

so habe ich es in den Unterlagen auch gelesen. 

Die Spannung ist verlässlicher weil sie mit einer unbelasteten Sense Leitung direkt am Pol der Batterie gemessen wird. 

Die Spannung, die der laderegler messen kann, wird im laderegler gemessen. Ohne Belastung (also ohne aktiver Ladung und mit direkt Anschluss des ladereglers an der Batterie, ohne gemeinsame Busbar) sollten die Werte vergleichbar sein. 

So wie die Kabel belastet sind bekommst du halt Abweichungen durch die Spannungsabfälle auf den Leitungen und Klemmstellen. 

Mit gemeinsamer Busbar hast du auch immer Spannungsabfälle von der busbar zur Batterie, wenn der wechselrichter Strom zieht. 

Deswegen sehe ich die Messwerte des battery sense als genauer an, als die, des ladereglers. Auch sind sie immer „gleich genau“ und schwanken nicht mit der Belastung der Stromkabel. (Wie gesagt, der laderegler sollte nachts das gleiche messen, wenn er direkt auf die Batterie geklemmt ist)

2024-09-04 14:08 UTC, SW-Niko commented
>Moment. BatterySense stellt den MPPTs die Batteriespannung zur Verfügung und deshalb nutzen wir dann die Spannung die der MPPT reported weil das die BatterySense Spannung ist?

Genau so ist es.

>Deswegen sehe ich die Messwerte des battery sense als genauer an, als die, des ladereglers. Auch sind sie immer „gleich genau“ und schwanken nicht mit der Belastung der Stromkabel. (Wie gesagt, der laderegler sollte nachts das gleiche messen, wenn er direkt auf die Batterie geklemmt ist)

Elektrotechnik 1+ 🥇

2024-09-04 14:24 UTC, schlimmchen commented
@spcqike Der Gedanke, dass die Messung vom Smart Battery Sense genauer ist als die von einem Smart Shunt, jedenfalls die Spannungsmessung, den darfst du bitte behalten und uns in einem anderen Kontext nochmal daran erinnern. Der Gedanke ist sicherlich sinnvoll. Aber lass uns das bitte nicht mit diesem PR vermischen. So zutreffend der Gedanke auch sein mag, er ist nicht trivial umzusetzen. Mach gerne ein Issue auf.

Dann argumentierst du für diesen PR, aber sagst gleichzeitig, dass man einen Battery Smart Sense als auch einen Smart Shunt einsetzen können soll (so verstehe ich dich). Dem widerspricht aber dieser PR. Wenn man den Smart Sense als Battery Provider einbindet, dann hat man keinen SmartShunt als Battery Provider.

> Moment. BatterySense stellt den MPPTs die Batteriespannung zur Verfügung und deshalb nutzen wir dann die Spannung die der MPPT reported weil das die BatterySense Spannung ist?

Ich dachte das sei ein eingener Datenpunkt, der dann per HEX-Protokoll abgefragt wird. Dem ist aber nicht so. Also vertrauen wir darauf, dass der Spannungswert der als Spannung am Batterieausgang des Ladereglers gemeldet wird, der Wert vom Smart Sense ist? Auf die Schnelle konnte ich das nicht aus den Manuals bestätigen... Hat das mal jemand getestet, ob das wirklich so funktioniert?

Also, auch wenn ich damit deinen PR weiter schlechtrede, @SW-Niko, tendiere ich dazu, lieber bessere Dokumentation zum Smart Sense zu schreiben, als ihn ausdrücklich als Battery Provider einzubinden. Das hat nämlich insb. den Nachteil, dass man SmartShunt und BatterySense nicht kombinieren kann. Und mir passt diese Abhängigkeit zum Laderegler ehrlich gesagt nur ganz schlecht in den Kram.

Allerdings sehe ich gerade, dass die Temperatur, die vom Smart Battery Sense gemeldet wird, nicht im LiveView steht. Das könnte man natürlich nachziehen. Sie wird allerdings per MQTT veröffentlicht und ist auch für HASS auto-discovery vorgesehen.

2024-09-04 14:53 UTC, SW-Niko commented
>Ich dachte das sei ein eigener Datenpunkt, der dann per HEX-Protokoll abgefragt wird. Dem ist aber nicht so. Also vertrauen wir darauf, dass der Spannungswert der als Spannung am Batterieausgang des Ladereglers gemeldet wird, der Wert vom Smart Sense ist? 

Nein leider bekommen wir diesen Wert nicht extra per HEX-Protokoll. Darum frage ich auch zusätzlich immer erst die Batterietemperatur ab um sicher zu gehen das ein Smart Batterie Sense angeschlossen ist.
Interessanterweise könnten wir aber dem MPPT die Spannung vom BMS zur Verfügung stellen. ... Aber das ist ein anderes Thema.

>Auf die Schnelle konnte ich das nicht aus den Manuals bestätigen... Hat das mal jemand getestet, ob das wirklich so funktioniert?

Ja habe ich. Einmal kurz die Smart Batterie Sense vom VE.Smart Netzwerk nehmen und schon verändert sich die MPPT Batterie Spannung.

Ok....
Ich sehe ich inzwischen genauso wie @schlimmchen . Der Aufwand deckt nicht den Nutzen.
Ich mache jetzt den PR zu und gut ist. Es gibt wirklich wichtigeres.
Vielen Dank für die hilfreichen Kommentare

2024-09-04 14:53 UTC, closed without merging

2024-09-04 15:06 UTC, schlimmchen commented
> Vielen Dank für die hilfreichen Kommentare

Danke für die gute Diskussion und dass du beitragen möchtest! Wie wäre es mit Umsetzung der Anzeige der Smart Battery Sense Temperatur im Abschnitt "Output (Battery)" des Live View des Ladereglers? Das wäre eine super Sache! Das würde dann auch leicht klar machen, ob die Daten des Battery Sense tatsächlich (noch) ankommen am Laderegler.

2024-09-04 18:24 UTC, AndreasBoehm commented
> Interessanterweise könnten wir aber dem MPPT die Spannung vom BMS zur Verfügung stellen. ... 

Daran wäre ich stark interessiert, gibt doch einige Werte die wir dem MPPT vom BMS übergeben könnten.

2024-09-04 18:31 UTC, spcqike commented
> Dann argumentierst du für diesen PR, aber sagst gleichzeitig, dass man einen Battery Smart Sense als auch einen Smart Shunt einsetzen können soll (so verstehe ich dich).


so habe ich es nicht gesagt. bzw. nicht gemeint. Ein Shunt kann natürlich mehr messen, vor allem den Strom und daraus den SoC berechnen. Allerdings ist er bei der Spannung nicht so genau, wie der BatterySense, da der BS eben mit 2 unbelasteten Sense-Leitungen die Spannung misst. der Shunt hingegen hat eine Sense-Leitung für Plus, Minus ist hingegen "intern" und kann frühestens an der Schraubverbindung im Lastkreis abgegriffen werden.

> Ich dachte das sei ein eingener Datenpunkt, der dann per HEX-Protokoll abgefragt wird. 

Das dachte ich auch. 
Wenn der BS seine Spannung nur als "Slave" an den Laderegler sendet, und dieser die Spannung dann übernimmt und weiterreicht, als wäre es seine eigenst gemessene ..... erübrigt sich eine separate Integration ja, oder? 

> Mach gerne ein Issue auf.

siehe oben. Wenn der Laderegler seine oder die genauere BS Spannung ausgibt, braucht es kein Issue, oder?

2024-09-04 18:39 UTC, schlimmchen commented
> Wenn der Laderegler seine oder die genauere BS Spannung ausgibt, braucht es kein Issue, oder?

Für mich braucht es das nicht, aber dein Gedanke war ja richtig: Wenn jemand einen SmartShunt hat und den als BatteryProvider einbindet, aber auch einen BatterySense hat, dann bevorzugen wir zur Zeit die Spannung des SmartShunt, obwohl der des BatterySense besser wäre. Es ist einerseits ein konstruiertes Setup, weil man eher nicht beides im Einsatz hat, aber weil es beides Victron ist, kann ich mir schon vorstellen, dass man eben doch beides hat?

2024-09-04 18:45 UTC, schlimmchen commented
>> Interessanterweise könnten wir aber dem MPPT die Spannung vom BMS zur Verfügung stellen. ...

> Daran wäre ich stark interessiert, gibt doch einige Werte die wir dem MPPT vom BMS übergeben könnten.

@SW-Niko Wie ist das gemeint? Wie können wir denn dem Laderegler etwas vom BMS erzählen?

2024-09-04 19:17 UTC, swingstate commented
Jetzt ist die Diskussion ja schon recht weit, ich gebe trotzdem gerne ein paar Punkte dazu. I
ch hatte einen BS zusammen mit einem Shunt an 2x 25,6V die in Serie geschaltet waren im Einsatz und fand es vor allem hilfreich, dass der BS dem MPPT die Spannung der Batteriebank, wie @spcqike schon geschrieben hat, unbelastet melden kann. Da ich einige Automationen in HA nutze, welche die Spannung als Parameter verwenden fand ich es gut, dass dieser Wert so nah an den Polen wie nur möglich gemessen wurde. Ich habe den BS aber vor allem deswegen verwendet, weil er die Temperatur direkt dort mist wo er ist - ich hatte ihn auf die Batterienbank geklebt und den Temperaturwert, der auch vom MPPT genutzt wird, auch zusätzlich in HA genutzt. 

Mittlerweile bin ich ja auch auf dem Pylon-Zug, denke aber dass ein BS eine gute Ergänzung sein kann, vor allem dann wenn man mit mit einfachen Batterien (Powerqueen in meinem Fall damals) arbeitet oder einem die Temperatur der Batterien wichtig ist. Ein eigener Batteryprovider wie es Shunt oder BMS sind ist ein BS nach meinem Dafürhalten eher nicht bzw. nur sehr rudimentär. Es würde zudem zusätzliche Änderungen an der GUI notwendig werden, um den Nutzer nicht zu verwirren, aber das habt ihr ja schon durch diskutiert wenn ich es recht verstehe. 

Also, kurzum - Der BS ist aus meiner Sicht eine Ergänzung, aber kein eigener Provider.

2024-09-04 19:31 UTC, SW-Niko commented
>Wie ist das gemeint? Wie können wir denn dem Laderegler etwas vom BMS erzählen?

Ich bin darauf gestoßen als ich mit den HEX-Nachrichten gespielt habe.
Aber ich habe es nicht ausprobiert. 
Ok...
Ähnlich wie der Smart Battery Shunt kann man über VE.Direct dem MTTP die Batteriespannung mitteilen. Und wenn bestimmte Rahmenbedingungen eingehalten werden dann verwendet der MPPT diese Spannung für seine interne Regelung.
Das kann ich gerne mal Ausprobieren.

Im Victron HEX protokol Dokument findet man auf Seite 24

![grafik](https://github.com/user-attachments/assets/480315c4-fd35-4cd5-b3cb-3d4e56624b26)

Was da nicht steht ist das Verhalten wenn mehrere MPPTs im Verbund arbeiten. Entweder muss man dann die Daten an alle senden oder an den aktuellen Master.

>Wie wäre es mit Umsetzung der Anzeige der Smart Battery Sense Temperatur im Abschnitt "Output (Battery)" des Live View des Ladereglers? 

Ja, ich denke das kann ich machen. Ich habe ja wieder etwas dazu gelernt.

>Es ist einerseits ein konstruiertes Setup, weil man eher nicht beides im Einsatz hat, aber weil es beides Victron ist, kann ich mir schon vorstellen, dass man eben doch beides hat?

Ich denke beides gleichzeitig hat man eher weniger im Einsatz. 
Ich bin davon ausgegangen das der SmartShunt ebenfalls seine Daten über das VE.Smart Netzwerk an die MPPT weitergeben kann. Hat einer von euch einen SmartShunt? Dann kann er ja mal in der Victron App nachsehen welche Daten geteilt werden.
Bei meinem Smart Battery Sense steht das die Spannung und die Temperatur verteilt werden.

2024-09-05 06:49 UTC, SW-Niko commented
Im SmartShunt Handbuch auf Seite 20

![grafik](https://github.com/user-attachments/assets/815ae8ba-83d3-4154-bb2b-292c536f6f89)

Jetzt ist nur noch die Frage offen ... wenn beide Sensoren vorhanden sind. Nimmt der MPPT die Daten vom SmartShunt oder vom Smart Battery Sense? Vielleicht benützen auch die MPPT's und der SmartShunt die Daten vom Smart Battery Sense?

In den Handbüchern konnte ich nichts darüber finden. Hat jemand beides und kann einen Test machen?

2024-09-05 06:54 UTC, spcqike commented
> Vielleicht benützen auch die MPPT's und der SmartShunt die Daten vom Smart Battery Sense?

das würde Sinn machen. 

vielleicht hat ja jemand beides und kann es mal testen? 😄

2024-09-05 06:56 UTC, swingstate commented
Einen Smartshunt habe ich noch da und ich meine den BatterySense auch. Ich schau mir das kommende Woche einmal an.

2024-09-05 10:18 UTC, schlimmchen commented
> Im Victron HEX protokol Dokument findet man auf Seite 24

Okay, das ist leider geil und ein echt richtig gutes, sehr gutes Feature, das man woanders nicht kriegt, wenn wir die vom BMS gemeldete Spannung an den Laderegler übermitteln (können).

Das ist sehr spannend!

Da würde ich mich drum kümmern, falls sonst keiner gerne möchte. Bitte Bescheid geben, falls das jemand vor mir beginnt.

Wird aber bisschen lästig den Wert überhaupt dahin zu kriegen innerhalb der Software, weil der Victron Teil eine Lib ist...

2024-09-05 11:23 UTC, SW-Niko commented
Nichts dagegen... 
Ich bin ab Sonntag im Urlaub und kann deshalb so schnell nichts neues anfangen. 😁 

Bei "dummen" Batterien sehe ich durchaus Vorteile wenn der MPPT die genaue Batteriespannung bekommt aber bei 
Batterien mit BMS sind die Vorteile eher geringer ... zu mindestens aus elektrotechnischer Sicht.

- Im Bulk-Mode (MPPT ist Strom-Quelle) ist die genaue Spannung irrelevant
- Im Absorption und Float-Mode (MPPT ist Spannungs-Quelle) ja .. schon eher, hier hat man Vorteile.

Ich denke, man landet bei Batterien mit BMS bei 2 Vorteilen:

1. Der Übergang vom Bulk in den Float erfolgt später -> Batterie wird schneller geladen
2. Im Absorption Mode erreicht man die Ziel Spannung schneller und genauer ->  Das ist vorteilhaft wenn das BMS den Absorption-Mode benötigt um den Zellausgleich zu machen.

Hmmmm.... Ja doch, hat auch for Batterien mit BMS Vorteile.

2024-09-05 12:11 UTC, swingstate commented
Könnte man aus Deinen Punkten auf eine Empfehlung schliessen, die da lauten würde selbst bei Pylontech Batterien auf einen BS zu setzen?

2024-09-05 13:44 UTC, SW-Niko commented
>Könnte man aus Deinen Punkten auf eine Empfehlung schliessen, die da lauten würde selbst bei Pylontech Batterien auf einen BS zu setzen?

Nein, nein ..... Ganz und gar nicht.

Der MPPT hat die Aufgabe die Batterien schnell und richtig zu laden.
Für Batterien ohne BMS ist das immens wichtig. Ich habe schon mal ein Ladegerät für Blei-Gel-Akkus entwickelt darum kenne ich mich da etwas aus. (Temperatur Nachführung, Leitungsverluste kompensieren, Ausgasen vermeiden, usw)
Mit dem Aufkommen von Lithium-Batterien mit BMS ist ein Großteil der Regelung für die Zellen vom Lader in das BMS gewandert.
Darum ist für den Lader die Kenntnis der genauen Batteriespannung nicht mehr so essentiell wichtig.
Von wem die Spannung für den Lader/MPPT geliefert wird (BMS oder SmartBatterySense oder ?) ist egal.