Add support for W5500 ethernet module
helgeerbe/OpenDTU-OnBattery pull request #1231
Opened 2024-09-05 20:03 UTC by Gumbagubanga

Based on the pull-request https://github.com/tbnobody/OpenDTU/pull/2068 from the upstream project, I adopted the changes to work with the newly introduced `SPIPortManager`.

Credits to @marvincarstensen and @LennartF22 for the implementation of the ETHSPI/W5500 support.

2024-09-06 14:49 UTC, Tpaydt commented
Nice, good job
 
ESP32S3+W5500+NRF ist working now.

One more question.
Which connection is prioritized when I start the DTU?
I have now deleted the wifi settings.

2024-09-06 19:00 UTC, Gumbagubanga commented
> Nice, good job
> 
> ESP32S3+W5500+NRF ist working now.
> 
> One more question. Which connection is prioritized when I start the DTU? I have now deleted the wifi settings.

As before Ethernet >> Wifi.

2024-09-11 16:12 UTC, AndreasBoehm commented
I jiat ordered a PoE Hat for my fusion board. Looking forward to try this PR.

2024-09-11 19:48 UTC, schlimmchen commented
Oh nice, that means this will be taken care of, as I would need to make the time somehow, even though I have the hardware already... Thanks @AndreasBoehm.

2024-09-12 15:04 UTC, AndreasBoehm requested changes
Works as expected! Nice!

2024-09-12 15:04 UTC, AndreasBoehm commented on lib/ETHSPI/src/ETHSPI.h
> +#pragma once
Can you provider and link the source of this driver?

2024-09-12 19:18 UTC, Gumbagubanga commented on lib/ETHSPI/src/ETHSPI.h
> +#pragma once
I did some digging and found the nearest source to be our daughter-project AhoyDTU.
https://github.com/lumapu/ahoy/blob/main/src/network/AhoyEthernetSpi.h

How to correctly acknowledge their work in this contribution?

2024-09-12 19:22 UTC, schlimmchen commented on src/NetworkSettings.cpp
>          return ETH.macAddress();
I agree that there shall be braces around the if statement, but I disagree that the else statement is useful. Leaving it out entirely makes it very clear that there is a return statement which is always reached.

2024-09-12 19:23 UTC, Gumbagubanga commented on src/NetworkSettings.cpp
> +        if (PinMapping.isValidCmt2300Config() && PinMapping.isValidNrf24Config()) {
I updated the code to handle warnings in the SPI port allocation like in the `InverterSettings`.

2024-09-12 19:24 UTC, Gumbagubanga commented on src/NetworkSettings.cpp
> +        ETH.begin(pin.eth_phy_addr, pin.eth_power, pin.eth_mdc, pin.eth_mdio, pin.eth_type, pin.eth_clk_mode);
I updated the code as on the first glance there is no need to change up the order.
But I haven't tested this change yet.

2024-09-12 19:26 UTC, schlimmchen commented on src/PinMapping.cpp
> +#endif
Can we define these pins in the opendtufusionv2 environment to the respective pins for the PoE hat and use `_pinMapping.eth_enabled` to enable/disable ethernet support? This would require users relying on pin_mapping.json to not only define the logic pins but to set this enable switch as well...

2024-09-12 19:27 UTC, Gumbagubanga commented on src/NetworkSettings.cpp
>          return ETH.macAddress();
Is the `break;` statement still required?
I'd drop it as the statement is not reachable.

2024-09-12 19:34 UTC, schlimmchen commented on lib/ETHSPI/src/ETHSPI.h
> +#pragma once
Well, good thing that Andreas asked, because if that is the case (where did you get the code from originally?) then we MUST add attribution. And that's okay, we may use their work and derive from it (alter it), but we shall add license information and attribution. I suggest this at the top of ETHSPI.(c|h):

```
//-----------------------------------------------------------------------------
// 2024 Ahoy, https://ahoydtu.de
// adapted to OpenDTU-OnBattery
// Creative Commons - https://creativecommons.org/licenses/by-nc-sa/4.0/deed
//-----------------------------------------------------------------------------
```

2024-09-12 19:38 UTC, schlimmchen commented on src/NetworkSettings.cpp
>          return ETH.macAddress();
Please leave the break statement in.

2024-09-12 19:44 UTC, Gumbagubanga commented on src/PinMapping.cpp
> +#endif
I updated the opendtufusionv2 profile according to https://github.com/markusdd/OpenDTUFusionDocs.
But I believe i forgot the setting `-DOPENDTU_ETHERNET`.
Anything else to be aware of?

2024-09-12 19:57 UTC, AndreasBoehm commented on src/NetworkSettings.cpp
> +        ETH.begin(pin.eth_phy_addr, pin.eth_power, pin.eth_mdc, pin.eth_mdio, pin.eth_type, pin.eth_clk_mode);
I tested the change and it seems that what you original did was the right way to go.

`setupMode()` is called pretty often and the SPIPortManager is reporting warnings because of this that don't exist in reality. We would also initialize the ETHSPI or ETH a couple of times for no reason.

Sorry for not knowing about this before!
Please move the code back to the `init()` function and it should be working fine.

<details>
<summary>Log</summary>

```
21:51:29.033 > Starting OpenDTU
21:51:29.039 > Initialize FS... done
21:51:29.166 > Reading configuration... done
21:51:29.213 > Reading PinMapping... found valid mapping done
21:51:29.213 > [SPIPortManager] SPI0 and SPI1 reserved by 'Flash and PSRAM'
21:51:29.263 > Initialize Network... [SPIPortManager] SPI0 already in use by 'Flash'
21:51:29.263 > [SPIPortManager] SPI1 already in use by 'PSRAM'
21:51:29.263 > [SPIPortManager] SPI2 now in use by 'ETHSPI'
21:51:29.277 > ETH start
21:51:29.277 > done
21:51:29.278 > Setting Hostname... Initialize NTP... done
21:51:29.278 > Initialize SunPosition... done
21:51:29.281 > Initialize MqTT... done
21:51:29.288 > Initialize WebApi... done
21:51:29.288 > Initialize Display... done
21:51:29.288 > Initialize LEDs... done
21:51:29.289 > Check for default DTU serial... done
21:51:29.289 > done
21:51:29.289 > Initialize Hoymiles interface... 
21:51:29.289 > [SPIPortManager] SPI0 already in use by 'Flash'
21:51:29.289 > [SPIPortManager] SPI1 already in use by 'PSRAM'
21:51:29.289 > [SPIPortManager] SPI2 already in use by 'ETHSPI'
21:51:29.289 > [SPIPortManager] SPI3 now in use by 'NRF24'
21:51:29.301 > NRF: Connection successful
21:51:29.301 > [SPIPortManager] SPI0 already in use by 'Flash'
21:51:29.301 > [SPIPortManager] SPI1 already in use by 'PSRAM'
21:51:29.302 > [SPIPortManager] SPI2 already in use by 'ETHSPI'
21:51:29.302 > [SPIPortManager] SPI3 already in use by 'NRF24'
21:51:29.302 > [SPIPortManager] Cannot assign another SPI port to 'CMT2300A'
21:51:29.302 >   Setting radio PA level... 
21:51:29.302 >   Setting DTU serial... 
21:51:29.302 >   Setting poll interval... 
21:51:29.302 >   Setting verbosity... 
21:51:29.302 > done
21:51:29.303 > Initialize Huawei AC charger interface... 
21:51:29.303 > Invalid pin config
21:51:29.303 > Switch to WiFi mode
21:51:29.305 > [SPIPortManager] SPI0 already in use by 'Flash'
21:51:29.305 > [SPIPortManager] SPI1 already in use by 'PSRAM'
21:51:29.305 > [SPIPortManager] SPI2 already in use by 'ETHSPI'
21:51:29.305 > [SPIPortManager] SPI3 already in use by 'NRF24'
21:51:29.305 > [SPIPortManager] Cannot assign another SPI port to 'ETHSPI'
21:51:29.305 > Setting Hostname... done
21:51:29.314 > [SPIPortManager] SPI0 already in use by 'Flash'
21:51:29.314 > [SPIPortManager] SPI1 already in use by 'PSRAM'
21:51:29.314 > [SPIPortManager] SPI2 already in use by 'ETHSPI'
21:51:29.314 > [SPIPortManager] SPI3 already in use by 'NRF24'
21:51:29.314 > [SPIPortManager] Cannot assign another SPI port to 'ETHSPI'
21:51:29.345 > [DPL::announceStatus] waiting for valid date and time to be available
21:51:31.278 > ETH connected
21:51:31.280 > Switch to Ethernet mode
21:51:31.291 > Configuring Ethernet DHCP IP... done
21:51:31.291 > Setting Hostname... done
21:51:38.798 > ETH got IP: 10.0.0.35
21:51:38.799 > Network connected
21:51:39.350 > [DPL::announceStatus] waiting for valid date and time to be available
21:51:49.351 > Admin AP remaining seconds: 10 / 180
21:51:49.352 > [DPL::announceStatus] waiting for valid date and time to be available
21:51:59.355 > Admin AP remaining seconds: 20 / 180
21:51:59.356 > [DPL::announceStatus] waiting for valid date and time to be available
21:51:59.822 > [DPL::announceStatus] disabled by configuration
21:52:18.410 > Admin AP remaining seconds: 30 / 180
21:52:18.410 > Admin AP remaining seconds: 40 / 180
21:52:28.421 > Admin AP remaining seconds: 50 / 180
21:52:38.434 > Admin AP remaining seconds: 60 / 180
21:52:48.445 > Admin AP remaining seconds: 70 / 180
21:52:58.456 > Admin AP remaining seconds: 80 / 180
21:53:18.481 > Admin AP remaining seconds: 90 / 180
21:53:18.481 > Admin AP remaining seconds: 100 / 180
21:53:38.504 > Admin AP remaining seconds: 110 / 180
21:53:38.505 > Admin AP remaining seconds: 120 / 180
21:53:58.528 > Admin AP remaining seconds: 130 / 180
21:53:58.528 > Admin AP remaining seconds: 140 / 180
21:54:08.540 > Admin AP remaining seconds: 150 / 180
21:54:18.553 > Admin AP remaining seconds: 160 / 180
21:54:28.565 > Admin AP remaining seconds: 170 / 180
21:54:38.577 > Admin AP remaining seconds: 180 / 180
21:54:39.578 > Admin mode disabled
21:54:39.578 > [SPIPortManager] SPI0 already in use by 'Flash'
21:54:39.578 > [SPIPortManager] SPI1 already in use by 'PSRAM'
21:54:39.578 > [SPIPortManager] SPI2 already in use by 'ETHSPI'
21:54:39.578 > [SPIPortManager] SPI3 already in use by 'NRF24'
21:54:39.578 > [SPIPortManager] Cannot assign another SPI port to 'ETHSPI'
```

</details>

2024-09-12 20:06 UTC, Gumbagubanga commented on src/NetworkSettings.cpp
> +        ETH.begin(pin.eth_phy_addr, pin.eth_power, pin.eth_mdc, pin.eth_mdio, pin.eth_type, pin.eth_clk_mode);
No problem. I reverted that change :)

2024-09-12 20:07 UTC, AndreasBoehm commented on src/NetworkSettings.cpp
> +        ETH.begin(pin.eth_phy_addr, pin.eth_power, pin.eth_mdc, pin.eth_mdio, pin.eth_type, pin.eth_clk_mode);
Thank you!

2024-09-12 20:11 UTC, AndreasBoehm approved these changes

2024-09-12 20:15 UTC, schlimmchen commented on lib/ETHSPI/src/ETHSPI.h
> +#pragma once
Sorry, I assumed you created the upstream PR.

> I assumed it was their original work as there was no attribution.

I can see that now. Let's do it the right way :muscle: I see you added the comments I suggested.

2024-09-12 20:17 UTC, schlimmchen commented on src/PinMapping.cpp
> +#endif
> But I believe i forgot the setting -DOPENDTU_ETHERNET.

@AndreasBoehm Did he? Did you have to define this? I don't think so, you would have told us... You merely adjusted your pin_mapping.json, correc?

2024-09-12 20:18 UTC, Gumbagubanga commented on src/PinMapping.cpp
> +#endif
Reusing `_pinMapping.eth_enabled` might not be wise as it might interfere with the existing ethernet initialization.

If you take into consideration that other boards like the LilyGo ETH-Lite use different pins to connect a W5500, the enable-flag approach would work with a new flag like `_pinMapping.w5500_enabled`. Everyone using a not-(yet)-supported board additionally has to set it in the pin mapping.

In the end it comes down to how many profiles do you want to maintain?

2024-09-12 20:20 UTC, AndreasBoehm commented on src/PinMapping.cpp
> +#endif
I tried the `opendtufusionv2` env and did not need to do anything to get it to work. 
To get it to work with the `generic_esp32_s3_usb` env i had to update the pin_mapping.json, thats it.

Not sure what `-DOPENDTU_ETHERNET` does but i did not need it

2024-09-12 20:28 UTC, Gumbagubanga commented on src/PinMapping.cpp
> +#endif
@AndreasBoehm 
Does every opendtufusionv2 have the ethernet port? If not, would it harm to keep the pins configured in the environment?

2024-09-12 20:30 UTC, AndreasBoehm commented on src/PinMapping.cpp
> +#endif
No, not every opendtufusionv2 has the ethernet port.
I don't think that that it does any harm if we have the pins configured, because if someone is going to use those pins for something else they will need to provide a custom pin_mapping.json anyway

2024-09-12 20:33 UTC, schlimmchen commented on src/PinMapping.cpp
> +#endif
Hm... I am not yet happy with this. The issue is this: The opendtufusionv2 env should define the pins, but it should not mean that the env can only be used with a PoE hat.

I think I regret proposing to change the opendtufusionv2 env... A user who wants to use W5500 ethernet shall define the respective pins in the pin_mapping.json.

So the `eth` object in the pin_mapping.json only concerns the Ethernet MAC in non-S3 ESP32. In that case we should not even show these in the device manager on S3 devices... Meh, that's a different issue. And the `w5500` object in the pin_mapping.json now controls this feature.

Let's update https://github.com/helgeerbe/OpenDTU-OnBattery/blob/development/docs/DeviceProfiles/opendtu_fusion.json with two new mappings: One with NRF24 and W5500, another with CMT2300 and W5500. Add the respective documentation to opendtu-onbattery.net, and be done with it. Users will know what to do.

Oh, wait, it was a completely stupid idea to extend the opendtufusionv2 env: It now uses three SPI devices: NRF24, CMT2300 and W5500. Let's forget about this environment. I don't know why I pushed this. Users shall use the most generic firmware and add a pin_mapping.json.

2024-09-12 20:35 UTC, schlimmchen commented on src/PinMapping.cpp
> +#endif
> I don't think that that it does any harm if we have the pins configured

Doesn't it now try to init NRF24, then CMT2300, and fails to initialize W5500? Why did this work on your board?

2024-09-12 20:42 UTC, AndreasBoehm commented on src/PinMapping.cpp
> +#endif
> Doesn't it now try to init NRF24, then CMT2300, and fails to initialize W5500? Why did this work on your board?

It will fail to init CMT2300 because thats the device that comes last. I thought that this is fine if use the POE Hat because then i get the device onto the network at least and will see that the CMT2300 is not working right now.

I agree with your suggestion to remove the default pins from this env. As its not part of the default hardware people will know what to do to get it to work.

2024-09-12 21:09 UTC, Gumbagubanga commented on src/PinMapping.cpp
> +#endif
> Let's update https://github.com/helgeerbe/OpenDTU-OnBattery/blob/development/docs/DeviceProfiles/opendtu_fusion.json with two new mappings: One with NRF24 and W5500, another with CMT2300 and W5500.
Done

> Add the respective documentation to opendtu-onbattery.net, and be done with it. Users will know what to do.
I'll create a PR: https://github.com/schlimmchen/OpenDTU-OnBattery-docs/pull/15

2024-09-13 14:49 UTC, schlimmchen approved these changes

2024-09-13 14:51 UTC, merged

2024-09-13 14:52 UTC, schlimmchen commented
Thanks @Gumbagubanga :heart:

2024-09-30 19:23 UTC, schlimmchen commented
There are bittersweet news regarding this PR/feature: I am going to revert these changes in favor of the [upstream implementation of the SpiManager](https://github.com/tbnobody/OpenDTU/commit/9b9c1e29f15e44b85bc29ff79468bc171e47d522) and the [upstream support for W5500 Ethernet](https://github.com/tbnobody/OpenDTU/commit/851190dbccc0bbbf5aa7fa6580b72712b9b48079) to keep the diff between this project and the upstream to a minimum.

I am kind of sorry that we lose this unique selling point. I like to think that @Gumbagubanga's effort added to Thomas motivation to merge https://github.com/tbnobody/OpenDTU/pull/2306, which replaces this feature, because [earlier Versions of the W5500 support in the upstream project](https://github.com/tbnobody/OpenDTU/pull/2068) were not merged for a long time.

Thanks again to @Gumbagubanga and @marvincarstensen, as this feature was highly appreciated!

2024-09-30 19:42 UTC, schlimmchen commented
> No hard feelings. It's just code

And time!

> Don't forget to discard/reject my PR for the documentation project as well.

Oh no, that is still relevant and valid. The upstream docs should cherry-pick it :wink: Thanks for thinking about that!