Sanitize manufacturer name to avoid json errors.
helgeerbe/OpenDTU-OnBattery pull request #1235
Opened 2024-09-06 16:16 UTC by ranma

If the string contains control characters for some reason, the browser will reject the json with the error `bad control character in string literal`.

See https://github.com/helgeerbe/OpenDTU-OnBattery/discussions/1226#discussioncomment-10566898

2024-09-06 19:21 UTC, schlimmchen commented on src/PylontechCanReceiver.cpp
> +                    std::min(5, static_cast<int>(rx_message.data_length_code)));
why at most 5?

2024-09-07 06:41 UTC, ranma commented on src/PylontechCanReceiver.cpp
> +                    std::min(5, static_cast<int>(rx_message.data_length_code)));
Pylontech uses `PYLON`, Pytes uses `PYTES` and with DEYE also only the first 5 bytes are valid ASCII...

2024-09-07 06:53 UTC, ranma commented on src/PylontechCanReceiver.cpp
> +                    std::min(5, static_cast<int>(rx_message.data_length_code)));
Alternatively maybe use all bytes up to the first invalid character?

2024-09-07 07:38 UTC, schlimmchen commented on src/PylontechCanReceiver.cpp
> +                    std::min(5, static_cast<int>(rx_message.data_length_code)));
Okay, I understand where the 5 comes from, then. That would need a comment for our future selfs... I like it better when we rely on the function you implemented, which filters for valid ASCII.

2024-09-07 07:39 UTC, schlimmchen commented on src/BatteryStats.cpp
> +        sanitized[i] = '?';
Maybe sanitized[i]=0; break; ?

2024-09-07 11:26 UTC, ranma commented on src/BatteryStats.cpp
> +        sanitized[i] = '?';
Done! (Using .remove() from the Arduino String API: https://www.arduino.cc/reference/en/language/variables/data-types/string/functions/remove/)

2024-09-07 11:27 UTC, ranma commented on src/PylontechCanReceiver.cpp
> +                    std::min(5, static_cast<int>(rx_message.data_length_code)));
Removed the length restriction here.

2024-09-08 16:24 UTC, AndreasBoehm requested changes

2024-09-08 16:24 UTC, AndreasBoehm commented on src/PylontechCanReceiver.cpp
> +#include <algorithm>
Do we need this new import?

2024-09-08 16:39 UTC, ranma commented on src/PylontechCanReceiver.cpp
> +#include <algorithm>
Added this for std::min, but can indeed be removed now.

2024-09-09 11:48 UTC, ranma commented
maybe it would make even more sense to add string validation to `addLiveViewInSection()`, rather than specifically as a workaround for bad manufacturer strings.

2024-09-09 13:31 UTC, AndreasBoehm commented
imho it makes sense to do the cleanup when we set the manufacturer string because it always makes sense to fix issues at the source of the problem and we should not pass around bad strings

2024-09-09 19:37 UTC, schlimmchen commented
I agree with Andreas. The new function is not indented properly. I am going to fix this now so this can be merged.

2024-09-09 19:46 UTC, merged

2024-09-09 19:47 UTC, schlimmchen commented
Thanks, @ranma :rocket: