DPL: Honor battery-provided discharge power limit (including UI adjustments)
helgeerbe/OpenDTU-OnBattery pull request #1245
Opened 2024-09-10 17:00 UTC by AndreasBoehm

Based on the great work from @ranma!
Base: https://github.com/helgeerbe/OpenDTU-OnBattery/pull/1198

| MQTT Battery Provider | Other Battery Providers |
|------------------------|-------------------------|
|![Screenshot 2024-09-10 at 18 59 03](https://github.com/user-attachments/assets/f77f69b4-b233-410b-b94f-ff114ab0a378)|![Screenshot 2024-09-10 at 18 59 16](https://github.com/user-attachments/assets/db198124-a73b-4e4c-814c-81908aaa8042)|

2024-09-10 17:10 UTC, spcqike commented
One question after a first glance: 
How does the manual limit fit to the BMS value? The hint says it’s a fallback. So I guess the BMS value has greater priority, even I f it’s higher than the manual value? 
so a manual limit of like 10A won’t work, if the BMS reports 25A?

2024-09-10 17:13 UTC, AndreasBoehm commented
Good catch @spcqike, i need to update the hint text.

Whatever limit is lower will be used

`min(bmsLimit, userLimit)`

2024-09-10 17:23 UTC, AndreasBoehm commented
Screenshots updated

2024-09-10 17:33 UTC, AndreasBoehm commented
We will now also show a live view for MQTT batteries when the discharge current limit is present.

2024-09-13 15:22 UTC, schlimmchen requested changes
Some nitpicking to annoy you :wink:

2024-09-13 15:22 UTC, schlimmchen commented on include/BatteryStats.h
> +        virtual bool supportsAlarmsAndWarnings() const { return false; };
I know this is splitting hairs, but still: This method seems to be implemented in all derived classes. In that case this should be pure virtual instead. However, it would be much more efficient to implement this to return true in the base class, and only have the MQTT battery override this and return false.

2024-09-13 15:22 UTC, schlimmchen commented on src/BatteryStats.cpp
> +    if (isDischargeCurrentLimitValid()) {
Why do we only show a card if the discharge current limit is valid? As far as I can tell, we can call the base class method unconditionally?

2024-09-13 15:22 UTC, schlimmchen commented on src/Configuration.cpp
> +    battery["useBatteryReportedDischargeCurrentLimit"] = config.Battery.UseBatteryReportedDischargeCurrentLimit;
Please change this from CamelCase to snake_case. I think we don't use camel case anywhere in the config.json.

2024-09-13 15:22 UTC, schlimmchen commented on src/WebApi_battery.cpp
> +    root["useBatteryReportedDischargeCurrentLimit"] = config.Battery.UseBatteryReportedDischargeCurrentLimit;
Convert to snake case.

2024-09-13 15:22 UTC, schlimmchen commented on src/WebApi_battery.cpp
If you are motivated, please move this to a new function in the ConfigurationClass, similar to the existing serialize... and deserialize... methods I implemented there for the power meter config. I also did this for the refactored power limiter when implementing the support of multiple inveters.

2024-09-13 15:22 UTC, schlimmchen commented on webapp/src/types/BatteryConfig.ts
> +    useBatteryReportedDischargeCurrentLimit: boolean;
Remember to update to snake case here as well, as well as where the vars are used in the view.

2024-09-13 15:29 UTC, AndreasBoehm commented on src/BatteryStats.cpp
> +    if (isDischargeCurrentLimitValid()) {
Because only the discharge current limit is data that we are not showing in the live card on top of the screen yet, I used its existance to decided wheter we should the big live view here or not. Otherwise we would only repeat whats already shown in the top card.

2024-09-13 15:31 UTC, AndreasBoehm commented on src/Configuration.cpp
> +    battery["useBatteryReportedDischargeCurrentLimit"] = config.Battery.UseBatteryReportedDischargeCurrentLimit;
Good catch, must be some copy&paste mistake

2024-09-13 15:40 UTC, AndreasBoehm commented on webapp/src/types/BatteryConfig.ts
> +    useBatteryReportedDischargeCurrentLimit: boolean;
done

2024-09-13 15:40 UTC, AndreasBoehm commented on src/WebApi_battery.cpp
Very nice idea, i will do that

2024-09-13 15:40 UTC, AndreasBoehm commented on src/WebApi_battery.cpp
> +    root["useBatteryReportedDischargeCurrentLimit"] = config.Battery.UseBatteryReportedDischargeCurrentLimit;
done

2024-09-13 15:44 UTC, AndreasBoehm commented on include/BatteryStats.h
> +        virtual bool supportsAlarmsAndWarnings() const { return false; };
What i did here did not make much sense, i will keep the default implementation and only override it within the MQTT battery

2024-09-13 15:45 UTC, AndreasBoehm commented on src/BatteryStats.cpp
> +    if (isDischargeCurrentLimitValid()) {
done

2024-09-13 16:27 UTC, AndreasBoehm commented on src/WebApi_battery.cpp
done

2024-09-13 16:27 UTC, AndreasBoehm commented on src/Configuration.cpp
> +    battery["useBatteryReportedDischargeCurrentLimit"] = config.Battery.UseBatteryReportedDischargeCurrentLimit;
done

2024-09-13 18:22 UTC, schlimmchen approved these changes

2024-09-13 18:46 UTC, schlimmchen commented
Github did not manage to detect that the first commit is merely already on development. I had to rebase manually. This set me as the committer, which I don't like and wasn't my intention. After a quick Internet search it seems this is tedious to avoid...

2024-09-13 18:49 UTC, AndreasBoehm commented
Dont worry about having my name on a commit.. its alright.

after a rebase we will be both mentioned in the commit, thats fine for me

2024-09-13 18:52 UTC, merged

2024-09-13 18:54 UTC, schlimmchen commented
![image](https://github.com/user-attachments/assets/40daec73-c701-4157-9b31-65ef2d4adc14)

Interesting. "Squash and Merge" cleaned it up the way I wanted it to. Guess "authored by and committed by" is only ever a thing when pushing from the CLI? Don't know for sure. Glad that this turned out well :wink: 

> its alright.

Thanks!

2024-09-24 10:31 UTC, spcqike commented
@AndreasBoehm after following #1236, i thought...maybe it's good to also introduce a mqtt topic, where the user can set a "soft discharge limit" on its own. soft, as not persistent and only applied, when provided via mqtt or whatever, but available for all providers.

right now, we can set a fixed and persistent default current. we than have the battery provider, who "overwrites" the default limit (only if its lower). so an on-the-fly, self-defined lower limit only works for MQTT batteryprovider, and not for VE or CAN.

do you think, this is needed or usefull at all? (the same applies for DPL max limit, which can only be set persistant right now, can it?)

2024-09-24 10:45 UTC, AndreasBoehm commented
Could you describe a scenario in which this soft limit would be needed?

2024-09-24 11:53 UTC, spcqike commented
if you try to manage a weather forecast charging, somehow (which needs to be done external in IOBroker, HA, Node-Red, ..). like if you now, that the next days will be very cloudy, you won't charge your battery to 100% and you would like to limit discharge current (or inverter output in general), to not more than X, to keep currents and losses (as power losses increase with increasing currents) small, but still provide your basic load.

iguess, i would limit my system to ~ 400W in such cases.

or, if you want to charge your EV, but don't want to empty your battery. so you would just throttle or limit battery discharge to 0A, can still use PV for charging.  but just "soft", without writing to persistant memory.

2024-09-24 13:11 UTC, AndreasBoehm commented
hmm, for me this does not sound like a feature that brings a benefit besides the possibility to be in full control. If i use the energy of my battery within 2 hours or 12 hours doesn't really make a difference imho.

If you want to limit the charge of your EV to PV power only this should be done on the charger side, limiting it to the value that your inverter or solar charger provides.

2024-09-24 13:45 UTC, spcqike commented
> If you want to limit the charge of your EV to PV power only this should be done on the charger side, limiting it to the value that your inverter or solar charger provides.

thats not wrong, but its complicated and not easily doable.

its easier to say "ok, we charge the car, stop using the battery for now" and "finished / unplugged, use the battery again" (to commands, set current to 0 and back to whatever you want) and let openDTU-oB handle all PV production on its own, instead of creating another controlsystem that checks the available PV power and controls the wallbox all the time. its just another loop with its problems and disadvantages. 

and, not all chargers are remotly controllable. like my "stupid" charger, where i can pre-set a current beforehand, but i can't change it, after charging started.

> If i use the energy of my battery within 2 hours or 12 hours doesn't really make a difference imho.

it does. just a little, but it does. as P=UI². double current, four times power losses. so its more efficient to discharge with 400W for 5h instead of 2000W within 1h. (in this case its 5x more current, so 25x more power losses)