Fusion V2 RS485 SDM power meter support (RxEn, TxEn)
helgeerbe/OpenDTU-OnBattery pull request #1269
Opened 2024-09-20 21:46 UTC by Adminius

2024-09-20 21:49 UTC, Adminius commented
https://github.com/markusdd/OpenDTUFusionDocs/issues/10

2024-09-21 20:32 UTC, schlimmchen requested changes
This change makes a lot of sense. However, please keep the changes to the lib to an absolute minium.

2024-09-21 20:32 UTC, schlimmchen commented on lib/SdmEnergyMeter/SDM.cpp
> +}
Keep the changes to the SdmEnergyMeter lib to the absolute minimum. Remove all newly added c'tors which accept a HardwareSerial, because none of them are ever used.

2024-09-21 20:32 UTC, schlimmchen commented on lib/SdmEnergyMeter/SDM.cpp
> +}
One of the added c'tors accepting a SoftwareSerial is not needed. I think it's this one.

2024-09-21 20:32 UTC, schlimmchen commented on lib/SdmEnergyMeter/SDM.cpp
> +  dereSet(LOW); // set init state to receive from SDM -> DE Disable, /RE Enable (for control MAX485)
Absolute minimum changes to the lib, please. Leave the comments, indention, code formatting, etc. as is.

2024-09-21 20:32 UTC, schlimmchen commented on lib/SdmEnergyMeter/SDM.h
> +    SDM(SoftwareSerial& serial, long baud = SDM_UART_BAUD, int dere_pin = DERE_PIN, int re_pin = RE_PIN);
Clean up unused c'tors.

2024-09-21 20:32 UTC, schlimmchen commented on src/PowerMeterSerialSdm.cpp
> +
Formatting: add space after "if" and around "else", move "else" to a new line.

2024-09-23 19:14 UTC, schlimmchen approved these changes

2024-09-23 19:18 UTC, schlimmchen commented
I could test this, but I won't, at least not right now, as I trust that this works for you. The changes look clean and good and reasonable.

However, the new pins *must* be [documented](https://opendtu-onbattery.net/firmware/device_profiles/#implemented-configuration-values). Would you be willing to add the respective lines to the table and explain that one can either use the dere pin XOR the rxen/txen pins? Please open a pull-request against the docs repo if possible.

2024-09-23 19:20 UTC, merged