Producing DC Channel aware power limit application
helgeerbe/OpenDTU-OnBattery pull request #156
Opened 2023-04-02 20:17 UTC by qubeck

Following the observations the inverter internally distributes any applied power limit across all DC channels.
In case not all DC channels are connected only a fraction of the requested power limit becomes effective when the power limiter kicks in.

The proposed modification improves that by taking the number of actually producing DC channels into account to artificially increase the applied power limit accordingly.

2023-04-03 04:35 UTC, berni2288 commented on src/PowerLimiter.cpp
> +        if (effPowerLimit > config.PowerLimiter_UpperPowerLimit)
I think you maybe want to use the maximum inverter power limit instead here, instead of `config.PowerLimiter_UpperPowerLimit`, otherwise effPowerLimit might be lower than it could be, dependending on what the user has configured. 

Example:

- Inverter has 2 DC Inputs
- DC 1 is used
- Maximum inverter limit & current household consumption: 800
- config.PowerLimiter_UpperPowerLimit: 400

effPowerLimit would be 400 and inverter would produce 200W only. But effPowerLimit should be 800 so that the inverter produces 400.

2023-04-03 04:36 UTC, berni2288 commented
Thanks for this great PR!

Can I ask for some code style fixes? `){` --> `) {` and add missing `{` and `}`, thanks!

2023-04-03 15:51 UTC, qubeck commented
Sure, I'll do that in the next days. A little busy at the moment with other work.

2023-04-03 19:13 UTC, MalteSchm commented
I'm not sure that this should be done

The Hoymiles inverters act problematic if a single channel current goes over ~11.5A. In such a case the actual input current is no longer correctly measured and has actually jumped to about ~16A in my tests. The output power jumps accordingly. This is not a place you want to be in and will screw up things.

I understand that you increase the requested limit in cases where only a subset of the input channels is being used. This means that this tipping point is reached sooner. Let me know if my understanding is wrong.

I have thought about limiting / throwing an error when the inverter consumes over 11A.
Attached are some measurements I took (in German)

[Messungen_Hoymiles (1).xlsx](https://github.com/helgeerbe/OpenDTU-OnBattery/files/11141644/Messungen_Hoymiles.1.xlsx)

2023-04-04 05:05 UTC, qubeck commented
That's an interesting observation that you made. Well for me it's quite hard to reproduce this. I don't have a working battery setup yet and my panels Imp is below ~10A.
@berni2288 I would keep the limit still configurable for now to have that situation manageable at least. Also I think in a battery setup it's also important to have this max limit configurable to not drain your battery to much if household consumption jumps to frequently.

2023-04-04 05:15 UTC, qubeck commented on src/PowerLimiter.cpp
> +        if (effPowerLimit > config.PowerLimiter_UpperPowerLimit)
Oh I see your point if only one dc channel is producing the calculated factor to increase the newPowerLimit is 2x
But this also affects the upper limit check of course.
I'll fix that!

2023-04-04 08:36 UTC, berni2288 commented on src/PowerLimiter.cpp
> +        if (effPowerLimit > config.PowerLimiter_UpperPowerLimit)
yes exactly. But it might make sense to move the UpperPowerLimit code also to the method setNewPowerLimit, otherwise it's confusing.

2023-04-04 08:43 UTC, berni2288 commented
> The Hoymiles inverters act problematic if a single channel current goes over ~11.5A. In such a case the actual input current is no longer correctly measured and has actually jumped to about ~16A in my tests. The output power jumps accordingly. This is not a place you want to be in and will screw up things.

That's a good input. The datasheet of the Hoymiles HM-600 says that the Max Input current of HM-600 / HM-700 is 11.5A and for HM-800 it's 12.5A. Oh and HM-1000 has 11.5A only.

We should also implement a limit on those values. Now the problem is, I don't want to hardcode those max current limits for each Hoymiles model in our code... (then we would have to maintain this). We could create a new configuration option with a default value of 10.5A, that is used when not all DC inputs are connected. That's the best thing I can think of.

![image](https://user-images.githubusercontent.com/1029328/229736549-f3d9239c-bbbf-47c8-8c18-c2cbf1193bb3.png)

2023-04-04 09:10 UTC, berni2288 commented
> The Hoymiles inverters act problematic if a single channel current goes over ~11.5A. In such a case the actual input current is no longer correctly measured and has actually jumped to about ~16A in my tests. The output power jumps accordingly. This is not a place you want to be in and will screw up things.

But if Hoymiles already evenly distributes the limit to all DC channels, then it wouldn't go over 11,5A as long as you don't set the limit higher than the max inverter limit, right?
Example: Max limit: 800; temporary limit: 800; Limit per DC channel: 400.

2023-04-04 09:53 UTC, MalteSchm commented
I think mixing solar and batteries should not be done unless this is tested and for now the recommendation should be: don't do it and connect the battery to all input channels of the inverter

2023-04-04 09:56 UTC, berni2288 commented
> With a single channel connected to a HM 1500 any value that is was over about 50% created this problem.

Interesting, maybe it's just a problem with HM-1500 or a bug in OpenDTU that sets the 50% too high?
I'll test my HM-800 how it behaves with just 1 DC input on battery and 50%.

2023-04-04 10:42 UTC, swingstate commented
So 1 battery on one port (plus + minus = one port) and 3 panels on each of the other ports this should still work?

I wonder how the mppt reacts when there is no DC from one panel and still DC from the battery on that mppt.

However, this might be more a problem for the inverters with more than 1 port.

I am considering a HM-300 for my night time feeding of approx 80-150W - from a AC charged Battery.

2023-04-04 12:48 UTC, MalteSchm commented
> > With a single channel connected to a HM 1500 any value that is was over about 50% created this problem.
> 
> Interesting, maybe it's just a problem with HM-1500 or a bug in OpenDTU that sets the 50% too high? I'll test my HM-800 how it behaves with just 1 DC input on battery and 50%.

I'm pretty sure that all Hoymiles inverters will do weird things when you exceed the current limit. Similar issues have been reported by others (also with other inverter models). If you run them e.g. on 24V and try to reach the rated power you'll also run into this current range. 

But testing this would be good. I just think it may be too early for this project to handle these cases.

There are some related issues too:
- The currently available settings under "Dynamic Power Limiter" allow selection of a single channel. I suppose that this the channel that the battery is connected to. In my case the battery is connected to all 4 channels of the HM 1500. I went with ch0 in my case but (as a user) this confused me
- The web overview page requires an update to the summary information. I'm on this right now and wanted to:
-- Show solar day / total yield. This would include the Victron MPPT and any Hoymiles channel that is connected to solar
-- Show battery day / total energy. This would include any Hoymiles channel that is connected to the battery
-- Show the battery SoC

This makes the whole thing a bit complex and given that the channels are not individually mapped to solar / battery right now not easily possible (unless I overlook something)

2023-04-04 13:45 UTC, berni2288 commented
> * The currently available settings under "Dynamic Power Limiter" allow selection of a single channel. I suppose that this the channel that the battery is connected to. In my case the battery is connected to all 4 channels of the HM 1500. I went with ch0 in my case but (as a user) this confused me

Only 1 battery is support at the moment. The channel selection is just to read the battery voltage to stop/start the inverter when stop and start threshold are reached. The voltage is usually the same for all inputs anyway when they are connected to the same battery. But I recommend to use the Battery SOC instead of the voltage. But at the moment this is only supported for Pylontech batteries.
I agree that the documentation should be improved here.

> * The web overview page requires an update to the summary information. I'm on this right now and wanted to:
>   -- Show solar day / total yield. This would include the Victron MPPT and any Hoymiles channel that is connected to solar
>   -- Show battery day / total energy. This would include any Hoymiles channel that is connected to the battery
>   -- Show the battery SoC

The information is already there on the live page in the Victron MPPT panel and also for the Battery now (if you have a Pylontech connected with CAN interface).
Or do you mean the green fact boxes at the top? Yeah new green boxes would be great, I already thought about adding some more.

2023-04-04 15:54 UTC, MalteSchm commented
> The information is already there on the live page in the Victron MPPT panel and also for the Battery now (if you have a Pylontech connected with CAN interface). Or do you mean the green fact boxes at the top? Yeah new green boxes would be great, I already thought about adding some more.

Yes I mean the green boxes.

2023-04-04 19:45 UTC, MalteSchm commented
Created draft PR in https://github.com/helgeerbe/OpenDTU-OnBattery/pull/157 to have those information updated.

2023-04-05 18:40 UTC, berni2288 commented
@MalteSchm 

I've now tried to reproduce your described problem with my HM-800, however I don't see the Ampere going too high.

![image](https://user-images.githubusercontent.com/1029328/230174247-c72f97ab-efb8-4a08-ba05-0ba6743647e9.png)

The numbers are correct like I would expect it. Maybe a 4 DC-input specific Hoymiles-Bug?
I can't believe that the Hoymiles inverter would not support just connecting 1 DC input and leaving the others disconnected and setting the limit to 50%.

2023-04-05 19:29 UTC, MalteSchm commented
> @MalteSchm
> 
> I've now tried to reproduce your described problem with my HM-800, however I don't see the Ampere going too high.
> 
> ![image](https://user-images.githubusercontent.com/1029328/230174247-c72f97ab-efb8-4a08-ba05-0ba6743647e9.png)
> 
> The numbers are correct like I would expect it. Maybe a 4 DC-input specific Hoymiles-Bug? I can't believe that the Hoymiles inverter would not support just connecting 1 DC input and leaving the others disconnected and setting the limit to 50%.

No, I wrote that there is an issue when you exceed the current limit. Max current is 8A in your test, so you have not reached this limit yet. (And you never will as you're using 48V)
A single channel on a 4 channel inverter will reach this point at 48V. 

Anyway do as you like. I just think that this level of flexibility has side effects

2023-04-05 19:53 UTC, berni2288 commented
> No, I wrote that there is an issue when you exceed the current limit. Max current is 8A in your test, so you have not reached this limit yet. (And you never will as you're using 48V) A single channel on a 4 channel inverter will reach this point at 48V.

I would understand your point if your spreadsheet would have DC input voltages of 24V. But you have 52V.
1500 W / 4 channels = 375W. With 375W the current should be ~7A. Or is the set limit not evenly distributed among the DC channels?

But I see the problem when a 24V battery would be used. Then it would be over 14 Amps = too much.

2023-04-05 20:03 UTC, berni2288 commented
@qubeck I've tested your PR with 1 DC connected and 2 DC connected and I didn't see any problems. The limit was correctly set in both cases.

2023-04-07 20:10 UTC, berni2288 requested changes
2 change suggestions. For the Too-much-Ampere issue, I've created another issue https://github.com/helgeerbe/OpenDTU-OnBattery/issues/163

2023-04-07 20:10 UTC, berni2288 commented on src/PowerLimiter.cpp
> +        }
`/ dcProdChnls` could lead to a division by zero error/crash if it is 0. This change should fix this.

```suggestion

        int32_t effPowerLimit;
        if (dcProdChnls > 0) {
            effPowerLimit = round(newPowerLimit * static_cast<float>(dcTotalChnls) / dcProdChnls);
            uint16_t inverterMaxPower = inverter->DevInfo()->getMaxPower();

            if (effPowerLimit > inverterMaxPower) {
                effPowerLimit = inverterMaxPower;
            }
        } else {
            effPowerLimit = config.PowerLimiter_LowerPowerLimit;
        }
```

2023-04-07 20:10 UTC, berni2288 commented on src/PowerLimiter.cpp
> +            if (inverter->Statistics()->getChannelFieldValue(TYPE_DC, c, FLD_PDC) > 0) {
I've unplugged the cables from one channel, and noticed that there is still some power being shown (`0.1 W`), even after 10 minutes, so the `> 0` actually didn't work for me. I therefore changed it to `> 1.0`, should be good enough.
It's maybe because the capacitor still has voltage on it, or I don't know...

```suggestion
            // There always seems to be some power < 1.0W, even when there are no cables connected.
            if (inverter->Statistics()->getChannelFieldValue(TYPE_DC, c, FLD_PDC) > 1.0) {
```

2023-04-11 11:44 UTC, berni2288 commented on src/PowerLimiter.cpp
> +            if (inverter->Statistics()->getChannelFieldValue(TYPE_DC, c, FLD_PDC) > 0) {
We could also check for a voltage > 20V instead?

2023-04-12 18:52 UTC, qubeck commented on src/PowerLimiter.cpp
> +            if (inverter->Statistics()->getChannelFieldValue(TYPE_DC, c, FLD_PDC) > 0) {
@berni2288 Thanks for mentioning that issue. I applied your suggestion using `> 1.0` with a slight modification from my side to explicitly fall back to the `newPowerLimit` in such a case.

2023-04-23 16:36 UTC, helgeerbe commented
What is the state of this PR?

2023-04-25 14:59 UTC, qubeck commented
> What is the state of this PR?

Well, it it's working with changes suggested by @berni2288 and slight modification from my side. Just waiting for review...

2023-04-25 16:39 UTC, closed without merging