Added option to limit AC charger power based on battery SoC
helgeerbe/OpenDTU-OnBattery pull request #449
Opened 2023-09-18 19:55 UTC by eu-gh

My personal setup includes the Huawei AC charger connected to a Pylontech battery, both of which are connected to the OpenDTU via CAN bus. I'm also using the option for automatic power control of the charger based on Power Meter readings, whichs works pretty good most of the time. 

However, on a sunny day, the current implementation keeps charging the battery at the maximum set power until it is (almost) full, which is probably not really helping the cells long-term health. At least the Pylontech's BMS reports a maximum current of 10A at a SoC above 89% instead of the usual 25A.

So I added an option to the charger settings which lets the user enter a SoC threshold and also a second, reduced maximum power value if that SoC is reached. After I spend several hours on being able to actually see these new options on my machine (including the realization that the PlatformIO build does indeed not rebuild the WebApp and the journey to getting the whole NodeJS/NPM(Corepack/Yarn stuff to work), I was also successfully able to do a test run.

Looks like this:
![grafik](https://github.com/helgeerbe/OpenDTU-OnBattery/assets/141823622/f0bdb6e4-55bc-46d3-9e00-bdd1ca8aaee4)

2023-09-22 14:03 UTC, schlimmchen requested changes

2023-09-22 14:03 UTC, schlimmchen commented on src/Huawei_can.cpp
> +          // Limit power to maximum
Missing an empty line before this comment, and comment was indented by accident. It should actually not change.

2023-09-22 14:03 UTC, schlimmchen commented on src/Huawei_can.cpp
> +              MessageOutput.printf("[HuaweiCanClass::loop] Current battery SoC %i reached threshold %i, reducing output power to %f \r\n", _batterySoC, config.Huawei_Auto_Power_BatterySoC_Threshold,
How often will this appear once the threshold is reached? In every call to loop()? Or is this section of the function only reached with a fixed interval? I am asking to make sure that this does not flood the serial line or the web console.

2023-09-23 07:02 UTC, eu-gh commented on webapp/.gitignore
> +.yarn
Correct, but I didn't know any other way to avoid pushing the 400+ cached yarn packages into the repo.

2023-09-23 07:02 UTC, eu-gh commented on webapp/src/locales/de.json
> +        "EnableReducePowerOnBatterySoCHint": "Wenn eine Batterie per CAN-Bus verbunden ist, kann die maximale Ausgangsleistung ab einem bestimmten SoC reduziert werden",
Will do 👍

2023-09-23 07:06 UTC, eu-gh commented on webapp/src/views/AcChargerAdminView.vue
> +                </CardElement>
I honestly don't know, but I will change it.

2023-09-23 07:07 UTC, eu-gh commented on webapp/yarn.lock
How do I do this without altering the included .gitignore file?

2023-09-23 07:07 UTC, eu-gh commented on webapp_dist/index.html.gz
How do I do this without altering the included .gitignore file?

2023-09-23 07:07 UTC, eu-gh commented on src/Huawei_can.cpp
> +          // Limit power to maximum
Fixed.

2023-09-23 07:18 UTC, eu-gh commented on src/Huawei_can.cpp
> +              MessageOutput.printf("[HuaweiCanClass::loop] Current battery SoC %i reached threshold %i, reducing output power to %f \r\n", _batterySoC, config.Huawei_Auto_Power_BatterySoC_Threshold,
It does get called regularly when the battery SoC threshold is reached, but since all other outputs in this function are like this, it doesn't really make a huge difference.

Personally, I would like to add a verbose logging switch to this settings page and link most console outputs to it, but I didn't get around to it yet.

2023-09-23 10:19 UTC, MalteSchm commented
Hi @eu-gh 

Would it not be better to read the maximum current from the BMS, subtract the current that a Victron charger delivers and use this as maximum current for the Huawei charger?
This was on my mind but I have not yet had the time to do this.

This makes this work without any user interface action and is a solution that just works without figuring out the SoC values manually (current will also depend on the battery temperature)

BTW: I have a draft PR here that fixes the CAN communication bus issue: https://github.com/helgeerbe/OpenDTU-OnBattery/pull/454

2023-09-24 20:20 UTC, schlimmchen commented on webapp_dist/index.html.gz
Do not `git add` any file in `webapp_dist` even if it is marked as modified. Or in other words: When crafting a commit, do not include `webapp_dist`. You question seems to suggest that you don't know what the git staging area is and how to use it. You are enabled to select particular files and even particular changes within a file for the next commit.

2023-09-24 20:22 UTC, schlimmchen commented on webapp/.gitignore
> +.yarn
See my comment below regarding the git staging area and selecting **parts** of your workdir to be included in the next commit.

2023-09-24 20:25 UTC, schlimmchen commented on webapp/src/views/AcChargerAdminView.vue
> +                </CardElement>
Hm? Now the diff looks way to big... There are now changes to pats that are not concerned with this feature.

2023-09-28 11:11 UTC, helgeerbe commented
What is the state of this PR? I will convert it to draft, until someone informs me, that it is ready to merge.

2023-10-01 09:30 UTC, eu-gh commented
@MalteSchm 
> Would it not be better to read the maximum current from the BMS, subtract the current that a Victron charger delivers and use this as maximum current for the Huawei charger? This was on my mind but I have not yet had the time to implement this.

This was my first intention too, but if I've seen this correctly, only the Pylontech BMS delivers this kind of data, which would make this feature exclude the two additional battery interfaces we gained in the meantime.
> This makes this feature work without any user interface action and is a solution that just works without figuring out the SoC values manually (the correct max current will also depend on the battery temperature and cell imbalance so it is not gonna be correct if set manually)

Albeit these are both valid points, non of the stuff we do here is production-grade or even standardized by any means, so I believe that the possibility to set options manually is more of a pro than a con. Also, the use cases are varying heavily. 

Two personal examples: 

- A stack of two US2000Cs wired in parallel configuration -> can take up to 50 amps, but (each) BMS reports only 25, so the charging current would be unnecessary limited
- Distributing the available energy dynamically to multiple endpoints, e.g. a car charger -> this is much easier to do if the storage battery limits its charging power by itself

Also I would like to add a feature to stop charging at a certain SoC altogether, but that's for a different PR.

@helgeerbe 
I've been using my personal build with this feature enabled for the last two weeks now and from my point of view, it's a really nice, simple addition without any real drawbacks. I don't see why this shouldn't be merged, but it is not on me to decide this.

2023-10-01 09:32 UTC, eu-gh commented on webapp/src/views/AcChargerAdminView.vue
> +                </CardElement>
Purely cosmetic, I added another <div> layer so the input fields will disappear altogether if the charger is disabled.

2023-10-01 09:33 UTC, eu-gh commented on webapp_dist/index.html.gz
I get it now, the GitHub client was adding all changed files by itself per default. Thanks!

2023-10-04 12:51 UTC, eu-gh commented
Superseded by https://github.com/helgeerbe/OpenDTU-OnBattery/pull/480

2023-10-04 12:51 UTC, closed without merging