Integration of Victron SmartShunt via VE.Direct
helgeerbe/OpenDTU-OnBattery pull request #452
Opened 2023-09-19 22:20 UTC by philippsandhaus

This a first draft of my integration as discussed in https://github.com/helgeerbe/OpenDTU-OnBattery/issues/205. As I did quite a lot of restructuring and I am not that confident in C++ I am marking this as draft and hereby ask for feedback from @schlimmchen and/or @helgeerbe. I rebased the current status on top of the development branch.

<img width="1386" alt="Bildschirmfoto 2023-09-17 um 22 38 20" src="https://github.com/helgeerbe/OpenDTU-OnBattery/assets/3939346/217105c1-c5c8-4a1f-8494-65aafd43e19c">
<img width="1368" alt="Bildschirmfoto 2023-09-17 um 22 08 23" src="https://github.com/helgeerbe/OpenDTU-OnBattery/assets/3939346/8f7a92c3-0e82-46bf-b8a7-91adbafd7529">

2023-09-20 11:58 UTC, helgeerbe commented
@philippsandhaus good job! I just looked at the frame handler. I would propose to use a `VeDirectController`base class and derive 'veDirectShuntController`and `VeDirectMpptController`from it. 

Advantage is, that you can do the generic stuff like init of the HardwareSerial in the base class and you have to implement it only once. Do only device specific in the DeviceController class.

2023-09-20 13:20 UTC, schlimmchen approved these changes

2023-09-20 13:20 UTC, schlimmchen commented on webapp/src/locales/en.json
> +        "ProviderVictron": "Victron SmartShunt using VE.Direct Interface",
This is missing in fr.json.

2023-09-20 19:34 UTC, philippsandhaus commented on lib/VeDirectFrameHandler/VeDirectFrameHandler.h
> +
Noting ;-) I removed them.

2023-09-20 19:38 UTC, philippsandhaus commented on include/BatteryStats.h
> +        void setSoC(uint8_t SoC) { _SoC = SoC; _lastUpdateSoC = millis(); }
Yes, removed it

2023-09-20 19:38 UTC, philippsandhaus commented on include/BatteryStats.h
> +        void setLastUpdate(uint32_t ts) { _lastUpdate = ts; }
Yes, removed it.

2023-09-20 19:40 UTC, philippsandhaus commented on include/BatteryStats.h
> +        float _voltage;
Yes, I did. Made them private now.

2023-09-20 19:41 UTC, philippsandhaus commented on lib/VeDirectFrameHandler/VeDirectMpptController.cpp
> +	if (_verboseLogging) _msgOut->println("Finished init MPPTCOntroller");
Done

2023-09-20 19:49 UTC, philippsandhaus commented on webapp/src/locales/de.json
> +        "ProviderVictron": "Victron SmartShunt per VE.Direct Interface",
Done

2023-09-20 19:50 UTC, philippsandhaus commented on webapp/src/locales/en.json
> +        "ProviderVictron": "Victron SmartShunt using VE.Direct Interface",
Hmm, the whole batteryadmin section is missing for. I copied the complete section from en for now. I guess the whole file has to be translated at some point.

2023-09-20 19:53 UTC, philippsandhaus commented on src/VictronSmartShunt.cpp
> +        MessageOutput.println(F("[Pylontech] Invalid pin config"));
Adjusted ;-)

2023-09-20 20:01 UTC, philippsandhaus commented on webapp/src/locales/en.json
> +        "nrChargedCycles": "Number of charged cycles",
I just looked into the Victron App. It just calls it charge cycles (Ladezyklen). So I guess I just copy that.

2023-09-20 20:02 UTC, philippsandhaus commented on webapp/src/locales/fr.json
> +        "model": "Model"
It was in an intermediate version. I removed it now.

2023-09-20 20:08 UTC, philippsandhaus commented on lib/VeDirectFrameHandler/VeDirectMpptController.h
> +    virtual void textRxEvent(char * name, char * value);
Thanks, this is exactly the kind of feedback I need. Forces me to understand the meanings of final, virtual, override etc. I guess final is the right one here.

2023-09-20 20:17 UTC, philippsandhaus commented on lib/VeDirectFrameHandler/VeDirectShuntController.h
> +    void frameEndEvent(bool) override;                 // copy temp struct to public struct
Changed to final

2023-09-20 20:17 UTC, philippsandhaus commented on lib/VeDirectFrameHandler/VeDirectShuntController.h
> +    virtual void textRxEvent(char * name, char * value);
Changed to final

2023-09-20 20:25 UTC, philippsandhaus commented
Thanks for the review. I adjusted my code accordingly and also moved initialization of the HardwareSerial interface to the base class. As far as I know there are only 2 HardwareSerial interfaces on the ESP32, right? So if there are more than 2 serial devices, one would have to think about some kind of management and also use SoftwareSerial, I guess.

Yes, for me the MPPT interface still works as before.

2023-09-21 08:07 UTC, schlimmchen requested changes

2023-09-21 08:07 UTC, schlimmchen commented on src/VictronSmartShunt.cpp
> +    VeDirectShunt.init(rx, tx, &MessageOutput, verboseLogging);
`_veDirectShunt = std::make_unique<VeDirectShuntController>()` goes here. consider removing the VeDirectShuntController::init() method and doing its work in the constructor instead.

2023-09-21 10:35 UTC, helgeerbe commented
I wouldn't mind, if we switch to Software Serial completely for ve.direct devices. Guess this makes the orchestration easier. @schlimmchen pointed out baudrate is moderate and the actual loop time is fast enough. 

Just thinking loud, if we are going to support also a second charger.

2023-09-21 15:20 UTC, philippsandhaus commented
`SoftwareSerial` and `HardwareSerial` both derive from `Stream`. I envision a class like `SerialProvider` which provides instances of `Stream` with for example `SerialProvider.getSerial(19200, SERIAL_8N1, rx, tx)`. 'SerialProvider' could then make the decision to hand an instance of `HardwareSerial` or `SoftwareSerial` based on baudrate and/or availability of hardware serial ports. But I guess the tricky parts are the details like how to get notified when a Hardware Serial port is freed up.

2023-09-21 15:25 UTC, schlimmchen commented
@philippsandhaus Interesting thoughts! How about you open up a new issue where we can discuss this (rather than being buried in this PR)?

2023-09-21 15:44 UTC, schlimmchen commented
@philippsandhaus I see there are values in `veShuntStruct` that are of type double. However, all values are always converted using `atoi`. I think it's fine to save the values as they were on the serial line, i.e., integers, and to do the scaling later -- even though this is different than in the MPPT counterpart. You do the scaling in `VictronSmartShuntStats::updateFrom`. If so, shouldn't the values in the `veShuntStruct` be all `int32_t`?

2023-09-21 16:14 UTC, schlimmchen commented
@philippsandhaus Feel free to cherry pick from https://github.com/schlimmchen/OpenDTU-OnBattery/commits/devel for this PR -- if you like. And except for the SoftwareSerial commit, that's a work in progress and requires testing.

2023-09-21 19:04 UTC, philippsandhaus commented on lib/VeDirectFrameHandler/VeDirectFrameHandler.cpp
> +void VeDirectFrameHandler::init(Print* msgOut, bool verboseLogging, uint16_t rx, uint16_t tx, uint16_t hwSerialPort)
Cherry picked your changes

2023-09-21 19:09 UTC, philippsandhaus commented on lib/VeDirectFrameHandler/VeDirectFrameHandler.cpp
> +	_vedirectSerial = new HardwareSerial(hwSerialPort);
Cherry picked your changes

2023-09-21 19:10 UTC, philippsandhaus commented on lib/VeDirectFrameHandler/VeDirectFrameHandler.cpp
> +    _vedirectSerial->flush();
Cherry picked your changes

2023-09-21 21:58 UTC, philippsandhaus commented
Great, I have cherry picked most of your adjustments. I also added handling of alarm cases for the live view. At least for me this PR would now be complete.

2023-09-22 14:27 UTC, schlimmchen commented
> At least for me this PR would now be complete.

Affirmative.

2023-09-22 14:34 UTC, helgeerbe commented
Cool. I could merge it into development. But I'm away from keyboard next week. So I would keep it in development for one additional week for further testing, before I release it. Are you fine with that?

2023-09-22 14:37 UTC, swingstate commented
I'll install a SmartShunt 500A tomorrow morning and was assuming you're going to release, however no worries - I'll compile development and flash that to my DTU for testing. Will report any findings and if no issue report back a "no issues"

2023-09-22 15:19 UTC, philippsandhaus commented
> Cool. I could merge it into development. But I'm away from keyboard next week. So I would keep it in development for one additional week for further testing, before I release it. Are you fine with that?

Sure, no problem.

2023-09-22 15:24 UTC, merged

2023-09-22 15:25 UTC, swingstate commented
guess now it is. I'll compile and flash my ESP tomorrow morning.

2023-09-22 15:33 UTC, helgeerbe commented
It's in development now. And it's on my OpenDTU.
Happy testing!

2023-09-22 16:09 UTC, helgeerbe commented
I removed the line. From my point of view. You should do the build locally. 
Action is only used to ensure, that every commit to development results in code that is compilable.

2023-09-24 11:40 UTC, swingstate commented
@helgeerbe I have the code on my ESP now and so far things look good, SOC is being displayed. I have one unclarity which I shared in the longer issue thread #205.