re-factoring of HttpPowerMeter
helgeerbe/OpenDTU-OnBattery pull request #594
Opened 2024-01-04 21:23 UTC by Fribur

Added ability to deal with local host names (mDNS), remove use of FirebasedJson to save ~20kB build size, some changes to PowerLimiter to avoid setting new inverter power limits when not needed (=current limit as reported by inverter is within hysteresis)

2024-01-04 22:26 UTC, helgeerbe commented
Can we remove in `platformio.ini` `mobizt/FirebaseJson @ ^3.0.6` or is it used elsewhere?

2024-01-04 23:24 UTC, Fribur commented
Indeed, I cannot see FirebaseJson used anywhere else, so can be removed from platformio.ini. Done in last commit.

2024-01-05 08:36 UTC, schlimmchen requested changes
I appreciate that you switched the JSON parsing to a library that is already available, saving so much code. Good job! This PR is hard to do a review on because you changed a lot at once. The refactoring you did is desirable and a refactoring is always harder to review.

2024-01-05 08:36 UTC, schlimmchen commented on src/HttpPowerMeter.cpp
> +#include <ArduinoJson.h>//saves 20kB to not use FirebaseJson as ArduinoJson is used already elsewhere (e.g. in WebApi_powermeter)
the content of this comment is interesting, but not in the source code. this should be mentioned in the commit message instead.

2024-01-05 08:36 UTC, schlimmchen commented on src/HttpPowerMeter.cpp
> +        }
if the hostname is not an IP address, you require mDNS to be enabled and throw an error if not? that's not okay. the hostname could be a perfectly valid DNS name and it must be resolved using regular DNS, as before.

2024-01-05 08:36 UTC, schlimmchen commented on src/HttpPowerMeter.cpp
> +}
wrong indention. and why is this so heavily relying on (different) char arrays and snprintf? all I see is string concatenation. use `String::operator +` and don't use manual error-prone char array length calculations.

2024-01-05 08:36 UTC, schlimmchen commented on src/HttpPowerMeter.cpp
> -
why is this empty line removed?

2024-01-05 08:36 UTC, schlimmchen commented on src/PowerLimiter.cpp
do not mix different changesets into one PR. these changes have nothing to do with your original intention (mDNS or http power meter refactor).

2024-01-05 08:36 UTC, schlimmchen commented on src/WebApi_powermeter.cpp
> +    // ESP.restart();
so this also is not related to mDNS or refactoring. you are asking a valid question (why is rebooting required here), but it is indeed required to perform a reboot here. if the user changes power meter settings, especially when switching the interface, these changes are currently not applied until the device reboots. remove this change. you may put in a comment that explains the requirement for a reboot, that would be fine.

2024-01-05 13:07 UTC, Fribur commented on src/HttpPowerMeter.cpp
> +        }
Do you know how to test if a hostname is local (to be resolved by regular DNS) or remote (mDNS)? I will research. I wish WifiClient would just take care of it and we do not have to figure this out here :-(

2024-01-05 13:27 UTC, Fribur commented on src/HttpPowerMeter.cpp
> +}
The motivation to avoid String::operator + is to avoid the [heap looks like swiss cheese after a while](https://cpp4arduino.com/2020/02/07/how-to-format-strings-without-the-string-class.html)...when used in abundance in such a hot function that concatenates so many strings every few seconds (when digest is used). As you know every "+' discards the prior string and allocates a new one. Why when one allocation can do it all? I had impression generally the OpenDTU code generally uses fixes size char arrays vs strings. What do you you think about using max size of each field [as per specification ](https://httpwg.org/specs/rfc7616.html) (e.g. sh256 digest response 64 hexadecimal characters) for the initialization of the receiving char array? So 
```
char responsePrep[256];
instead of 
char responsePrep[sizeof(ha1)+sizeof(nc)+sizeof(cNonce)+4+sizeof(ha2) + 5];
```

2024-01-05 13:29 UTC, Fribur commented on src/HttpPowerMeter.cpp
> -
Not sure. I guess because I removed the one line space between end of each function and begin of next one when sorting the order of the functions (collapsed them in editor for that purpose). Shall I keep 1 line space between each function?

2024-01-05 13:30 UTC, Fribur commented on src/PowerLimiter.cpp
OK. Will remove all changes to PowerLimiter. Agree we need to continue this discussion elsewhere :-)

2024-01-05 13:31 UTC, Fribur commented on src/WebApi_powermeter.cpp
> +    // ESP.restart();
Got it. After creating the pull request I actually found somewhere a discussion on GitHub about why this reboot is needed. Will remove.

2024-01-05 13:44 UTC, schlimmchen commented on src/HttpPowerMeter.cpp
> +        }
my approach would be this: skip processing hostname if hostname is an IP address (this is done already). if mDNS is enabled and mDNS was successful in resolving the address, use that as the new hostname. otherwise, leave hostname as is (presumably it is a valid DNS name).

2024-01-05 13:55 UTC, schlimmchen commented on src/HttpPowerMeter.cpp
> +}
thanks for providing the links! if you read the (article linked in the one you linked)[https://cpp4arduino.com/2018/11/06/what-is-heap-fragmentation.html] you will notice that even the author of the article admits that short-lived heap allocated objects are no real concern. regarding this function: all those strings will be gone and cleaned up after the function returns. what's the fuzz? also: this guy is talking about Arduino. and the part that grinds my gear is that Arduino != Arduino. of course you will avoid String or std::string on an Arduino nano with 6KB of RAM. of course! OpenDTU-OnBattery, however, is running on an ESP32 with close to 300KB of RAM.

I really don't see the issue. I might be wrong and ignorant, but until someone or some data convinces me that heap fragmentation is an actual issue for this project, I will push using modern code. complaining that no 100KB block of consecutive memory is available for a particular JSON response is not proof of memory fragmentation. we should not expect to be able to allocate 33% of the whole RAM in a consecutive block.

I understand that you want to avoid heap fragmentation, that's noble. I think that this part of the code is very hard to maintain and the array size calculations are a nightmare. :wink:

2024-01-05 13:56 UTC, schlimmchen commented on src/HttpPowerMeter.cpp
> -
well, yes, but the more interesting goal is to keep the changeset small. I will support removing trailing whitespace in a region where changes are done anyway, or removing useless empty lines. but this change is a step backwards.

2024-01-05 13:57 UTC, schlimmchen commented on src/PowerLimiter.cpp
thanks for agreeing!

2024-01-05 15:18 UTC, Fribur commented
OK I made a new commit, hopefully addressing all your requests. Do you see the commits? Thanks a bunch for the review!

2024-01-05 15:21 UTC, Fribur commented on src/HttpPowerMeter.cpp
> +}
OK, if you insist I can change back to `String::operator +` My last argument for keeping the snprintf way of doing it is safety: 

> In particular, never ever use a string that comes from user input as the format string because it would be an easy target for the aspiring hacker. When I say “a user input,” I mean anything that comes from the outside of the code, including configuration files and HTTP requests or responses. Ignoring this commandment would open the door to a [format string attack](https://owasp.org/www-community/attacks/Format_string_attack).

2024-01-05 15:32 UTC, Fribur commented on src/HttpPowerMeter.cpp
> +        }
Ok this is how I did it now:  If url is not an IP address to begin with, I now try to resolve via DNS (as done by WifiClient:connect), and only if that fails I try mDNS.

2024-01-05 16:01 UTC, schlimmchen commented on src/HttpPowerMeter.cpp
> +}
No, I do not insist. I will ring you up once this function needs a change and you will do it :grin:

Your argument regarding safety is invalid. The format strings you use are all string literals. The user input is formatted according to those string literals, but the user input is not the format string. The issue only concerns interpretation of user input as format strings.

But wait a minute... I looked again at the user inputs.

```char h1Prep[sizeof(username)+sizeof(realm)+sizeof(password)+2];```

This is not doing what you think it does. `sizeof(String)` is not the length that the `String` object is managing, it's the size of the String object itself (which is constant). This implementation certainly leads to stack corruption. And once you try to use `String.length()` you will see that you cannot allocate a char array with a value calculated at runtime. Have you tried this code?

This must be fixed.

You can either allocate char arrays with a size that will be sufficiently large in any case, or.... Well you know what I am going to tell you :wink:

2024-01-05 16:16 UTC, Fribur commented on src/HttpPowerMeter.cpp
> +}
OK. I go back "+" :-) 

Unrelated, I also noticed I did not pass the https bool to HTTPclient.begin(). So some more minor change to deal with that in the next commit. Are you able to still follow in your review or should I create a new Pull request with all those changes?

2024-01-05 20:14 UTC, Fribur commented on src/HttpPowerMeter.cpp
> +        }
Actually, we first have to do mDNS and then DNS, otherwise console will get spammed by WifiGeneric::hostByName failed error.

2024-01-08 13:32 UTC, helgeerbe commented
@Fribur I'm sorry. With the latest merge of the upstream code, we have a merge conflict. Can you resolve it.
For the rest, is it ready to be merged into development?

2024-01-08 16:03 UTC, Fribur commented
Thanks for notifying me about the conflict...did not realize the ball is on my end to resolve. I just did. From my perspective this pull request is final. It is working reliably with those changes now sience 2 days on my end. Please not however I cannot test the refactored digest authorization as I got no Digest compatible Power Meter (Shelly EM can only do basic authorization). So if you could verify Digest authorization after the merge that would be great!

2024-01-08 18:32 UTC, helgeerbe commented
Thanks for resolving the conflicts.  I know, I'm a bit lazy, but you know your code, better than me.  I own, only a normal Sehelly EM, but I have a Shelly PM 1 plus (which support digest auth). I will give it a try.

2024-01-08 19:10 UTC, helgeerbe commented
Just installed this PR locally. 
I get successful requests but see sometime also:
- http error connection lost
- Bad HTTP code: 401
I use basic authentication.

But in the past I saw also connection problems to my shelly EM

2024-01-08 21:48 UTC, Fribur commented
Exactly those errors (besides the mDNS issue) prompted me to begin looking into re-factoring HttpPowerMeter: see issue I opened prior to the re-ractoring. https://github.com/helgeerbe/OpenDTU-OnBattery/issues/579 

I came to realize this is only related to the frequency of querying the PowerMeter (I believe it is already to once per second limited in PowerLimiter class) and the configured timeout. When I set it to 2000ms it works in 99% of the cases. Maybe this can be reduced by setting different timeouts for "Connect" and "Response"? What are reasonable values? Currently it is implemented like this: 
```
httpClient.setConnectTimeout(timeout);
httpClient.setTimeout(timeout);
```

2024-01-16 11:56 UTC, merged