Minor VeDirect Improvements (parse additional values, ... )
helgeerbe/OpenDTU-OnBattery pull request #840
Opened 2024-04-03 20:18 UTC by SW-Niko

- VeDirect: add of text message values "IL", "AR" and "MON"
- VeDirect: discard BMV and Async MPPT History Data

2024-04-03 20:38 UTC, SW-Niko commented
Bei verboseLogging = off
Taucht im Logging bei mir nichts mehr auf.
Bei verboseLogging = on
Noch jede Menge. Mein Vorschlag .. Die "Sending Hex Command" und die "Unhandled Hex .. " auch noch entfernen.
[VE.Direct MPPT 22/21] Sending Hex Command: :7DBED0086, Free FIFO-Buffer: 118
[VE.Direct MPPT 22/21] Sending Hex Command: :7ECED0075, Free FIFO-Buffer: 118
[VE.Direct MPPT 22/21] Sending Hex Command: :727200007, Free FIFO-Buffer: 118
[VE.Direct MPPT 22/21] Unhandled Hex Async Response, addr: 0x0200 (Device Mode), value: 0x00000001, flags: 0x00
[VE.Direct MPPT 22/21] Unhandled Hex Async Response, addr: 0x0202 (Remote Control Used), value: 0x00000002, flags: 0x00
[VE.Direct MPPT 22/21] Unhandled Hex Async Response, addr: 0x0201 (Device State), value: 0x00000000, flags: 0x00
[VE.Direct MPPT 22/21] Hex Data: MPPT Temperature (0xEDDB): 32.70°C
[VE.Direct MPPT 22/21] Hex Data: Smart Battery Sense Temperature (0xEDEC): 23.75°C
[VE.Direct MPPT 22/21] Hex Data: Network Total DC Power (0x2027): 0.00W
[VE.Direct MPPT 22/21] Unhandled Hex Async Response, addr: 0xEDD5 (Charger Voltage), value: 0x00000A2E, flags: 0x00
[VE.Direct MPPT 22/21] Unhandled Hex Async Response, addr: 0xEDA9 (???), value: 0x00000078, flags: 0x00
[VE.Direct MPPT 22/21] Unhandled Hex Async Response, addr: 0x2002 (???), value: 0x0000FFFF, flags: 0x00

Und dann ist mir noch aufgefallen das diese Abfrage nicht mehr ganz richtig ist, weil in _lastByteMillis die Hex Bytes und die Text (Frame) Bytes vermischt werden. Das korrigiere ich auch noch.

	// there will never be a large gap between two bytes of the same frame.
	// if such a large gap is observed, reset the state machine so it tries
	// to decode a new frame once more data arrives.
	if (State::IDLE != _state && (millis() - _lastByteMillis) > 500) {

2024-04-04 06:36 UTC, schlimmchen commented
> Mein Vorschlag .. Die "Sending Hex Command" und die "Unhandled Hex .. " auch noch entfernen.

Das finde ich nicht so gut. Im Falle, dass man etwas debuggen muss, insb. wenn man anderen helfen möchte, muss man schon sehen, was rausgeht und reinkommt.

> weil in _lastByteMillis die Hex Bytes und die Text (Frame) Bytes vermischt werden.

Das verstehe ich nicht. Präsentiere gerne deinen Fix, dann verstehe ich vermutlich welches Problem du erkannt hast.

2024-04-04 06:47 UTC, schlimmchen requested changes

2024-04-04 06:47 UTC, schlimmchen commented on lib/VeDirectFrameHandler/VeDirectData.h
> +    float IL;                       // Load current in A (Available only for models with a load output.)
Ich war bisher nicht hinreichend motiviert, alle floats zu ersetzen in diesem struct, aber eigentlich wollte ich es tun. Vermutlich hast du die Diskussion verpasst: Lass uns bitte alle Werte, die als Integer übermittelt werden, auch als solche speichern. Es gibt keinen Grund, Präzision einzubüßen und rechenaufwändige floats zu verwenden, wenn wir stattdessen auch Integer speichern können. Langfristig sollten diese Bezeichner auch ersetzt werden. Dass ein Wert als "IL" markiert ist ein einem seriellen Protokoll, bei dem jedes Byte Zeit und Ressourcen verbraucht, macht Sinn. Aber es macht absolut keinen Sinn "IL" als Variablenname (Struct Member) zu verwenden. Da es sich um eine neue Variable handelt, kann auch gleich ein gescheiter Name festgelegt werden: `loadCurrentMilliAmps`. Bist du anderer Meinung?

2024-04-04 06:47 UTC, schlimmchen commented on lib/VeDirectFrameHandler/VeDirectMpptController.cpp
> +		_tmpFrame.IL = atoi(value.c_str()) / 100.0;
Multipliziere stattdessen mit 10, siehe Kommentar zur Variable "IL" im veMpptStruct.

2024-04-04 07:11 UTC, schlimmchen requested changes

2024-04-04 07:11 UTC, schlimmchen commented on lib/VeDirectFrameHandler/VeDirectFrameHandler.cpp
> +	return strlen(_tmpFrame.SER) > 0 && (millis() - _lastUpdate) < (10 * 1000);
Das ist leider keine Vereinfachung, sondern jetzt ein Problem, denn jetzt ist isDataValid() in den ersten zehn Sekunden nach dem Start (und dann zehn Sekunden nach jedem Überlauf alle vierzig-schießmichtod Tage) true. Das ist nicht gewollt.

2024-04-04 07:11 UTC, schlimmchen commented on lib/VeDirectFrameHandler/VeDirectFrameHandler.cpp
> +	if ((State::IDLE != _state) && (State::RECORD_HEX != _state) && ((millis() - _lastByteMillis) > 500)) {
Hm. Das bedeutet insbesondere, dass die State Machine nicht zurückgesetzt wird, wenn während des Dekodierens eines HEX Frames keine Daten mehr empfangen werden, bzw. wenn ein HEX Frame zu kurz ist, oder wenn das \n (newline) nicht angekommen ist (was ja absolut möglich ist). Warum denkst du, dass das sinnvoll ist?

2024-04-04 07:13 UTC, SW-Niko commented
> Das verstehe ich nicht. Präsentiere gerne deinen Fix, dann verstehe ich vermutlich welches Problem du erkannt hast.

Findest du in meinem letzten Commit.
Hintergrund:
Die state machine wird jetzt nur dann zurückgesetzt wenn zwischen 2 **text bytes** mehr als 500ms vergangen sind.
Das war bereits früher mit asynchronen Nachrichten vermischt. Durch die Implementierung der hex Nachrichten wird es immer unwahrscheinlicher das ein reset über den 500ms Check ausgelöst wird.

Und in der Funktion isDataValid() habe ich die Abfrage "_lastUpdate > 0" weil sie keinen Mehrwert bringt und ein check > 0 bei einem periodisch überlaufenden Zähler potentiell gefährlich ist mit ... ok...sehr geringem Risiko.

2024-04-04 07:21 UTC, SW-Niko commented on lib/VeDirectFrameHandler/VeDirectFrameHandler.cpp
> +	if ((State::IDLE != _state) && (State::RECORD_HEX != _state) && ((millis() - _lastByteMillis) > 500)) {
Ja da hast du recht. 👍 Eigentlich sollte immer bei Byte Lücken > 500ms zurückgesetzt werden.
Ich mach das wider auf original code und ändere nur den Kommentar. 
// there will never be a large gap between two bytes of the same frame.
	// if such a large gap is observed, reset the state machine so it tries
	// to decode a new frame once more data arrives.

zu
// there will never be a large gap between two bytes 
	// if such a large gap is observed, reset the state machine so it tries
	// to decode a new frame / hex messages once more data arrives.

2024-04-04 07:35 UTC, SW-Niko commented on lib/VeDirectFrameHandler/VeDirectData.h
> +    float IL;                       // Load current in A (Available only for models with a load output.)
> Lass uns bitte alle Werte, die als Integer übermittelt

Das kann ich machen. Dabei muss ich vermutlich viele Stellen im Code anfassen. Ich schau mir das mal an.



> gescheiter Name festgelegt werden

Hat Vor und Nachteile. Ich finde es praktisch wenn der Name mit der Victron Dokumentation zusammenstimmt. Vielleicht eine Combination IL -> loadCurrent_mA_IL ?

2024-04-04 07:58 UTC, SW-Niko commented on lib/VeDirectFrameHandler/VeDirectFrameHandler.cpp
> +	return strlen(_tmpFrame.SER) > 0 && (millis() - _lastUpdate) < (10 * 1000);
Wo habe ich da meinen Denkfehler ?
Nach dem Start liefert die Funktion false bis erstmals eine Seriennummer empfangen wurde. 
Zu diesem Zeitpunkt wird auch _lastUpdate gesetzt. 
Und ab dann liefert die Funktion true wenn innerhalb 10 Sekunden neue Werte ankommen.
Bei einem Überlauf passiert jetzt nichts weil die Überprüfung einer Zeitdauer mit millis() immer funktioniert.

Wenn ich millis() richtig verstanden habe dann kann es nur zu Problemen bei einem Überlauf kommen wenn Zeitpunkte herangezogen werden also Abfragen wie if(millis() > _lastupdate + 10) 
aber nicht bei Zeitdauern also if (millis() - _lastupdate > 10)

2024-04-04 08:40 UTC, schlimmchen commented on lib/VeDirectFrameHandler/VeDirectData.h
> +    float IL;                       // Load current in A (Available only for models with a load output.)
> Das kann ich machen. Dabei muss ich vermutlich viele Stellen im Code anfassen.

Das musst du nicht machen. Es ging mir drum, dass neue Werte dann einer neuen Konvention folgen. Aber falls du Bock drauf hast, gerne.

> loadCurrent_mA_IL

Hier stört mich das Mischen von CamelCase und Unterstrichen. Ich hätte im JK BMS auch gerne Unterstriche verwendet, aber um mich dem Stil des Projektes anzupassen, wurden die Einheiten dann "MilliAmps" statt "mA". Bin mir nicht sicher, ob der cpplinter das zulässt. Falls ja, fände ich "loadCurrent_IL_mA" akzeptabel Einheit am Schluss).

2024-04-04 08:57 UTC, schlimmchen commented on lib/VeDirectFrameHandler/VeDirectFrameHandler.cpp
> +	return strlen(_tmpFrame.SER) > 0 && (millis() - _lastUpdate) < (10 * 1000);
Beim Starten stimme ich dir zu, da rettet uns die Tatsache, dass die Seriennummer geprüft wird.

Wenn mal eine Seriennummer empfangen wurde, aber dann nicht mehr, nämlich für vierzig-schießmichtod Tage, dann gibt es einen Zeitraum von 10 Sekunden, in dem die Daten valide sind. Dieses Problem gabs aber auch schon vorher.

Du hast Recht, `_lastUpdate > 0` ist also redundant.

Es sei denn, wir setzen `_lastUpdate = 0` sobald es einmal ein Timeout gab.

```
template<typename T>
void VeDirectFrameHandler<T>::loop() {
    if ( (millis() - _lastUpdate) > (10 * 1000) ) {
        _lastUpdate = 0; // marks data as invalid
    }
    // ...
}

template<typename T>
bool VeDirectFrameHandler<T>::isDataValid() const {
    return _lastUpdate > 0 && (millis() - _lastUpdate) < (10 * 1000);
}
```

Dann verbleibt nur noch der Zufall, dass ein Frame dekodiert wurde als `millis()` Null war, sodass `_lastUpdate` korrekter weise Null wird. Das trifft man nur in einer Millisekunde alle vierzig-schießmichtod Tage, statt 10 Sekunden im gleichen Zeitraum.

2024-04-04 09:59 UTC, SW-Niko commented on lib/VeDirectFrameHandler/VeDirectFrameHandler.cpp
> +	return strlen(_tmpFrame.SER) > 0 && (millis() - _lastUpdate) < (10 * 1000);
Prima, ich sehe wir nähern uns an. 
Aber ich denke auch _lastUpdate = 0 können wir uns sparen, weil es kein Problem bei einem Rollover gibt wenn Zeitdauern verglichen werden.
An dieser Stelle können wir auch weiterhin Zeitpunkte vergleichen, das Risiko ist hier sehr sehr sehr klein.
Mir ist allerdings an mehreren Stellen im Code aufgefallen das immer wieder mal Zeitpunkte verglichen werden und ich mich schwer tue auch hier das Risiko abzuschätzen.
Darum bohre ich jetzt so intensiv nach. 
Vielleicht nimmst du dir mal ein paar Minuten und liest diesen Artikel:
[https://arduino.stackexchange.com/questions/12587/how-can-i-handle-the-millis-rollover/12588#12588](https://github.com/helgeerbe/OpenDTU-OnBattery/pull/url) 
Die können das besser erklären als ich. 😞

2024-04-04 10:18 UTC, SW-Niko commented on lib/VeDirectFrameHandler/VeDirectData.h
> +    float IL;                       // Load current in A (Available only for models with a load output.)
Ich stelle jetzt mal die neuen Werte um und wenn das passt gehe ich die alten Werte an. 
loadCurrent_IL_mA, alarmReason_AR und dcMonitorMode_MON

Mir fällt gerade auf das AR auch vom MPPT gesendet wird wenn ein Fehler vorliegt. Dan muss ich das Parsen von AR in den Framehändler verschieben.

2024-04-04 11:08 UTC, schlimmchen commented on lib/VeDirectFrameHandler/VeDirectFrameHandler.cpp
> +	return strlen(_tmpFrame.SER) > 0 && (millis() - _lastUpdate) < (10 * 1000);
> Aber ich denke auch _lastUpdate = 0 können wir uns sparen,

Warum?

> weil es kein Problem bei einem Rollover gibt wenn Zeitdauern verglichen werden.

Doch klar, das geht nur gut solange man eine Dauer kleiner als die Hälfte des Wertebereiches betrachtet.

2024-04-05 09:59 UTC, SW-Niko commented
Die veMpptStruct habe ich abgeändert. Namen und types angepasst.
Auf der Web App ist alles wie vorher (Werte und Nachkommastellen) Mqtt kann ich nicht testen!
Wenn es so passt dann kann ich die veStruct auch noch anpassen.

Schau dir doch mal diese Umwandlung an.
_tmpFrame.offReason_OR = strtol(value.c_str(), nullptr, 0); // SW-Nico basis 16 ?
Wenn ich die Victron Doku anschaue, dann werden hex Stings übertragen und damit von uns falsch gewandelt.
11:57:03.168 > [VE.Direct MPPT 22/21] Text Data 'OR' = '0X00000000'

2024-04-05 11:05 UTC, schlimmchen commented
> Die veMpptStruct habe ich abgeändert. Namen und types angepasst.

Nice :muscle: 

> Schau dir doch mal diese Umwandlung an.

Das Feld sieht so aus: `0d 0a 4f 52 09 30 78 30 30 30 30 30 30 30 30 0d 0a` also `\r\nOR\t0x00000000` in ASCII. Das passt, weil `strtol()` mit 0 als basis "auto-basis" ist. Da der string mit "0x" beginnt, wird die Zahl in der Tat als Hexadezimalzahl interpretiert. Also alles gut.

2024-04-05 18:32 UTC, schlimmchen commented on lib/VeDirectFrameHandler/VeDirectFrameHandler.cpp
> +	return strlen(_tmpFrame.SER) > 0 && (millis() - _lastUpdate) < (10 * 1000);
Ich hab den stackexchange Artikel überflogen, und hab erstmal nichts neues gefunden. Ich glaube du weißt, dass dieser Vergleich nach 49.7 Tagen schief geht, also: MPPT ist neuerdings offline, dann gibt es ab diesem Zeitpunkt in 49.7 Tagen einen Zeitraum von 10 Sekunden, in dem `(millis() - _lastUpdate) < (10 * 1000)` wahr ist (weil die Seriennummer nicht leer ist). Von mir aus ignorieren wir das. Es ist echt gut genug so :wink:

2024-04-05 18:36 UTC, schlimmchen commented
Du arbeitest noch weiter an diesem Thema, oder? Dann warte ich noch mit testen und mergen?

2024-04-06 05:20 UTC, SW-Niko commented
Ja, Ich bin fast soweit. Die veShuntStruct würde ich mal so lassen, weil ich Änderungen nicht testen kann.

2024-04-06 07:17 UTC, schlimmchen commented
Ich dachte schon an 1. und habs auch angefangen als pseudo-code vorzuschlagen und dann wieder verworfen. `isDataValid()` sollte jeder Kunde benutzen, der VE.Direct Daten verarbeitet. Und da könnten wir folgendes tun:

```
template<typename T>
bool VeDirectFrameHandler<T>::isDataValid() const
{
	// VE.Direct text frame data is valid if we receive a device serialnumber and
	// the data is not older as 10 seconds
	bool valid = strlen(_tmpFrame.serialNr_SER) > 0 && (millis() - _lastUpdate) < (10 * 1000);

	// if the frame is invalid because it timed out, we reset it, which resets the serial number
	// in particular, preventing isDataValid() from ever becoming true when millis() - _lastUpdate rolls over.
	if (!valid) { _tmpFrame = { }; }
	return valid;
}
```

Allerdings sind dann die Daten echt weg, statt dass die zuletzt eingegangenen vorgehalten werden. Dabei bin ich mir unsicher, ob das zu Problemen irgendwo führt oder das Verhalten ändert, sodass wir für Leute irgendwas kaputt machen.

Daher dachte ich, es ist akzeptabel, dass dieser Glitch passieren kann nach 50 Tagen. Ich würd's daher einfach ignorieren. Du?

2024-04-06 07:44 UTC, SW-Niko commented
Stimme dir zu. Solange wir keinen wirklichen Vorteil mit einer Codeänderung sehen sollten wir es so lassen und den Glitch akzeptieren. Ich ändere das gleich noch ab und setze den PR auf review.

2024-04-06 08:11 UTC, SW-Niko commented
Ok, von meiner Seite kannst du die Änderungen mergen.
Kannst du die Mqtt Änderungen testen? Ich habe kein Mqtt bei mir am laufen und wir sollten sichergehen, das die Einheiten (V, A, W usw) die an Mqtt gesendet werden, nicht verändert wurden.

2024-04-06 18:30 UTC, schlimmchen requested changes
Es sind nur noch Kleinigkeiten übrig. Falls du die nicht schaffst bis Sonntagmittag und dich auch nicht wehrst, dann übernehme ich das gerne.

2024-04-06 18:30 UTC, schlimmchen commented on lib/VeDirectFrameHandler/VeDirectData.h
> +    uint32_t pannelCurrent_mA;          // panel current in mA (calculated)
*panel

2024-04-06 18:30 UTC, schlimmchen commented on lib/VeDirectFrameHandler/VeDirectData.h
> +    uint32_t yieldTodayRes_H19_Wh;      // yield total resetable Wh
*yieldTotal_H19_Wh

2024-04-06 18:30 UTC, schlimmchen commented on lib/VeDirectFrameHandler/VeDirectFrameHandler.cpp
> +	return strlen(_tmpFrame.serialNr_SER) > 0 && _lastUpdate > 0 && (millis() - _lastUpdate) < (10 * 1000);
Why did you re-introduce `_lastUpdate > 0`?

2024-04-06 18:30 UTC, schlimmchen commented on lib/VeDirectFrameHandler/VeDirectFrameHandler.cpp
> +	// Actual we accept a short glitch during rollover if _lastupdate = 0 and serialNr_SER != 0
// we accept a glitch where the data is valid for ten seconds when serialNr_SER != "" and (millis() - _lastUpdate) overflows

_lastUpdate muss nicht Null sein, damit das passiert. millis() holt so lange auf, bis es _lastUpdate überholt, und dann ist für zehn Sekunden lang isDataValid() wahr.

2024-04-06 18:30 UTC, schlimmchen commented on lib/VeDirectFrameHandler/VeDirectMpptController.cpp
> +		_tmpFrame.offReason_OR = strtol(value.c_str(), nullptr, 0); // SW-Nico basis 16 ?
Remove comment.

2024-04-06 18:30 UTC, schlimmchen commented on src/MqttHandleVedirect.cpp
> +    PUBLISH(yieldTodayRes_H19_Wh,    "H19",  static_cast<float>(currentData.yieldTodayRes_H19_Wh / 1000.0));
Warum sind hier static_cast<float> nötig, wenn sie bei der Spannung und dem Strom etc. nicht nötig sind? Sind sie sicherlich nicht. Wenn sie es sind, dann um die Variable herum um dann durch 1000 zu teilen.

2024-04-06 18:32 UTC, schlimmchen commented
> Kannst du die Mqtt Änderungen testen?

Ja, mach ich.

> Die veShuntStruct würde ich mal so lassen, weil ich Änderungen nicht testen kann.

Ich bin da mutiger und würde das übernehmen, auch wenn ich keinen SmartShunt habe. Die sind leider recht teuer, zu teuer um für Tests anzuschaffen.

2024-04-06 19:28 UTC, PhilJaro commented
> Ich bin da mutiger und würde das übernehmen, auch wenn ich keinen SmartShunt habe. Die sind leider recht teuer, zu teuer um für Tests anzuschaffen.

Da ich einen SmurtShunt im Einsatz habe, habe ich mir den PR mal aufgespielt. Es scheint da etwas mit dem Current nicht zu passen. Per MQTT sowie WebApp werden viel zu hohe werte angezeigt.
<img width="859" alt="image" src="https://github.com/helgeerbe/OpenDTU-OnBattery/assets/122352327/994a1f1a-9981-4f09-aa32-0852f585ea77">

Des weiteren Plopt beim SmartSolar in der WebApp die Temperatur immer auf und verschwindet dann wieder und so weiter...

2024-04-06 19:36 UTC, PhilJaro commented
Gerade nochmal etwas beobachtet, current verändert sich auch nicht, bzw. kann das auch kein einfacher Umrechnungsfehler sein.

2024-04-07 05:56 UTC, SW-Niko commented on lib/VeDirectFrameHandler/VeDirectData.h
> +    uint32_t pannelCurrent_mA;          // panel current in mA (calculated)
Erledigt

2024-04-07 06:01 UTC, SW-Niko commented on lib/VeDirectFrameHandler/VeDirectData.h
> +    uint32_t yieldTodayRes_H19_Wh;      // yield total resetable Wh
Erledigt

2024-04-07 06:02 UTC, SW-Niko commented on lib/VeDirectFrameHandler/VeDirectMpptController.cpp
> +		_tmpFrame.offReason_OR = strtol(value.c_str(), nullptr, 0); // SW-Nico basis 16 ?
Erledigt

2024-04-07 06:09 UTC, SW-Niko commented on src/MqttHandleVedirect.cpp
> +    PUBLISH(yieldTodayRes_H19_Wh,    "H19",  static_cast<float>(currentData.yieldTodayRes_H19_Wh / 1000.0));
static_cast entfernt

2024-04-07 06:12 UTC, SW-Niko commented on lib/VeDirectFrameHandler/VeDirectFrameHandler.cpp
> +	// Actual we accept a short glitch during rollover if _lastupdate = 0 and serialNr_SER != 0
Ok

2024-04-07 06:16 UTC, SW-Niko commented on lib/VeDirectFrameHandler/VeDirectFrameHandler.cpp
> +	return strlen(_tmpFrame.serialNr_SER) > 0 && _lastUpdate > 0 && (millis() - _lastUpdate) < (10 * 1000);
Richtig. Das ist Blödsinn und addiert nur einen weiteren Glitch bei 0

2024-04-07 07:48 UTC, PhilJaro commented
Seit heute morgen passt der Wert wieder, ohne das ich irgendetwas verändert habe... 
<img width="558" alt="image" src="https://github.com/helgeerbe/OpenDTU-OnBattery/assets/122352327/ea61df43-28a9-4d4f-a2a4-33d15a217dd0">

2024-04-07 09:14 UTC, SW-Niko commented
Hallo @PhilJaro ,
wenn du das Problem mit der MPPT Temperature noch hast dann bitte mal das VE.Direkt logging einschalten und prüfen ob diese Meldung regelmäßig kommt.
11:07:38.538 > [VE.Direct MPPT 22/21] Hex Data: MPPT Temperature (0xEDDB): 45.40°C.

Die Werte werden im 1 Sekunden Rhythmus abgefragt.
Ich kann bei meinem MPPT 75/15 kein Problem feststellen. Die Werte kommen sauber und regelmäßig an.

2024-04-07 09:53 UTC, PhilJaro commented
Bzgl. des current Problems ist mir nun noch folgendes aufgefallen, sobald die Werte Negativ werden, sprich die Batterie entladen wird stehen dort wieder die 4… Millionen, deshalb ging es bei mir heute morgen wieder, da ab dort wieder mehr geladen als entladen wurde. Sieht also so aus als könne die Änderung nicht mit negativen Werten umgehen. 

@SW-Niko 
Habe gerade nochmal etwas zugeschaut und konnte das gestrige Verhalten nicht mehr beobachten, auch im Verbose-Log sah das soweit gut aus. Allerdings sieht man einige Fehler bzgl hex Async response.

Hier mal ein 2 Sekunden Ausschnitt:

[VE.Direct MPPT 14/27] serial input (363 Bytes):
11:50:34.112 > [VE.Direct MPPT 14/27] 3a 37 44 42 45 44 30 30 39 45 31 36 44 32 0a 3a
11:50:34.133 > [VE.Direct MPPT 14/27] 37 45 43 45 44 30 30 46 46 46 46 37 37 0a 3a 37
11:50:34.165 > [VE.Direct MPPT 14/27] 32 37 32 30 30 30 35 34 35 30 30 31 30 30 36 32
11:50:34.214 > [VE.Direct MPPT 14/27] 0a 3a 41 44 37 45 44 30 30 41 30 30 30 45 37 0a
11:50:34.222 > [VE.Direct MPPT 14/27] 3a 41 42 43 45 44 30 30 33 35 35 30 30 31 30 30
11:50:34.229 > [VE.Direct MPPT 14/27] 31 43 0a 3a 41 44 35 45 44 30 30 38 44 31 34 45
11:50:34.245 > [VE.Direct MPPT 14/27] 38 0a 3a 41 42 42 45 44 30 30 32 35 31 38 36 36
11:50:34.254 > [VE.Direct MPPT 14/27] 0a 3a 41 30 32 32 30 30 30 46 46 46 46 32 42 0a
11:50:34.299 > [VE.Direct MPPT 14/27] 3a 41 30 41 32 30 30 30 46 46 46 46 46 46 37 46
11:50:34.380 > [VE.Direct MPPT 14/27] 41 35 0a 3a 41 31 33 32 30 30 30 46 46 46 46 46
11:50:34.474 > [VE.Direct MPPT 14/27] 46 37 46 39 43 0a 0d 0a 50 49 44 09 30 78 41 30
11:50:34.526 > [VE.Direct MPPT 14/27] 36 30 0d 0a 46 57 09 31 36 33 0d 0a 53 45 52 23
11:50:34.587 > [VE.Direct MPPT 14/27] 09 48 51 32 32 32 38 56 59 32 51 44 0d 0a 56 09
11:50:34.697 > [VE.Direct MPPT 14/27] 35 32 35 39 30 0d 0a 49 09 31 36 30 32 30 0d 0a
11:50:34.750 > [VE.Direct MPPT 14/27] 56 50 56 09 36 31 37 37 30 0d 0a 50 50 56 09 38
11:50:34.779 > [VE.Direct MPPT 14/27] 36 31 0d 0a 43 53 09 33 0d 0a 4d 50 50 54 09 32
11:50:34.795 > [VE.Direct MPPT 14/27] 0d 0a 4f 52 09 30 78 30 30 30 30 30 30 30 30 0d
11:50:34.802 > [VE.Direct MPPT 14/27] 0a 45 52 52 09 30 0d 0a 4c 4f 41 44 09 4f 46 46
11:50:34.809 > [VE.Direct MPPT 14/27] 0d 0a 49 4c 09 30 0d 0a 48 31 39 09 31 32 31 39
11:50:34.814 > [VE.Direct MPPT 14/27] 38 0d 0a 48 32 30 09 32 32 30 0d 0a 48 32 31 09
11:50:34.832 > [VE.Direct MPPT 14/27] 39 34 37 0d 0a 48 32 32 09 36 35 37 0d 0a 48 32
11:50:34.839 > [VE.Direct MPPT 14/27] 33 09 31 30 31 37 0d 0a 48 53 44 53 09 33 35 0d
11:50:34.843 > [VE.Direct MPPT 14/27] 0a 43 68 65 63 6b 73 75 6d 09 1d
11:50:34.849 > [VE.Direct MPPT 14/27] Text Data 'PID' = '0XA060'
11:50:34.859 > [VE.Direct MPPT 14/27] Text Data 'FW' = '163'
11:50:34.870 > [VE.Direct MPPT 14/27] Text Data 'SER' = 'HQ2228VY2QD'
11:50:34.875 > [VE.Direct MPPT 14/27] Text Data 'V' = '52590'
11:50:34.881 > [VE.Direct MPPT 14/27] Text Data 'I' = '16020'
11:50:34.889 > [VE.Direct MPPT 14/27] Text Data 'VPV' = '61770'
11:50:34.896 > [VE.Direct MPPT 14/27] Text Data 'PPV' = '861'
11:50:34.903 > [VE.Direct MPPT 14/27] Text Data 'CS' = '3'
11:50:34.914 > [VE.Direct MPPT 14/27] Text Data 'MPPT' = '2'
11:50:34.920 > [VE.Direct MPPT 14/27] Text Data 'OR' = '0X00000000'
11:50:34.926 > [VE.Direct MPPT 14/27] Text Data 'ERR' = '0'
11:50:34.934 > [VE.Direct MPPT 14/27] Text Data 'LOAD' = 'OFF'
11:50:34.939 > [VE.Direct MPPT 14/27] Text Data 'IL' = '0'
11:50:34.947 > [VE.Direct MPPT 14/27] Text Data 'H19' = '12198'
11:50:34.954 > [VE.Direct MPPT 14/27] Text Data 'H20' = '220'
11:50:34.959 > [VE.Direct MPPT 14/27] Text Data 'H21' = '947'
11:50:34.967 > [VE.Direct MPPT 14/27] Text Data 'H22' = '657'
11:50:35.302 > [VE.Direct MPPT 14/27] Text Data 'H23' = '1017'
11:50:35.303 > [VE.Direct MPPT 14/27] Text Data 'HSDS' = '35'
11:50:35.303 > [VE.Direct MPPT 14/27] Sending Hex Command: :7DBED0086, Free FIFO-Buffer: 118
11:50:35.304 > [VE.Direct MPPT 14/27] Sending Hex Command: :7ECED0075, Free FIFO-Buffer: 118
11:50:35.318 > [VE.Direct MPPT 14/27] Sending Hex Command: :727200007, Free FIFO-Buffer: 118
11:50:35.329 > [VE.Direct MPPT 14/27] Hex Data: MPPT Temperature (0xEDDB): 57.90°C
11:50:35.341 > [VE.Direct MPPT 14/27] Hex Data: Smart Battery Sense Temperature is not available
11:50:35.348 > [VE.Direct MPPT 14/27] Hex Data: Network Total DC Power (0x2027): 861.00W
11:50:35.357 > Middle missing
11:50:35.372 > Request retransmit: 3
11:50:35.375 > Success
11:50:35.380 > [VE.Direct MPPT 14/27] Unhandled Hex Async Response, addr: 0xEDD7 (???), value: 0x0000009F, flags: 0x00
11:50:35.388 > [VE.Direct MPPT 14/27] Unhandled Hex Async Response, addr: 0xEDBC (???), value: 0x00015015, flags: 0x00
11:50:35.393 > [VE.Direct MPPT 14/27] Unhandled Hex Async Response, addr: 0xEDD5 (Charger Voltage), value: 0x00001489, flags: 0x00
11:50:35.400 > [VE.Direct MPPT 14/27] Unhandled Hex Async Response, addr: 0xEDBB (Panel Voltage), value: 0x00001841, flags: 0x00
11:50:35.408 > [VE.Direct MPPT 14/27] Hex Data: Network Total DC Power (0x2027): 860.00W
11:50:35.414 > [VE.Direct MPPT 14/27] Unhandled Hex Async Response, addr: 0x200A (???), value: 0x7FFFFFFF, flags: 0x00
11:50:35.427 > [VE.Direct MPPT 14/27] Unhandled Hex Async Response, addr: 0x2013 (???), value: 0x7FFFFFFF, flags: 0x00
11:50:35.435 > [VE.Direct MPPT 14/27] Unhandled Hex Async Response, addr: 0x0200 (Device Mode), value: 0x00000001, flags: 0x00
11:50:35.441 > [VE.Direct MPPT 14/27] Unhandled Hex Async Response, addr: 0x0202 (Remote Control Used), value: 0x00000002, flags: 0x00
11:50:35.450 > [VE.Direct MPPT 14/27] Unhandled Hex Async Response, addr: 0x0201 (Device State), value: 0x00000003, flags: 0x00
11:50:35.458 > [VE.Direct MPPT 14/27] Unhandled Hex Async Response, addr: 0xEDD7 (???), value: 0x000000A0, flags: 0x00
11:50:35.462 > [VE.Direct MPPT 14/27] serial input (427 Bytes):
11:50:35.470 > [VE.Direct MPPT 14/27] 3a 37 44 42 45 44 30 30 39 45 31 36 44 32 0a 3a
11:50:35.480 > [VE.Direct MPPT 14/27] 37 45 43 45 44 30 30 46 46 46 46 37 37 0a 3a 37
11:50:35.491 > [VE.Direct MPPT 14/27] 32 37 32 30 30 30 35 34 35 30 30 31 30 30 36 32
11:50:35.503 > [VE.Direct MPPT 14/27] 0a 3a 41 44 37 45 44 30 30 39 46 30 30 45 38 0a
11:50:35.507 > [VE.Direct MPPT 14/27] 3a 41 42 43 45 44 30 30 31 35 35 30 30 31 30 30
11:50:35.523 > [VE.Direct MPPT 14/27] 33 43 0a 3a 41 44 35 45 44 30 30 38 39 31 34 45
11:50:35.529 > [VE.Direct MPPT 14/27] 43 0a 3a 41 42 42 45 44 30 30 34 31 31 38 34 41
11:50:35.539 > [VE.Direct MPPT 14/27] 0a 3a 41 32 37 32 30 30 30 46 30 34 46 30 31 30
11:50:35.544 > [VE.Direct MPPT 14/27] 30 43 34 0a 3a 41 30 41 32 30 30 30 46 46 46 46
11:50:35.552 > [VE.Direct MPPT 14/27] 46 46 37 46 41 35 0a 3a 41 31 33 32 30 30 30 46
11:50:35.560 > [VE.Direct MPPT 14/27] 46 46 46 46 46 37 46 39 43 0a 3a 41 30 30 30 32
11:50:35.568 > [VE.Direct MPPT 14/27] 30 30 30 31 34 38 0a 3a 41 30 32 30 32 30 30 30
11:50:35.576 > [VE.Direct MPPT 14/27] 32 30 30 30 30 30 30 34 35 0a 3a 41 30 31 30 32
11:50:35.581 > [VE.Direct MPPT 14/27] 30 30 30 33 34 35 0a 3a 41 44 37 45 44 30 30 41
11:50:35.588 > [VE.Direct MPPT 14/27] 30 30 30 45 37 0a 0d 0a 50 49 44 09 30 78 41 30
11:50:35.611 > [VE.Direct MPPT 14/27] 36 30 0d 0a 46 57 09 31 36 33 0d 0a 53 45 52 23
11:50:35.634 > [VE.Direct MPPT 14/27] 09 48 51 32 32 32 38 56 59 32 51 44 0d 0a 56 09
11:50:35.643 > [VE.Direct MPPT 14/27] 35 32 35 35 30 0d 0a 49 09 31 36 30 32 30 0d 0a
11:50:35.654 > [VE.Direct MPPT 14/27] 56 50 56 09 36 32 30 34 30 0d 0a 50 50 56 09 38
11:50:35.665 > [VE.Direct MPPT 14/27] 35 39 0d 0a 43 53 09 33 0d 0a 4d 50 50 54 09 32
11:50:35.680 > [VE.Direct MPPT 14/27] 0d 0a 4f 52 09 30 78 30 30 30 30 30 30 30 30 0d
11:50:35.688 > [VE.Direct MPPT 14/27] 0a 45 52 52 09 30 0d 0a 4c 4f 41 44 09 4f 46 46
11:50:35.699 > [VE.Direct MPPT 14/27] 0d 0a 49 4c 09 30 0d 0a 48 31 39 09 31 32 31 39
11:50:35.706 > [VE.Direct MPPT 14/27] 38 0d 0a 48 32 30 09 32 32 30 0d 0a 48 32 31 09
11:50:35.713 > [VE.Direct MPPT 14/27] 39 34 37 0d 0a 48 32 32 09 36 35 37 0d 0a 48 32
11:50:35.723 > [VE. [...]

2024-04-07 11:12 UTC, SW-Niko commented
Hallo @PhilJaro,
Guter Hinweis. Die Strom I beim Shunt kann auch negativ werden. Beim MPPT nicht.
Kannst du mir auch ein Log vom Shunt machen und posten?

2024-04-07 11:48 UTC, SW-Niko commented
Hallo @PhilJaro,
ich denke ich habe den Fehler mit den Stromwerten gefixt. Beim Shunt und auch beim MPPT kann man negative Werte haben. Beim MPPT muss man nur über den Lastausgang mehr Leistung entnehmen als über die Solar Panel geliefert werden.
Ich schau mir die Temperaturwerte nochmal an.

PS:   Die "Unhandled Hex Async Response" sind ganz normal. Die Victron Geräte tauschen jede Menge Daten untereinander aus und die bekommen wir nun auch mit.  Wir werten sie nur nicht aus.

2024-04-07 12:17 UTC, PhilJaro commented
@SW-Niko Sehr gut, jetzt werden die Negativen Werte richtig angezeigt, somit sollte alles passen.

2024-04-07 13:46 UTC, schlimmchen commented
@PhilJaro Ausdrücklich vielen Dank für deine frühe Hilfe beim Testen! :muscle: 

@SW-Niko Danke für deinen Einsatz. `yieldToday_H19_Wh` ist noch falsch, es ist der Gesamtertrag, also `yieldTotal_H19_Wh`, das passe ich an. Dann squashe ich deine Commits und merge deine Arbeit.

2024-04-07 13:46 UTC, schlimmchen approved these changes

2024-04-07 14:36 UTC, SW-Niko commented
Danke @schlimmchen und @PhilJaro,
für die Unterstützung. 
Ich bin noch etwas besorgt wegen der On/Off Anzeige den Temperaturwerten. Das kann eigentlich nur passieren wenn mal 10 Sekunden lang keine Temperaturwerte ankommen. 
Hmmm...   Nur so eine Idee ....  Vielleicht kommst es bei deinem System wie bei mir zu einem Puffer Überlauf und Checksum Fehler. 
@PhilJaro Bitte bei mir melden wenn die Temperaturwerte wieder springen.
@schlimmchen  Ich könnte auch noch einen einfachen Fehlerzähler für den Überlauf / Checksum einbauen der beim Verbose Logging mit ausgegeben wird? Denke das wäre bei einer Fehleranalyse ganz nützlich.

2024-04-07 14:44 UTC, schlimmchen commented
> Ich könnte auch noch einen einfachen Fehlerzähler für den Überlauf / Checksum einbauen der beim Verbose Logging mit ausgegeben wird? Denke das wäre bei einer Fehleranalyse ganz nützlich.

Ja, mach das gerne, genau diesen Gedanken hatte ich auch schon.
* Sowohl erfolgreiche dekodierte Pakete zählen, als auch Fehler zählen (Checksummenfehler, Timeout (gibts noch mehr?))
* Außerdem gesendete Nachrichten zählen und **die passenden** HEX Antworten zählen.

Beides dann absolut und relativ ausgeben.

@PhilJaro Da fällt mir noch was ein in diesem Zusammenhang, das ich dich fragen wollte: Wie hast du denn den Victron angeschlossen an den ESP32? Direkt? Mit Level-Shifter? Mit ADUM1201? Es ist nämlich so, dass das direkte Anschließen beim Senden definitiv zu mehr oder zumindest mit höherer Wahrschenlichkeit zu Problemem führt, als beim Empfangen. Denn der ESP32 kommt ja nur auf 3V3 am TX Pin, und das muss der Victron nicht notwendiger Weise bzw. nicht zuverlässig als High erkennen, weil er mit 5V arbeitet.

2024-04-07 14:44 UTC, schlimmchen commented
> Ja, mach das gerne

Neuer Pull-Request, bitte.

2024-04-07 14:58 UTC, schlimmchen commented
![image](https://github.com/helgeerbe/OpenDTU-OnBattery/assets/3578416/b758cc95-41c9-44d8-95e8-1fa27b2cc57a)

Wie erwartet, alles dufte.

2024-04-07 15:02 UTC, schlimmchen commented
Rebased onto helgeerbe/development and squashed commits.

2024-04-07 15:13 UTC, merged

2024-04-08 15:28 UTC, SW-Niko commented
Hallo @PhilJaro ,
ich benutze auch die ADUM1201. Die VE.Direkt Verbindung bei mir ist sehr robust. 
Das Problem mit Überlauf und Checksum Fehler taucht bei mir erst auf wenn eine andere Funktion die DTU ausbremst.
Bei mir ist es das Powermeter. Siehe #752 und #760.