Feature: Publish Huawei AC charger mode via MQTT
helgeerbe/OpenDTU-OnBattery pull request #876
Opened 2024-04-15 06:36 UTC by eu-gh

Since we can set this parameter using MQTT, we should also be able to read its current value

2024-04-15 06:38 UTC, eu-gh commented
Did the files of this project change to CRLF by default? I only added like 3 lines, yet the diff looks horrible.

2024-04-15 09:39 UTC, eu-gh commented
I'm on Linux. Thanks, that did the trick!

Also I saw that you merged/reworked the sensible stuff from my old PR, big thank you for that. I was rather short on time the last couple of months.

2024-04-15 20:59 UTC, schlimmchen requested changes
Please address the second comment, where the getMode() can be implemented in the header (as its implementation is trivial) and add the const qualifier.

2024-04-15 20:59 UTC, schlimmchen commented on include/Huawei_can.h
> +    uint8_t getMode();
Implement here (in header) and use `const` qualifier.

2024-04-15 20:59 UTC, schlimmchen commented on include/Huawei_can.h
> -    uint32_t _nextRequestMillis = 0;              // When to send next data request to PSU
I do appreciate whitespace cleanups, however it is much nicer if they are part of a separate commit. Ideally, such a commit would be empty when using `git show --ignore-all-space`. That way, actual code changes are separated from non-functional changes, i.e., whitespace cleanups. Something to consider next time :wink:

2024-04-15 21:00 UTC, schlimmchen commented
> Also I saw that you merged/reworked the sensible stuff from my old PR, big thank you for that. I was rather short on time the last couple of months.

Thanks for your appreciation!

2024-04-19 13:11 UTC, eu-gh commented on include/Huawei_can.h
> +    uint8_t getMode();
> Implement here (in header) and use `const` qualifier.

Done 👍 While I'm at it, shall I also transform the getAutoPowerStatus() method in the same fashion?

2024-04-20 05:59 UTC, schlimmchen commented on include/Huawei_can.h
> +    uint8_t getMode();
Yes, thanks. Are there more trivial getters?

2024-04-20 06:02 UTC, schlimmchen commented on include/Huawei_can.h
> -    uint32_t _nextRequestMillis = 0;              // When to send next data request to PSU
This might be unintended. unix2dos should not do that, I never experienced that. However, you are right, some cleanups, including the removal of trailing whitespace is desirable. And new trailing whitespace should be catched by the linter.

2024-04-30 05:05 UTC, eu-gh commented on include/Huawei_can.h
> +    uint8_t getMode();
getLastUpdate() and getAutoPowerStatus() -> also transformed now. I'm unsure about the generic get() for RectifierParameters_t *; as I don't really recognize that syntax and my editor complains about a type mismatch if I try to move that to the header file.

2024-04-30 05:11 UTC, eu-gh commented on include/Huawei_can.h
> -    uint32_t _nextRequestMillis = 0;              // When to send next data request to PSU
Well, I literally typed unix2dos [./filename] and did not change anything else, except for my additions :smile: However, on my last pull request, none of this was necessary, so I am kind of confused why this is necessary now in the first place.

2024-05-02 19:12 UTC, schlimmchen approved these changes
Let's accept the whitespace changes, as they are progress in the right direction. Other than that, the changes look good (cannot test myself, but the changes seems to be alright).

2024-05-02 19:19 UTC, merged