add new DPL feature 'overscaling' to allow to compensate for shading
helgeerbe/OpenDTU-OnBattery pull request #956
Opened 2024-05-04 23:18 UTC by AndreasBoehm

2024-05-10 11:10 UTC, schlimmchen requested changes
Quite clean. Thanks for printing an informative message in case this new overscaling method does change the limit. I did not check the algorithm itself, since I don't care. Others will let us know if this works as expected or not.

2024-05-10 11:10 UTC, schlimmchen commented on webapp/src/views/PowerLimiterAdminView.vue
> +        },
This has to be checked by the firmware as well, i.e., even if "allow overscaling to compensate shading" is enabled (I can name two ways how it could happen), this type of overscaling should really only happen if the "is solar powered" switch is enabled as well.

2024-05-10 11:10 UTC, schlimmchen commented on webapp/src/locales/de.json
> +        "UseOverscalingToCompensateShading": "Wechselrichter-Limit im Zweifel Überskalieren, um Verschattung eines oder mehrerer Eingänge auszugleichen",
Well, this is way to long. Please find a reasonably short label (feature name) and use a tooltip (hint) to explain a little more. Then, please take some more time to explain the feature in detail in the wiki.

2024-05-10 11:10 UTC, schlimmchen commented on src/PowerLimiter.cpp
> +    if(allowOverscaling) {
Only if "allowOverscaling" *and* "inverter is solar powered". See my other comment at the "canUserOverscaling()" Javascript function.

2024-05-10 11:20 UTC, schlimmchen commented
@AndreasBoehm I allowed myself to rebase this onto the current development branch before asking users to review your work.

2024-05-10 11:53 UTC, greymda commented
i don't have access any more to partially shaded setup :(

2024-05-10 14:45 UTC, spcqike commented
Kann es sein dass es ein Problem mit HMS wechselrichter und neuer Firmware gab? Oder liegt es am PR? Ich bekomme seit dem Update keine Verbindung mehr zum HMS.

2024-05-10 15:04 UTC, spcqike commented
Kein peoxy. Direkt die IP der openDTU. Er empfängt gar nichts vom wechselrichter 

Naja. Da steht nicht viel. 

```
All missing
17:03:43.240 > Nothing received, resend whole request
17:03:43.738 > Websocket: [/livedata][6] disconnect
17:03:44.048 > All missing
17:03:44.058 > Nothing received, resend whole request
17:03:44.864 > All missing
17:03:44.907 > Nothing received, resend whole request
17:03:45.566 > All missing
17:03:45.576 > Nothing received, resend count exeeded
17:03:45.888 > All missing
17:03:45.896 > Nothing received, resend whole request
17:03:46.195 > All missing
17:03:46.240 > Nothing received, resend whole request
17:03:46.502 > All missing
17:03:46.544 > Nothing received, resend whole request
17:03:46.714 > All missing
17:03:46.748 > Nothing received, resend whole request
17:03:46.912 > All missing
17:03:46.951 > Nothing received, resend count exeeded
17:03:46.958 > Fetch inverter: 116492305207
17:03:46.965 > Request SystemConfigPara
17:03:46.972 > All missing
17:03:46.980 > Nothing received, resend whole request
17:03:46.988 > All missing
17:03:46.997 > Nothing received, resend whole request
17:03:47.033 > All missing
17:03:47.041 > Nothing received, resend whole request
17:03:47.085 > All missing
17:03:47.093 > Nothing received, resend whole request
17:03:47.101 > All missing
17:03:47.109 > Nothing received, resend count exeeded
17:03:47.707 > All missing
17:03:47.717 > Nothing received, resend whole request
```

2024-05-10 15:06 UTC, schlimmchen commented
Begreif ich nicht. Hat sich an den Einstellungen des CMT etwas verändert? Ich hab ja ein HMT und keine Probleme...

2024-05-10 15:24 UTC, spcqike commented
Nein. Daran hat sich nichts geändert. 

Ich weiß allerdings nicht, wie lange ich kein Update gemacht habe. Wenn irgendwas die Kommunikation zerschossen hat, könnte das auch schon länger her sein. Wobei es dann wohl mehr issues geben würde. Und das letzte war ja wegen dem Proxy, oder?

2024-05-10 15:53 UTC, spcqike commented
Ich weiß nicht hat genau warum, aber es scheint an den DTU Einstellungen zu liegen. 

Ich habe in der Vergangenheit, da ich Signal Probleme hatte, die Frequenz und die sendeleistung leicht erhöht. 

Damit der DTU den wechselrichter nach einem Update wieder findet oder anspricht, reicht es, in den DtU Einstellungen bspw verbose logging zu aktivieren und zu speichern. Den Rest kann ich so lassen wie es ist. Logging kann danach auch wieder aus gemacht werden. Hauptsache das speichern wird einmal ausgeführt. 

Das konnte ich jetzt sowohl mit der Firmware aus dem PR als auch mit dem latest release und einem Release aus dem Februar reproduzieren. 

So, es läuft also. Und irgendwie lag es (halb?) an mir. Aber dennoch komisch. Leider ist jetzt die Sonne weg um die Anpassung zu testen :)

2024-05-10 17:09 UTC, schlimmchen commented
> Und auch ein reiner Neustart der DTU genüg für das Problem. Scheinbar.

Sicher?

Es gab da jedenfalls Probleme mit den Einstellungen. Die hatten mit der Frequenzauswahl zu tun. Da musste man dann den Schieber einmal bewegen und speichern, sodass ein gültiger Wert abgespeichert wurde.

2024-05-10 17:44 UTC, spcqike commented
> Sicher?

grad nochmal getestet. Ja. Neustart, 30 Sekunden kein Empfang. Einstellungen ->DTU -> Speicher , 3 sek später die live Daten.

2024-05-10 22:07 UTC, AndreasBoehm commented on webapp/src/views/PowerLimiterAdminView.vue
> +        },
I wasn't aware of this and added a check in the PowerLimitier, thank you for pointing that out.

2024-05-10 22:08 UTC, AndreasBoehm commented on webapp/src/locales/de.json
> +        "UseOverscalingToCompensateShading": "Wechselrichter-Limit im Zweifel Überskalieren, um Verschattung eines oder mehrerer Eingänge auszugleichen",
You are totally right, changes pushed.

2024-05-10 22:08 UTC, AndreasBoehm commented on src/PowerLimiter.cpp
> +    if(allowOverscaling) {
Check added

2024-05-10 22:37 UTC, hex2647 commented
> @greymda @spcqike @hex2647 Please test this feature by flashing the firmware built in [this PR's build-run](https://github.com/helgeerbe/OpenDTU-OnBattery/actions/runs/9031462329?pr=956).

Ist installiert und aktiviert... morgen ist bei mir keine Verschattung zu erwarten aber das lässt sich ja simulieren :) bin gespannt.

2024-05-10 23:37 UTC, AndreasBoehm commented on webapp/src/locales/de.json
> +        "UseOverscalingToCompensateShading": "Wechselrichter-Limit im Zweifel Überskalieren, um Verschattung eines oder mehrerer Eingänge auszugleichen",
I also added details in the wiki: https://github.com/helgeerbe/OpenDTU-OnBattery/wiki/Dynamic-Power-Limiter-(Nulleinspeisung)-%E2%80%93-OHNE-BATTERIE#compensation-for-shaded-modulesinputs-by-overscaling-starting-from-release-202405

2024-05-11 08:48 UTC, AndreasBoehm commented
Es sieht so aus als ob ich die Logik nochmal überarbeiten muss, habe zwei Eingänge mit 50W und zwei die bis zu 100w bekommen. Netzbezug ist auf -100W gestellt, trotzdem regelt die Überskalierung effektiv auf -200W.

Konnte jemand von euch ein ähnliches Problem feststellen?

2024-05-11 10:19 UTC, hex2647 commented
Das bisher noch nicht. Was mir vorhin aufgefallen war ist das er total instabil war, also das die Regelung extrem geschwankt hat… ich Versuch das nachher mal festzuhalten und besser darzustellen…

2024-05-11 10:38 UTC, spcqike commented
Hab es auch grad getestet. Schwankt stark. Entweder voll offen (2.000W) oder das normale Limit, welches nicht ausreicht 

<img width="375" alt="image" src="https://github.com/helgeerbe/OpenDTU-OnBattery/assets/50098985/b67bc9a6-d28b-418d-8a26-f22dc2f3813b">

hab zum testen 1 Paneel abgesteckt und das Target grad auf 800W gestellt.

2024-05-11 11:17 UTC, AndreasBoehm commented on src/PowerLimiter.cpp
> +        auto overScaled = static_cast<int32_t>((newLimit - limitedChannelPowerSum) * dcTotalChnls);
Note to myself: The scaled limit should be based on the non-limited MPPTs only, otherwise the limit is way too high.

2024-05-11 11:17 UTC, AndreasBoehm commented on src/PowerLimiter.cpp
> +        auto expectedPowerPerChannel = currentLimitWatts / dcTotalChnls;
Note to myself: try to use a threshold (e.g. 98%) to avoid that the limit is fluctuating a lot

2024-05-11 11:34 UTC, spcqike commented on src/PowerLimiter.cpp
> +        auto expectedPowerPerChannel = currentLimitWatts / dcTotalChnls;
Sollte das Limit pro Kanal nicht mit der gesamt Effizienz des inverters im Verhältnis stehen? 

E.g. 95.5% -> bei 400W Limit beim hms-2000 sollten pro Kanal 105W fließen.

2024-05-11 11:47 UTC, spcqike commented on src/PowerLimiter.cpp
> +        auto overScaled = static_cast<int32_t>((newLimit - limitedChannelPowerSum) * dcTotalChnls);
It should be something like 

(newlimit - nonlimited)/number_limited*number_total 

so eg 1000W target - 100W non limited /3 * 4 -> 1200W new limit. So each non limited input can deliver up to 300W and the limited input only delivers 100W. 

Should it?

2024-05-12 21:42 UTC, AndreasBoehm commented on src/PowerLimiter.cpp
> +        auto overScaled = static_cast<int32_t>((newLimit - limitedChannelPowerSum) * dcTotalChnls);
Thanks for your input, i did some calculations and came up with a quiet similar formula.

```
(target - limitedSum) / non_limited_channels_count * total_channel_count
```

|Target| Limited sum | Non limited channels | Calculation | Result |
|------|--------------|----------------------|------------|-------|
|1000|100|3|(1000 - 100) / 3 * 4|1200|
|400|150|1|(400 - 150) / 1 * 4|1000|

2024-05-12 22:30 UTC, AndreasBoehm commented on src/PowerLimiter.cpp
> +        auto expectedPowerPerChannel = currentLimitWatts / dcTotalChnls;
Gute Idee! Das Thema kann ich angehen sobald die Regelung grundsätzlich richtig funktioniert.

2024-05-12 22:31 UTC, AndreasBoehm commented
Danke fürs testen @spcqike und @hex2647.
Ich habe den Fehler für die instabile und schwankende Regelung und auch den Fehler in der Berechnung für das Limit behoben. Vorerst zähle ich einen Eingang der 95% des Limits liefert als nicht limitiert um bei minimalen Schwankungen nicht zu viel zu skalieren, was haltet ihr davon?

@schlimmchen Könntest du den workflow erneut freigeben um neue test builds bereitzustellen? Danke.

2024-05-13 04:32 UTC, schlimmchen commented
Neue Firmware: https://github.com/helgeerbe/OpenDTU-OnBattery/actions/runs/9054654684

2024-05-13 06:39 UTC, spcqike commented
> Vorerst zähle ich einen Eingang der 95% des Limits liefert als nicht limitiert um bei minimalen Schwankungen nicht zu viel zu skalieren, was haltet ihr davon?

ich weiß nicht, ob das so hinkommt. 

```
auto expectedPowerPerChannel = (newLimit / dcTotalChnls) * 0.95;

        size_t dcLimitedChnls = 0;
        auto limitedChannelPowerSum = 0.0;

        for (auto& c : dcChnls) {
            auto channelPower = inverter->Statistics()->getChannelFieldValue(TYPE_DC, c, FLD_PDC);

            if (channelPower < expectedPowerPerChannel) {
                dcLimitedChnls++;
                limitedChannelPowerSum += channelPower;
            }
        }
```

vielleicht verstehe ich auch nur die Variablen falsch, aber sollte man nicht die **nicht** begrenzten Eingänge zählen? und sollte man nicht gegen das alte Limit vergleichen? Sollte es nicht eher so werden?

```
auto expectedPowerPerChannel = (currentLimitWatts/ dcTotalChnls) / 0.95;

        size_t dcNotLimitedChnls = 0;
        auto notLimitedChannelPowerSum = 0.0;

        for (auto& c : dcChnls) {
            auto channelPower = inverter->Statistics()->getChannelFieldValue(TYPE_DC, c, FLD_PDC);

            if (channelPower < expectedPowerPerChannel) {
                dcNotLimitedChnls ++;
                notLimitedChannelPowerSum += channelPower;
            }
        }

        if (dcNotLimitedChnls == 0 || dcNotLimitedChnls == dcTotalChnls) { return newLimit; }

        auto overScaled = static_cast<int32_t>((newLimit - notLimitedChannelPowerSum ) /(dcTotalChnls-dcNotLimitedChnls) * dcTotalChnls);

        MessageOutput.printf("[DPL::scalePowerLimit] %d/%d channels are producing less than expected, "
                "scaling from %d to %d W\r\n", dcNotLimitedChnls , dcTotalChnls, newLimit, overScaled);
        return overScaled;
```

Wie oben geschrieben, müsste 1. anhand des aktuell gültigen Limits verglichen werden. (Wenn das Limit bspw. von 1000W auf 300W fällt, und man die aktuelle DC Leistung gegen das neue Limit vergleicht, liefern alle DC Eingänge zu viel)
Dann müsste 2. herausgefunden werden, welche Eingänge NICHT durch das Software-Limit begrenzt sind (sondern durch Verschattung). die Summe der "unter performenden" Eingänge und deren Leistung ist wichtig.

Ob man nun fixe 95% annimmt, oder die aktuelle Effizienz, oder den Wert einfach bei 1 belässt (immerhin wird die erwartete DC Leistung dadurch nur erhöht. DC-seitig liefern die Eingänge immer mehr, als man AC-seitig haben will.), kann man ja einfach ausprobieren.

Was man vielleicht noch einbauen sollte

```
 if (newLimit < currentLimitWatts) { return newLimit; }
```

Die Skalierung braucht nicht gemacht zu werden, wenn das Limit sich verkleinert. Die Berechnung 

```
auto overScaled = static_cast<int32_t>((newLimit - limitedChannelPowerSum) / dcNonLimitedChnls * dcTotalChnls);
```

wird nicht sinnvoll klappen, wenn das neue Limit, durch Verbrauchsreduzierung, wesentlich kleiner wird. im Gegenteil, extrem Beispiel: das alte LImit war 800W, das neue ist 50W. Was passiert da?

2024-05-13 07:32 UTC, AndreasBoehm commented
> vielleicht verstehe ich auch nur die Variablen falsch, aber sollte man nicht die **nicht** begrenzten Eingänge zählen? und sollte man nicht gegen das alte Limit vergleichen? Sollte es nicht eher so werden?
Ich hab die Variablen umbenannt um deutlich zu machen das in meinem Fall "limited" ein "limited by shading" war und nicht "limited by inverter limit". Eventuell kannst du mit dieser Info meine Berechnungen nachvollziehen.


> 
> ```
> auto expectedPowerPerChannel = (currentLimitWatts/ dcTotalChnls) / 0.95;
Hast du hier eine Effizienz von 95% angenommen um den AC wert von 'currentLimitWatts' in DC zu wandeln?

>         size_t dcNotLimitedChnls = 0;
>         auto notLimitedChannelPowerSum = 0.0;
> 
>         for (auto& c : dcChnls) {
>             auto channelPower = inverter->Statistics()->getChannelFieldValue(TYPE_DC, c, FLD_PDC);
> 
>             if (channelPower < expectedPowerPerChannel) {
>                 dcNotLimitedChnls ++;
>                 notLimitedChannelPowerSum += channelPower;
>             }
>         }
> 
>         if (dcNotLimitedChnls == 0 || dcNotLimitedChnls == dcTotalChnls) { return newLimit; }
> 
>         auto overScaled = static_cast<int32_t>((newLimit - notLimitedChannelPowerSum ) /(dcTotalChnls-dcNotLimitedChnls) * dcTotalChnls);
> 
>         MessageOutput.printf("[DPL::scalePowerLimit] %d/%d channels are producing less than expected, "
>                 "scaling from %d to %d W\r\n", dcNotLimitedChnls , dcTotalChnls, newLimit, overScaled);
>         return overScaled;
> ```
> 
> Wie oben geschrieben, müsste 1. anhand des aktuell gültigen Limits verglichen werden. (Wenn das Limit bspw. von 1000W auf 300W fällt, und man die aktuelle DC Leistung gegen das neue Limit vergleicht, liefern alle DC Eingänge zu viel) Dann müsste 2. herausgefunden werden, welche Eingänge NICHT durch das Software-Limit begrenzt sind (sondern durch Verschattung). die Summe der "unter performenden" Eingänge und deren Leistung ist wichtig.

Du hast recht, da hatte ich einen Fehler in meiner Logik, ich werde den Code anpassen un das aktuelle Limit verwenden um zu ermitteln ob ein Eingang verschattet ist.


> Ob man nun fixe 95% annimmt, oder die aktuelle Effizienz, oder den Wert einfach bei 1 belässt (immerhin wird die erwartete DC Leistung dadurch nur erhöht. DC-seitig liefern die Eingänge immer mehr, als man AC-seitig haben will.), kann man ja einfach ausprobieren.

Ich denke du vermischt hier zwei Dinge a) AC <-> DC Umwandlung und die Effizienz davon und b) Threshold der z.b. auch bei 61 Watt bei geforderten 64 Watt den Eingang als `non shaded` wertet.

**a)** werde ich sobald die Regelung klappt noch mit einbauen, denn nur dann entspricht das Limit auch wirklich dem was man erwartet.
**b)** sollten wir diskutieren, aktuell nutze ich hier 95%

> Was man vielleicht noch einbauen sollte
> 
> ```
>  if (newLimit < currentLimitWatts) { return newLimit; }
> ```

Das kann man pauschal so nicht machen, denn `newLimit` wird immer kleiner sein als `currentLimitWatts` wenn wir aktuell im 'Overscaling' sind, auch kann das neue Limit kleiner sein aber es trotzdem bedarf geben eine Verschattung auszugleichen.

> Die Skalierung braucht nicht gemacht zu werden, wenn das Limit sich verkleinert. Die Berechnung
> 
> ```
> auto overScaled = static_cast<int32_t>((newLimit - limitedChannelPowerSum) / dcNonLimitedChnls * dcTotalChnls);
> ```
> 
> wird nicht sinnvoll klappen, wenn das neue Limit, durch Verbrauchsreduzierung, wesentlich kleiner wird. im Gegenteil, extrem Beispiel: das alte LImit war 800W, das neue ist 50W. Was passiert da?

Dafür gibt es eine extra Abfrage die einfach `newLimit` zurück gibt wenn alle Eingänge die Erwartungen erfüllen. Gibt dann ja keinen 'shaded channel'.

2024-05-13 08:17 UTC, AndreasBoehm commented
> Was man vielleicht noch einbauen sollte
> 
> ```
>  if (newLimit < currentLimitWatts) { return newLimit; }
> ```
> 
> Die Skalierung braucht nicht gemacht zu werden, wenn das Limit sich verkleinert.

Da wir nun 'currentLimitWatts' zur Berechnung nutzen habe ich verstanden warum du diese Vorschlag bringst.
Ich würde vorschlagen das wir in dem fall aber dann einfach mit 'newLimit' prüfen ob wir einen verschatetten Eingang haben um gleich korrekt zu skalieren. Was denkst du?

2024-05-13 08:47 UTC, spcqike commented
> Hast du hier eine Effizienz von 95% angenommen um den AC wert von 'currentLimitWatts' in DC zu wandeln?

naja, die 95% habe ich von dir übernommen, aber ja 😄 dazu habe ich ja noch folgende Gedanken gehabt

> Ob man nun fixe 95% annimmt, oder die aktuelle Effizienz, oder den Wert einfach bei 1 belässt (immerhin wird die erwartete DC Leistung dadurch nur erhöht. DC-seitig liefern die Eingänge immer mehr, als man AC-seitig haben will.), kann man ja einfach ausprobieren.

Muss man halt mal gucken, ob und wie 95%, die tatsächliche Effizienz oder aber auch ne "1" sich auswirken. die DC Leistung ist definitiv immer höher als die AC Leistung. Es wäre also falsch, das ``(lastLimit / dcTotalChnls)*factor`` anzunehmen, da der Erwartungswert damit immer kleiner wird und Eingänge als "gesättigt" bzw. durch den Software-Limiter begrenzt interpretiert werden, obwohl sie es nicht sind.

> Ich denke du vermischt hier zwei Dinge a) AC <-> DC Umwandlung und die Effizienz davon und b) Threshold der z.b. auch bei 61 Watt bei geforderten 64 Watt den Eingang als non shaded wertet.
> 
> a) werde ich sobald die Regelung klappt noch mit einbauen, denn nur dann entspricht das Limit auch wirklich dem was man erwartet.
b) sollten wir diskutieren, aktuell nutze ich hier 95%

Tue ich das? 
Hier ein Auszug meines HMS-2000
![grafik](https://github.com/helgeerbe/OpenDTU-OnBattery/assets/50098985/76800383-5b93-49ac-85db-5936b27550be)

Das Limit ist 600W, jeder Eingang kann also 150W, die Effizienz ist aktuell ~ 95%. 

``auto expectedPowerPerChannel = (currentLimitWatts/ dcTotalChnls) / 0.95;`` liefert also 157.9W zurück. Jeder Eingang liefert (leicht) mehr, ist also rein durch den Limiter begrenzt. 

``auto expectedPowerPerChannel = (currentLimitWatts/ dcTotalChnls);`` würde halt rein 150W zurück geben, auch da liegt jeder Eingang drüber. 

welchen Threshold wir annehmen können, sollten wir testen. Sauberer wäre wahrscheinlich der erste, da ein EIngang, der in diesem Fall "nur" 155W liefert, tatsächlich nicht sein Maximum erreicht 😄 aber ob die fehlenden ~2W pro Eingang am Ende ins Gewicht fallen? (wobei 5% Abweichung bei angenommenen 1500W Limit bereits 75W ausmachen können ..... 🤔)

> Das kann man pauschal so nicht machen, denn newLimit wird immer kleiner sein als currentLimitWatts wenn wir aktuell im 'Overscaling' sind

da hast du natürlich recht.

> Ich würde vorschlagen das wir in dem fall aber dann einfach mit 'newLimit' prüfen ob wir einen verschatteten Eingang haben um gleich korrekt zu skalieren. Was denkst du?

klingt sinnig. aber wie du auch korrekt feststellst ``newLimit wird immer kleiner sein als currentLimitWatts wenn wir aktuell im 'Overscaling' sind`` damit trifft es ja wieder immer zu, oder? 😞 


ach, ärgerlich. ich habe meinen Branch leider bereits gelöscht, hatte doch aber genau solch eine Regelung bereits laufen 😄 inkl. der Probleme des Überschwingens und der Beseitigung derer https://github.com/helgeerbe/OpenDTU-OnBattery/pull/241

2024-05-13 08:58 UTC, spcqike commented
Nachtrag:

Was ich in meinem ehemaligen PR noch sehe: ich hatte ne Abfrage, ob die tatsächliche AC Ausgangsleistung < dem newLimit ist

``maxPower >= _lastRequestedPowerLimit / dcTotalChnls && inverter->Statistics()->getChannelFieldValue(TYPE_AC, (ChannelNum_t)config.PowerLimiter_InverterChannelId, FLD_PAC) < newPowerLimit``

Nicht schön, aber die Abfrage ist ja quasi "maxPower (irgendeines Eingangs) >= durch den Limiter begrenzte Leistung (hier ohne Berücksichtigung der Effizienz) UND  AC Leistung des Inverters < newPowerLimit". Wenn also mindestens 1 Eingang durch den Limiter begrenzt ist, also mehr liefern könnte, und das AC Limit dennoch nicht erreicht wird.

2024-05-13 11:08 UTC, spcqike commented
Ich nochmal:

Ich hab mir die Anpassungen nochmal angeguckt, vielleichts liegts ja an mir / meinem Verständnis, aber ist das nicht doch falsch=

``auto expectedAcPowerPerChannel = (newLimit / dcTotalChnls) * 0.95;``

und später

```
            auto channelPowerDC = inverter->Statistics()->getChannelFieldValue(TYPE_DC, c, FLD_PDC);

            if (channelPowerDC < expectedAcPowerPerChannel) {
                //shaded channel
```

Du berechnest einen zu erwartenden AC Leistungswert pro Eingang und vergleichst diesen später mit der DC Eingangsleistung? 

Wäre es nicht besser, den DC Anteil pro Eingang zu berechnen und dann DC mit DC zu vergleichen?

Wenn ich deine Berechnung richtig verstehe, unter der Annahme eines HM-600 und 300W limit. Jeder Eingang muss, nach deiner berechnung 300/2*0.95 -> 142.5W DC liefern. alles unter 142.5W wird als verschattet angenommen.

Wenn wir also 158W und 145W annehmen, ist das System stabil und nicht verschattet, auch wenn uns 13W AC-seitig fehlen (158+145 -> 303W DC; 95% Effizienz -> ~287W AC output) bei höheren Leistungen driftet es noch weiter auseinander, ohne dass das System skalieren würde. (bspw. der HMS-2000, mit 1500W Limit. bei deiner Berechnung wären 356W ok und nicht verschattet. in Wahrheit misst er aber 403W pro Eingang, immerhin knapp 50W pro Eingang mehr)

Wäre es nicht besser direkt in DC zu rechnen?

``auto expectedDcPowerPerChannel = (currentLimitWatts/ dcTotalChnls) / 0.95;``

gäbe 158W DC pro nicht verschatteten Eingang, bzw. für einen rein durch das Softwarelimit begrenzten Eingang.


Wenn ich so drüber nachdenke, glaube ich, dass der Punkt

``maxPower >= _lastRequestedPowerLimit / dcTotalChnls && inverter->Statistics()->getChannelFieldValue(TYPE_AC, (ChannelNum_t)config.PowerLimiter_InverterChannelId, FLD_PAC) < newPowerLimit`` doch recht wichtig ist bzw. damals war. Dass die Skalierung stattfindet, wenn wenigstens 1 Eingang durch den Wechselrichter limitiert ist und die aktuelle AC Leistung dem neuen Limit nicht gerecht wird.

2024-05-14 21:28 UTC, AndreasBoehm commented on src/PowerLimiter.cpp
> +        auto expectedPowerPerChannel = currentLimitWatts / dcTotalChnls;
Ich arbeite jetzt nur noch mit Leistung in AC um hier exakt zu arbeiten.

2024-05-14 23:08 UTC, AndreasBoehm commented
@spcqike Danke für deine Infos und Gedanken.

Ich habe jetzt alles umgestellt auf AC, damit lässt sich sinnvoller mit dem aktuellen Limit vergleichen und auch besser das neue Limit berechnen.

Habe auch noch ein paar mehr Regeln hinzugefügt um sicherzugehen das wir weiter hochskalieren wenn das Limit noch nicht ausreicht um die gewünschte Energie zu liefern und auch um das Limit wieder zu senken falls gefordert, ohne das uns die skalierung dazwischen kommt.

Ich würde mich freuen wenn du nochmal drüber schaust und probierst ob jetzt alles funktioniert.

@schlimmchen Könntest du den workflow bitte erneut freigeben? Danke.

2024-05-15 14:33 UTC, AndreasBoehm commented
@greymda @spcqike @hex2647 Please test the latest changes by flashing the firmware built in [this PR's build-run](https://github.com/helgeerbe/OpenDTU-OnBattery/actions/runs/9087695629).

2024-05-15 17:11 UTC, hex2647 commented
Install stops at 5%?
![IMG_1404](https://github.com/helgeerbe/OpenDTU-OnBattery/assets/161470023/e5a2db01-2bba-4400-8cc8-2b80436257dc)

2024-05-15 17:29 UTC, spcqike commented
Bei mir ist es durchgelaufen. Hab es leider zu spät gemacht. Heute wird es nichts mehr mit testen :) 

Gebe morgen Bescheid

2024-05-15 17:50 UTC, schlimmchen commented
> Install stops at 5%?

That's a weird error situation that I observe myself regularly. Need to restart the DTU, then try again.

2024-05-16 07:07 UTC, spcqike commented
mit aktivem DPL bekomme ich weider ganz viele Timeouts, der WEchselrichter ist nicht erreichbar. Hat jemand von euch ähnliche Probleme?

ich habe den HMS-2000. 
Mir kommt es so vor, als wenn zu viele und zu häufige Abfragen/Anfragen irgendwie Probleme verursachen...

2024-05-16 08:31 UTC, AndreasBoehm commented
> mit aktivem DPL bekomme ich weider ganz viele Timeouts, der WEchselrichter ist nicht erreichbar. Hat jemand von euch ähnliche Probleme?
> 
> 
> 
> ich habe den HMS-2000. 
> 
> Mir kommt es so vor, als wenn zu viele und zu häufige Abfragen/Anfragen irgendwie Probleme verursachen...

Hab den HMS-1600 und anfangs ähnliche Probleme. Hab die DTU dann in einen anderen Raum gestellt, näher an den WR, seitdem habe ich keine Probleme mehr.

2024-05-16 10:07 UTC, spcqike commented
naja, da ich an der DTU und den Positionen nichts geändert habe und es bis dato gut und stabil lief (also nur das Abfragen der Daten, kein DPL aktiv), und es auch wieder gut läuft, wenn der DPL aus ist, denke ich nicht, dass es an der Aufstellung liegt.

es gibt auch im Upstream mehrere Issues, weil die HMS die Verbindung wohl des öfteren verlieren in letzter Zeit.
bspw.: https://github.com/tbnobody/OpenDTU/issues/1921


Das, was ich jetzt getestet habe, sah gut aus. 
![grafik](https://github.com/helgeerbe/OpenDTU-OnBattery/assets/50098985/aad808a9-7e04-4576-bbb4-0e66621dc295)

rot die PV Erzeugung, orange der Gesamtbezug (bzw. Einspeisung). Target: -1000W (sonst greift die Skalierung grad nicht, da jeder Eingang > 250W liefert :D)

Ab und zu bekommt er die -1000W nicht hin, aber da scheint auch kein neuer Wert von der DTU zu kommen, also wird auch der neue Limit nicht durchgehen... Was auch immer den Empfang da beeinträchtigt... 

jetzt, wo der DPL wieder aus ist, ist die Aufzeichnung der PV-Leistung auch wieder konsistent. Die Abfrage klappt im 5s DTU Intervall aller 5-10s.

2024-05-17 06:25 UTC, hex2647 commented
> > Install stops at 5%?
> 
> That's a weird error situation that I observe myself regularly. Need to restart the DTU, then try again.

That Solved it… its installed

2024-05-20 20:44 UTC, hex2647 commented
> Hab es auch grad getestet. Schwankt stark. Entweder voll offen (2.000W) oder das normale Limit, welches nicht ausreicht
> 
> <img alt="image" width="375" src="https://private-user-images.githubusercontent.com/50098985/329774871-b67bc9a6-d28b-418d-8a26-f22dc2f3813b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyMzgxMTIsIm5iZiI6MTcxNjIzNzgxMiwicGF0aCI6Ii81MDA5ODk4NS8zMjk3NzQ4NzEtYjY3YmM5YTYtZDI4Yi00MThkLThhMjYtZjIyZGMyZjM4MTNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIwVDIwNDMzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMyZWIzNDJlOTNjYTVjYTczZGEwNWY2ZjMwNjQ4YTVhODhkYmE5YTBhMDA5OWQzZjQ0MGM2NWFjZDQ3YzMyZmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rZzIGsA4E0QoPGBqRilPltFVTzUFhNIDhPsxm4-rOPQ">
> hab zum testen 1 Paneel abgesteckt und das Target grad auf 800W gestellt.

@spcqike: Wie bekomm ich denn die schicken Charts? Dadurch würde vermutlcih das Fehler beschreiebn deutlich leichter werden :)

2024-05-20 20:52 UTC, hex2647 commented
> @greymda @spcqike @hex2647 Please test the latest changes by flashing the firmware built in [this PR's build-run](https://github.com/helgeerbe/OpenDTU-OnBattery/actions/runs/9087695629).

Ich konnte heute nochmal etwas genauer draufschauen. Grundsätzlich würde ich sagen sieht das ganze ganz gut aus aber heute ist nochmal ein Spannender Fall aufgetreten (tatsächlich mehrfach)...

Ausgewirkt hat es sich darin das die DTU sich auf einem viel zu niedrigen Wert "festgeschossen hat"... Resulatat waren die 104,7 Watt aus dem Inverter obwohl genug Sonne und auch genug Leistung aus dem Netz abgerufen wurden:
![IMG_1435](https://github.com/helgeerbe/OpenDTU-OnBattery/assets/161470023/1165fd34-16eb-4b5b-a815-1b97fda189ee)

Auch im Log zu sehen: Aus irgend einem Grund behält er die 240W obwohl er eigentlich mehr machen sollte... Auf welcher Datenbasis entscheidet er hier das alle Strings weniger machen als erwartet?

Websocket: [/livedata][14] disconnect
13:12:50.963 > [DPL::loop] ******************* ENTER **********************
13:12:51.584 > [DPL::calcPowerLimit] battery use prevented, solar power (DC): 10000 W
13:12:51.615 > [DPL::calcPowerLimit] target consumption: 0 W, base load: 70 W, power meter does include inverter output
13:12:51.892 > [DPL::calcPowerLimit] power meter value: 2979 W, power meter valid: yes, inverter output: 104 W, solar power (AC): 9215 W
13:12:51.909 > [DPL::calcPowerLimit] limited to solar power: 3083 W
13:12:51.924 > [DPL::setNewPowerLimit] input limit: 3083 W, min limit: 10 W, max limit: 1000 W, hysteresis: 5 W
13:12:51.953 > [DPL::scalePowerLimit] all channels are producing less than expected, keeping the current limit of 240 W instead of 1000 W by 
13:12:51.970 > [DPL::setNewPowerLimit] inverter max: 2000 W, inverter is producing, requesting: 240 W, reported: 240 W, diff: 0 W
13:12:52.016 > [DPL::announceStatus] the system is stable, the last power limit is still valid

2024-05-20 22:53 UTC, spcqike commented
@hex2647 in meinem Fall mit NodeRed (Processing), influxdb (Datenbank) und grafana (Frontend für Graphen und Dashboards) 

> Aus irgend einem Grund behält er die 240W obwohl er eigentlich mehr machen sollte... Auf welcher Datenbasis entscheidet er hier das alle Strings weniger machen als erwartet?

er berechnet es. Wenn dein Limit zu der Zeit 240W waren, sollte er ja 60W pro Eingang liefern. Scheinbar liefert er insgesamt nur 104W und auf jedem Eingang < 58W. Daher gibt es noch keinen Grund das Limit zu ändern, da auch ein höheres Limit nicht mehr Output liefern würde. 

Kannst du, sollte sowas wieder passieren, auch Screenshots der wechselrichter Daten(Gesamtleistung, Effizienz,…) und der einzelnen Eingänge beistellen? Dass man besser nachvollziehen kann, was genau grade passiert?

2024-05-21 05:31 UTC, AndreasBoehm commented
> ... das die DTU sich auf einem viel zu niedrigen Wert "festgeschossen hat"... Resulatat waren die 104,7 Watt aus dem Inverter obwohl genug Sonne und auch genug Leistung aus dem Netz abgerufen wurden

Vielen Dank fürs testen und berichten.

Ich habe einen ähnlichen Fall beobachtet, dachte aber es liegt an meinem Anker Solarspeicher.

Um uns das lösen des Problems einfacher zu machen werde ich nachher die Konsolen Ausgabe um einige Daten erweitern die uns helfen sollten zu verstehen warum die Berechnung auf einem niedrigen Wert "hängen bleibt".

2024-05-21 06:45 UTC, AndreasBoehm commented
Ich habe die Konsolen Ausgabe erweitert, sieht nun wie folgt aus:
(Aktuell ist die Sonne hinter den schwarzen Wolken versteckt)
```
08:41:51.248 > [DPL::calcPowerLimit] battery use prevented, solar power (DC): 10000 W
08:41:51.253 > [DPL::calcPowerLimit] target consumption: -150 W, base load: 100 W, power meter does include inverter output
08:41:51.258 > [DPL::calcPowerLimit] power meter value: 164 W, power meter valid: yes, inverter output: 72 W, solar power (AC): 9231 W
08:41:51.268 > [DPL::calcPowerLimit] limited to solar power: 386 W
08:41:51.290 > [DPL::setNewPowerLimit] input limit: 386 W, min limit: 40 W, max limit: 1600 W, hysteresis: 5 W
08:41:51.304 > [DPL::scalePowerLimit::debug] checking for shading, inverterInputDC 76.599998 W, inverterOutputAC 72.900002 W, inverterEfficiencyFactor 0.951697, expectedAcPowerPerChannel 90.160000 W, currentLimitWatts 368 W, newLimit 386 W
08:41:51.306 > [DPL::scalePowerLimit::debug] channel 0 is producing less than expected, channelPowerAC 3.901958 W, channelPowerDC 4.100000 W
08:41:51.314 > [DPL::scalePowerLimit::debug] channel 1 is producing less than expected, channelPowerAC 3.806789 W, channelPowerDC 4.000000 W
08:41:51.319 > [DPL::scalePowerLimit::debug] channel 2 is producing less than expected, channelPowerAC 31.025326 W, channelPowerDC 32.599998 W
08:41:51.339 > [DPL::scalePowerLimit::debug] channel 3 is producing less than expected, channelPowerAC 34.165932 W, channelPowerDC 35.900002 W
08:41:51.346 > [DPL::scalePowerLimit] 4/4 channels are producing less than expected, shadedChannelACPowerSum 71 W
08:41:51.353 > [DPL::scalePowerLimit] all channels are producing less than expected, keeping the current limit of 368 W instead of 386 W
08:41:51.359 > [DPL::setNewPowerLimit] inverter max: 1600 W, inverter is producing, requesting: 368 W, reported: 368 W, diff: 0 W
```

@schlimmchen Könntest du den workflow erneut freigeben? Danke.

2024-05-21 08:43 UTC, AndreasBoehm commented
> Wenn ich so drüber nachdenke, glaube ich, dass der Punkt
> 
> `maxPower >= _lastRequestedPowerLimit / dcTotalChnls && inverter->Statistics()->getChannelFieldValue(TYPE_AC, (ChannelNum_t)config.PowerLimiter_InverterChannelId, FLD_PAC) < newPowerLimit` doch recht wichtig ist bzw. damals war. Dass die Skalierung stattfindet, wenn wenigstens 1 Eingang durch den Wechselrichter limitiert ist und die aktuelle AC Leistung dem neuen Limit nicht gerecht wird.

Kannst du mir eventuell noch erläutern welchen Fall du mit diesem if sicherstellst bzw welche action anschließend ausgeführt wurde? Ich bin mir aktuell nicht sicher ob wir das so brauchen oder nicht.

2024-05-21 08:48 UTC, spcqike commented
könntest du die Ausgabe abrunden? auf eine, oder gar keine Nachkommastelle? ich denke 72.123456 W macht wenig Sinn. Ganze Watt sollten ausreichen, oder?

In der Vergangenheit gab es Probleme, wenn die Nachrichten zu lang wurden, dann wurden Daten einfach abgeschnitten oder nicht angezeigt, oder es kam zu anderen komischen Verhalten.

auch finde ich

> 08:41:51.304 > [DPL::scalePowerLimit::debug] checking for shading, inverterInputDC 76.599998 W, inverterOutputAC 72.900002 W, inverterEfficiencyFactor 0.951697, expectedAcPowerPerChannel 90.160000 W, currentLimitWatts 368 W, newLimit 386 W

echt lang. 

Ich persönlich würd Debug-nachrichten kürzer halten, ja fast kryptisch, und ggf. n Kommentar an der Stelle im Code lassen, was was genau ist. 

> 08:41:51.314 > [DPL::scalePowerLimit::debug] channel 1 is producing less than expected, channelPowerAC 3.806789 W, channelPowerDC 4.000000 W

ebenfalls, reicht nicht "ch0: shaded, 4W", bzw. "chx: not shaded, 32W"?

AC und DC sind redundant, da beides mit der gleichen Effizienz von ein paar Zeilen vorher berechnet wird, oder?


Ich find den Umgang mit AC/DC noch immer verwirrend, aber das mag an mir und meinem Verständnis liegen :) aber, reicht es nicht, sich auf einen Wert festzulegen? AC oder DC?

Ich würde die ganzen Berechnungen und Vergleiche anhand der DC Werte machen. Ja, wir möchten ein AC Limit setzen, dafür bedarf es aber einer DC Gesamt-Leistung, die, nachdem sie einmal berechnet wurde, 1 zu 1 mit den DC Eingängen weiter berechnet/verglichen werden kann. oder ?

2024-05-21 09:00 UTC, AndreasBoehm commented
@spcqike Die meisten Nachrichten werfe ich wieder raus sobald wir wissen das der Algorithmus funktioniert.
Ich gebe jeweils AC und DC aus um euch mehr Infos zu geben über die Daten mit denen ich arbeite. Falls die Skalierung nicht wie erwartet arbeitet sehe ich dann alle Werte und kann direkt prüfen ob es irgendwo einen Rechenfehler gibt. AC zu nutzen schien mir am elegantesten, da ich am Schluss auch die Summe der Shaded-Inputs in AC vom newLimit (AC) abziehen muss, und auch das aktuelle Limit in AC vorliegt. Natürlich können wir das auch alles in DC machen, ich sehe keinen Vor- oder Nachteil mit AC oder DC. Kann ich für das nächste Test build gerne umstellen wenn es dir hilft um mich zu unterstützen

2024-05-21 09:05 UTC, spcqike commented
> Kannst du mir eventuell noch erläutern welchen Fall du mit diesem if sicherstellst bzw welche action anschließend ausgeführt wurde?

So ganz nachvollziehen kann ich das auch nicht mehr. Dafür hat sich auch der Code in Gänze zu stark geändert (also auch die Punkte vor den Skalierungen)

Sinn war aber, dass nur skaliert wird, wenn nötig. also dann, wenn:
- mindestens 1 Eingang durch das Softwarelimit limitiert wird (``maxPower >= _lastRequestedPowerLimit / dcTotalChnls`` maxPower ist einfach die maximale DC EIngangsleistung die an irgend einem Eingang anliegt, ohne Korrektur der Effizienz. Daher klappt auch der Vergleich, da ``_lastRequestedPowerLimit`` ein AC Limit ist, welches, nach Berücksichtigung der Effizienz, ja kleiner wird. also wäre bspw 158W DC maxPower >= 300W / 2 -> 158W DC Leistung bei 150W AC Limit pro Eingang (beim HM-600?) -> Der Eingang "überperformt"/ist nicht verschattet / ist rein durch das Limit begrenzt. Natürlich nicht 100% sauber, dein aktueller Ansatz mit Berücksichtigung der Effizienz macht es granularer und sauberer) 
**UND** 
- die aktuelle AC Ausgangsleistung kleiner ist, als das, was wir eigentlich wollen. (``inverter->Statistics()->getChannelFieldValue(TYPE_AC, (ChannelNum_t)config.PowerLimiter_InverterChannelId, FLD_PAC) < newPowerLimit``)

Heißt: mindestens ein Kanal könnte mehr liefern um das bisher nicht erreichte Ziel zu erreichen.

Sonst hab ich keine Skalierung gemacht gehabt. wenn nichts durch Software limitiert ist (sondern alles durch durch Verschattung), oder wenn das Ziel erreicht wird (also bspw. alle durch Software limitiert).

Ich glaube, diese Umstände hast du bereits abgefangen, aber eben später im Code und teilweise umfangreicher. 

Eine Skalierung wie "wir haben grad 500W, wollen runter auf 300W, Eingang 1 liefert aber nur 100W also brauchen wir ein Limit von 400W um 300W AC seitig zu erreichen" (wieder für ein 2-MPPT Modell) hatte ich damals noch nicht drin.

2024-05-25 13:37 UTC, hex2647 commented
Hab jetzt nochmal umgebaut sodass alle 4 Eingänge belegt sind… er skaliert aber trotzdem nicht hoch. Obwohl er eigentlich selbst sagt das die Module verschattet sind?

15:35:33.778 > [DPL::loop] ******************* ENTER **********************
15:35:33.807 > [DPL::calcPowerLimit] battery use prevented, solar power (DC): 10000 W
15:35:33.838 > [DPL::calcPowerLimit] target consumption: 0 W, base load: 70 W, power meter does include inverter output
15:35:33.865 > [DPL::calcPowerLimit] power meter value: 287 W, power meter valid: yes, inverter output: 108 W, solar power (AC): 9224 W
15:35:33.897 > [DPL::calcPowerLimit] limited to solar power: 395 W
15:35:33.931 > [DPL::setNewPowerLimit] input limit: 395 W, min limit: 10 W, max limit: 2000 W, hysteresis: 5 W
15:35:33.964 > [DPL::scalePowerLimit::debug] checking for shading, inverterInputDC 114.200005 W, inverterOutputAC 108.599998 W, inverterEfficiencyFactor 0.950963, expectedAcPowerPerChannel 61.740000 W, currentLimitWatts 252 W, newLimit 395 W
15:35:34.001 > [DPL::scalePowerLimit::debug] channel 0 is producing less than expected, channelPowerAC 20.635902 W, channelPowerDC 21.700001 W
15:35:34.035 > [DPL::scalePowerLimit::debug] channel 1 is producing less than expected, channelPowerAC 1.521541 W, channelPowerDC 1.600000 W
15:35:34.063 > [DPL::scalePowerLimit::debug] channel 2 is producing less than expected, channelPowerAC 52.302975 W, channelPowerDC 55.000000 W
15:35:34.091 > [DPL::scalePowerLimit::debug] channel 3 is producing less than expected, channelPowerAC 34.139580 W, channelPowerDC 35.900002 W
15:35:34.118 > [DPL::scalePowerLimit] 4/4 channels are producing less than expected, shadedChannelACPowerSum 108.599998 W
15:35:34.152 > [DPL::scalePowerLimit] all channels are producing less than expected, keeping the current limit of 252 W instead of 395 W
15:35:34.188 > [DPL::setNewPowerLimit] inverter max: 2000 W, inverter is producing, requesting: 252 W, reported: 252 W, diff: 0 W

2024-05-25 17:39 UTC, AndreasBoehm commented
@hex2647 Das Problem ist das alle Eingänge verschattet sind und (laut den Zahlen in deinem Log) keiner der Eingänge durch das Limit begrenzt ist sondern rein durch die verschattung.
Selbst Channel 3 liefert nur 52 W anstelle der erwarteten 61W beim aktuellen Limit.

Hast du denn tatsächlich so viel verschattung oder wir kommen deine eoch sehr unterschiedlichen Werte an den Eingängen zustande?

Das simple verdoppeln des Limits wie es bisher aktiv war ist durch meinen Algorithmus nicht mehr erforderlich und deshalb auch nicht implementiert.

2024-05-25 19:16 UTC, spcqike commented
> Selbst Channel 3 liefert nur 52 W

CH1 liefert sogar nur 1.6W. Also quasi nichts. So wenig auf einem Eingang hab ich nur zur Dämmerung

2024-05-27 07:09 UTC, AndreasBoehm commented
@hex2647 @spcqike 
> 15:35:34.152 > [DPL::scalePowerLimit] all channels are producing less than expected, keeping the current limit of 252 W instead of 395 W

Ich könnte noch einen check einbauen der das neue Limit setzt wenn alle Eingänge verschattet sind und das aktuelle Limit kleiner ist als das neue Limit, aber das wird unterm Strich dem WR auch nicht mehr Leistung entlocken wenn alle Eingänge verschattet sind.

@hex2647 Könntest du dein Szenario mal mit der "alten" Skalierung gegentesten? Also den Haken für das ausgleichen von Verschattung rausnehmen und dann Vergleichen ob du tatsächlich mehr Leistung aus deinem WR bekommst?

2024-05-27 08:39 UTC, spcqike commented
> Ich könnte noch einen check einbauen der das neue Limit setzt wenn alle Eingänge verschattet sind und das aktuelle Limit kleiner ist als das neue Limit, aber das wird unterm Strich dem WR auch nicht mehr Leistung entlocken wenn alle Eingänge verschattet sind.

daran hab ich auch schon gedacht. früher war das ja so, und in der Aufzeichnung in Grafana konnte man dann relativ gut nachvollziehen, was berechnet wurde und was das Limit war. Das passiert aktuell ja nicht 😄 dafür reduziert man mit deiner jetzigen Lösung aber den Overhead und unnötige Übertragungen. Wozu aller 10 Sekunden ein Limit übertragen, wenn ne dicke Wolke da ist und eh nichts passieren würde 😄 (man hat nur jetzt halt das kurzzeitige Risiko, dass man, sollte die Sonne doch schlagartig kommen, zu viel produziert. Aber das ist ja generell so, wenn überskaliert wird, und für mich ok)

also nein: aktuell sehe ich keinen Bedarf daran, ein kleineres, nicht erreichtes Limit neu zu setzen.

> @hex2647 Könntest du dein Szenario mal mit der "alten" Skalierung gegentesten? Also den Haken für das ausgleichen von Verschattung rausnehmen und dann Vergleichen ob du tatsächlich mehr Leistung aus deinem WR bekommst?

alternativ könnte er den DPL komplett deaktivieren und den Wechselrichter mal manuell auf 100% stellen. nur, um zu sehen, was aktuell wirklich an Solarleistung zur verfügung steht.
Ich find es immer noch komisch, dass sein Ch1 so gar nichts beiträgt

> 15:35:34.035 > [DPL::scalePowerLimit::debug] channel 1 is producing less than expected, channelPowerAC 1.521541 W, channelPowerDC 1.600000 W

wie gesagt, 1.5W kenne ich nur aus der Dämmerung. das sind Frühs und Abends jeweils wenige Minuten, wo das so ist. selbst ne Nordseite liefert mehr, egal ob bewölkt oder nicht.

2024-05-28 09:14 UTC, AndreasBoehm commented
@greymda Did you have a chance to test this feature? Asking because you made the effort to create the issue on github.

2024-05-28 09:30 UTC, greymda commented
@AndreasBoehm you're right i opened this enhancement but I no longer have access to the partially shaded environment so, unfortunately, I cannot test. Still I believe that this functionality will bring value to the project, though.

2024-06-01 06:51 UTC, AndreasBoehm commented
@hex2647 Konntest du nochmal prüfen warum bei dir so eine geringe Leistung anliegt? Und denkst du das die Skalierung nun korrekt funktioniert für dich?

2024-06-03 08:07 UTC, hex2647 commented
> @hex2647 Konntest du nochmal prüfen warum bei dir so eine geringe Leistung anliegt? Und denkst du das die Skalierung nun korrekt funktioniert für dich?

Hi sorry bin gerade in Spanien unterwegs und hab daher leider keine Möglichkeit es zu testen… werd ich aber machen sobald ich zurück bin. Bezüglich der 1.9W hatte ich tatsächlich nen Verkabelungsfehler drin als ich den dann aber entdeckt hatte war die Sonne weg :(

2024-06-07 12:41 UTC, Dozer-hh commented
Sehe ich es richtig, dass das hier angesprochene Schatten-Feature auch meine Anfrage löst?
Ich bleibe mal bei der deutschen Beschreibung meines Request:

Ich habe einen HMS-2000-4T mit 4 PV-Modulen á 435 W. Hiervon haben 2 Module eine Süd-Ost-Ausrichtung und 2 Module eine Süd-West-Ausrichtung, es liegt also nie an allen 4 Modulen die gleiche Leistung an. Derzeit habe ich keinen Speicher, so dass ich die volle Leistung bis zur erlaubten 800 W Grenze ins Haus einspeise.

Wenn ich das obere Leistungslimit auf 800W setze, wird der WR auf ein Limit von 40% gesetzt und somit jeder MPPT auf 200 W (der möglichen 500 W) begrenzt.

Wenn die 4 Module zu einem bestimmten Zeitpunkt insgesamt z.B. 1000 W produzieren können, davon Modul 1 und 2 (Süd-Ost) jeweils 400 W und die Module 3 und 4 (Süd-West) aber sonnenstandsbedingt nur jeweils 100 W, wird die reale Einspeisung durch das Limit von 40% pro MPPT auf zusammen 600 W (je 200 W von M1 und M2 und je 100 W von M3 und M4) begrenzt. 
Somit gehen zu dem Zeitpunkt 200 W verloren.

Wenn die OpenDTU-OnBattery nun erkennen würde, dass sie, um das gewünschte obere Leistungslimit von 800W zu erreichen, die "fehlenden" 200 W durch eine Angleichung des prozentualen Limits ausgleichen muss, würde man (beim Betrieb ohne Speicher) einiges weniger vom Netzbetreiber beziehen müssen, da die Anlage es selber hergeben würde.

2024-06-07 12:58 UTC, spcqike commented
@Dozer-hh ja das siehst du richtig. dieser PR soll, bei Verwendung des DPL, genau das bewirken.

den letzten Build aus dem PR findest du, glaube ich, hier
https://github.com/helgeerbe/OpenDTU-OnBattery/actions/runs/9087695629

2024-06-07 13:08 UTC, Dozer-hh commented
Perfekt, danke für die Bestätigung und den Link zum letzten PR Release!

2024-06-07 13:14 UTC, Dozer-hh commented
@spcqike  Perfekt, danke für die Bestätigung und den Link zum letzten PR Release!

EDIT: Ist der letzte Release nicht dieser hier: https://github.com/helgeerbe/OpenDTU-OnBattery/actions/runs/9170291945?

2024-06-09 06:14 UTC, AndreasBoehm commented
@Dozer-hh Den letzten build findest du hier: https://github.com/helgeerbe/OpenDTU-OnBattery/actions/runs/9345299744
Bitte gib Bescheid ob alles klappt und wie erwartet funktioniert.

2024-06-10 06:43 UTC, Dozer-hh commented
@AndreasBoehm vielen Dank für den Link.
Ich habe Freitag die Version aus meinem vorangegangenen Link installiert und bisher keine Probleme festgestellt.
Wetterbedingt konnte ich aber das von mir gewünschte Verhalten bzgl. Übersteuern noch nicht feststellen, da die Panel entweder gar nicht so viel Ertrag oder alle einen sehr ähnlichen Ertrag gebracht haben.
Ich werde aber beobachten und berichten, falls es Probleme gibt bzw. sobald ich feststelle, dass die Steuerung klappt.

2024-06-18 20:09 UTC, AndreasBoehm commented
@Dozer-hh Konntest du schon testen bzw feststellen ob alles funktioniert wie erwartet?

2024-06-19 06:27 UTC, Dozer-hh commented
@AndreasBoehm Soweit ich es bisher sehen konnte, funktioniert die Übersteuerung / Regelung. Ich hatte bisher wetterbdingt leider nur zwei Situationen, die ich abpassen konnte und wo das Overscaling in jedem Fall höhere Werte der beiden nicht verschatteten Module bewirkte. Der Vergleich durch Ausschalten des DPL und einem "Dauerhaften Limit" von 100% brachte "identische" Ertragswerte der Module und das Ausschalten vom Overscaling bewirkte das gewohnt niedrigere Limit mit Beschneidung der beiden Module, die voll in der Sonne standen. 

Ich meine, dass der angestrebte Netzbezug (bei mir auf -10W bei einer Hysterese von 5W) immer etwas lange über- bzw. unterschritten wurde (Bereich -30W bis +30W), das kann ich aber wetterbedingt nur eingeschränkt beurteilem, da ich WENN hier mal ausreichend Sonne ist, meist im Büro sitze und nicht allzu ausgiebig testen kann, bzw. sich Sonnenzustand zu Hause und im Büro nicht decken...

Aber auf den ersten Eindruck deckt das Feature genau meine Anforderungen und ist eine echte Verbesserung für meine Installationssituation mit unterschiedlich ausgerichteten Modulen.

2024-06-19 07:11 UTC, AndreasBoehm commented
Danke für deine mühen @Dozer-hh !
Ich werde nachher noch etwas aufräumen, dann können wir das feature endlich mergen.

2024-06-19 07:36 UTC, schlimmchen commented
@AndreasBoehm Hast du einen ESP32 mit mind. 8MB Flash und kannst das Feature auch ab dem nächsten Release begleiten?

2024-06-19 08:41 UTC, Dozer-hh commented
@AndreasBoehm Also wird das aufgeräumte / zusammengeführte Release dann schon nicht mehr auf den 4MB ESPs funktionieren?

2024-06-19 09:06 UTC, schlimmchen commented
@Dozer-hh Wenn das Feature "fertig" ist, gibt es im Rahmen dieses PR nochmal einen Build Run, der das Feature enthält und auf dem aktuellen Development-Branch beruht (Release 2024.06.03), welches das bisherige Partitionslayout für 4MB Flash noch benutzt. Das nächste Release allerdings wird das neue Partitionslayout verwenden.

2024-06-19 11:15 UTC, hex2647 commented
> @Dozer-hh Wenn das Feature "fertig" ist, gibt es im Rahmen dieses PR nochmal einen Build Run, der das Feature enthält und auf dem aktuellen Development-Branch beruht (Release 2024.06.03), welches das bisherige Partitionslayout für 4MB Flash noch benutzt. Das nächste Release allerdings wird das neue Partitionslayout verwenden.

Ich bin zwar erst nächste Woche zurück zum weiter testen aber woran erkenne ich ob ich 4 oder 8mb zur Verfügung habe?

2024-06-19 11:21 UTC, AndreasBoehm commented
@hex2647 
Das kannst du in openDTU überprÜfen wenn du das aktuelle Release build oder das aktuellste build von meinem PR installiert hast.
> ..navigate to the system's information page of the web UI. It lists the flash memory size in section "Hardware Information". This information is expected to be reliable.
Quelle: https://github.com/helgeerbe/OpenDTU-OnBattery/issues/1025

@schlimmchen Ich hab aufgeräumt und der PR wäre von meiner Seite aus jetzt fertig.

2024-06-20 11:31 UTC, schlimmchen approved these changes
Beautiful :heart:

2024-06-20 11:32 UTC, merged

2024-06-20 11:33 UTC, AndreasBoehm commented
> Beautiful ❤️

Thanks a lot for your support on this @schlimmchen !

2024-06-20 11:36 UTC, schlimmchen commented
@Dozer-hh FYI: Ich rechne im Moment damit, dass ESP32 mit 4MB flash doch noch weiter unterstützt werden. Allerdings auf Kosten von Over-The-Air Updates. Siehe https://github.com/helgeerbe/OpenDTU-OnBattery/issues/1025#issuecomment-2179428297

> Thanks a lot for your support on this

@AndreasBoehm You are very welcome. Let me know if you are interested in tackling another feature :wink:

2024-06-20 12:05 UTC, Dozer-hh commented
@schlimmchen Jetzt habe ich mir gestern frisch ne Fusion DTU bestellt, um up-to-date zu bleiben… 🤪🫣

2024-06-20 12:18 UTC, schlimmchen commented
Das wirst du auch nicht bereuen. Alleine schon um weiterhin OTA Updates machen zu können. Mit dem Kabel und dem PC für jedes Update an die OpenDTU-OnBattery zu gehen, oder schlimmer, diese an den PC zu bringen, ist schon lästig und würde eine Hürde darstellen, up-to-date zu bleiben, ggf. sogar obwohl du neue Features spannend findest.

2024-06-20 13:20 UTC, hex2647 commented
> @hex2647 Das kannst du in openDTU überprüfen wenn du das aktuelle Release build oder das aktuellste build von meinem PR installiert hast.
> 
> > ..navigate to the system's information page of the web UI. It lists the flash memory size in section "Hardware Information". This information is expected to be reliable.
> > Quelle: #1025
> 
> @schlimmchen Ich hab aufgeräumt und der PR wäre von meiner Seite aus jetzt fertig.

Kann das sein das ich nur 2mb hab? Da wurde ich ja dann ganz schön verarscht… welches ist denn das ideale Board vorallem wenn ich noch Batterie und Ladegeräte abklemmen will?
![IMG_1781](https://github.com/helgeerbe/OpenDTU-OnBattery/assets/161470023/9ed1d28d-22f9-4219-89a1-9fcdbe6dd00c)

2024-06-20 13:24 UTC, AndreasBoehm commented
@hex2647 
Die Info gibts unter 'Hardwareinformationen'
![Screenshot 2024-06-20 at 15 23 59](https://github.com/helgeerbe/OpenDTU-OnBattery/assets/1270749/9a5bbb57-1d11-4f38-8f3e-ec4354b4292a)

2024-06-20 13:38 UTC, hex2647 commented
> @hex2647 Die Info gibts unter 'Hardwareinformationen' ![Screenshot 2024-06-20 at 15 23 59](https://private-user-images.githubusercontent.com/1270749/341427292-9a5bbb57-1d11-4f38-8f3e-ec4354b4292a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4OTA5ODgsIm5iZiI6MTcxODg5MDY4OCwicGF0aCI6Ii8xMjcwNzQ5LzM0MTQyNzI5Mi05YTViYmI1Ny0xZDExLTRmMzgtOGYzZS1lYzQzNTRiNDI5MmEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MjBUMTMzODA4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MmZiYTcyZWNmZjM0MmRiYTIwZWQ3YWFiY2U4MmRmZDVjZDcyZDc4YTcyZTk0YWRmNTc4NWMxMDAzOTdmNmYzNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.zA29lAhaqCf4Ua1kK_ZK_dcdL7rTwT2fTU_p-XaC-qY)

Ah ok da wird mir nichts angezeigt dann hab ich wohl keine passende Version installiert :)

2024-06-20 13:40 UTC, AndreasBoehm commented
@hex2647 Das ist durchaus möglich, sonst versuch mal die Seite manuell neu zu laden, das ist nach einem Update immer erforderlich um die aktuelle Version der WebApp anzuzeigen.

2024-07-02 14:11 UTC, spcqike commented
Mahlzeit,

ich hab jetzt den PR (https://github.com/helgeerbe/OpenDTU-OnBattery/pull/1077) auf dem neuen Board installiert, läuft soweit. Nun kann ich auch das Overscaling noch einmal auf Herz und Nieren testen. Dabei fällt mir auf, dass irgendwas nicht zu passen scheint :)

![grafik](https://github.com/helgeerbe/OpenDTU-OnBattery/assets/50098985/68d834b0-dda4-4a09-bf34-3ead87e3ae3c)


```
16:05:31.825 > [DPL::loop] ******************* ENTER **********************
16:05:31.909 > [DPL::calcPowerLimit] battery use prevented, solar power (DC): 10000 W
16:05:31.971 > [DPL::calcPowerLimit] target consumption: 0 W, base load: 250 W, power meter does include inverter output
16:05:32.115 > [DPL::calcPowerLimit] power meter value: 71 W, power meter valid: yes, inverter output: 213 W, solar power (AC): 9220 W
16:05:32.217 > [DPL::calcPowerLimit] limited to solar power: 284 W
16:05:32.321 > [DPL::setNewPowerLimit] input limit: 284 W, min limit: 200 W, max limit: 2000 W, hysteresis: 25 W
16:05:32.385 > [DPL::scalePowerLimit] all channels are shaded, keeping the current limit of 226 W
16:05:32.449 > [DPL::setNewPowerLimit] inverter max: 2000 W, inverter is producing, requesting: 226 W, reported: 226 W, diff: 0 W
16:05:32.527 > [PowerMeterHttpJson] New total: 63.49
16:05:32.850 > [DPL::loop] ******************* ENTER **********************
16:05:32.933 > [DPL::calcPowerLimit] battery use prevented, solar power (DC): 10000 W
16:05:32.994 > [DPL::calcPowerLimit] target consumption: 0 W, base load: 250 W, power meter does include inverter output
16:05:33.139 > [DPL::calcPowerLimit] power meter value: 63 W, power meter valid: yes, inverter output: 213 W, solar power (AC): 9220 W
16:05:33.241 > [DPL::calcPowerLimit] limited to solar power: 276 W
16:05:33.350 > [DPL::setNewPowerLimit] input limit: 276 W, min limit: 200 W, max limit: 2000 W, hysteresis: 25 W
16:05:33.417 > [DPL::scalePowerLimit] all channels are shaded, keeping the current limit of 226 W
16:05:33.550 > [DPL::setNewPowerLimit] inverter max: 2000 W, inverter is producing, requesting: 226 W, reported: 226 W, diff: 0 W
16:05:33.655 > Fetch inverter: 116492305207
16:05:33.758 > Success
16:05:33.854 > [PowerMeterHttpJson] New total: 64.87
16:05:33.956 > [DPL::loop] ******************* ENTER **********************
16:05:34.017 > [DPL::calcPowerLimit] battery use prevented, solar power (DC): 10000 W
16:05:34.161 > [DPL::calcPowerLimit] target consumption: 0 W, base load: 250 W, power meter does include inverter output
16:05:34.265 > [DPL::calcPowerLimit] power meter value: 64 W, power meter valid: yes, inverter output: 213 W, solar power (AC): 9224 W
16:05:34.335 > [DPL::calcPowerLimit] limited to solar power: 277 W
16:05:34.396 > [DPL::setNewPowerLimit] input limit: 277 W, min limit: 200 W, max limit: 2000 W, hysteresis: 25 W
16:05:34.469 > [DPL::scalePowerLimit] all channels are shaded, keeping the current limit of 226 W
16:05:34.572 > [DPL::setNewPowerLimit] inverter max: 2000 W, inverter is producing, requesting: 226 W, reported: 226 W, diff: 0 W
16:05:34.675 > [PowerMeterHttpJson] New total: 69.00
```

wie man sieht, gegen 15:50 hab ich das Target auf 0W gesetzt. das hält er auch. Kurz nach 16:00 gab es einen Anstieg im Verbrauch. Allerdings will er nicht hoch regeln. er sagt immer, alles sei verschattet, was so nicht ganz hinkommt. die 30W mehr wären sicherlich drin :) 
Daher hab ich das Skalieren aus gemacht und siehe da, er regelt hoch und macht auch mehr.

Leider sehe ich die Auswertung der Eingänge nicht mehr im Log, also wie viel leistung welcher Eingang tatsächlich liefert. und ich hab es mir nicht notiert :D 

Hab also das Skalieren noch mal an gemacht und gucke, ob das Verhalten noch mal auftritt. Dann geb ich n Update dazu, welches Limit gesetzt ist, welche Leistung erzeugt und und welcher Eingang was dazu beisteuert.

2024-07-03 10:25 UTC, Dozer-hh commented
Ich kann das Fehlverhalten bestätigen, allerdings aus dem Release #1310 von hier: https://github.com/helgeerbe/OpenDTU-OnBattery/actions/runs/9596676383.

Ich habe vor ein paar Tagen auf die Fusion openDTU von 3PrintD Solution gewechselt.
Da für mich auf dem Fusion-Board die PIO Umgebung nicht eindeutig war (steht irgendwas mit Fusion in der Bezeichnung), habe ich wegen des ESP32-S3 Chips erst die falsche Firmware geflasht und die "opendtu-onbattery-generic_esp32s3" verwendet. Hier kam es dann aber bei aktiviertem DPL zu seltsamem Verhalten der openDTU.

Zum Glück bin ich dann unter: https://github.com/markusdd/OpenDTUFusionDocs/blob/main/BLANK_START.md auf den Hinweis gestoßen: _For the Fusion board, you need the USB version._

Für Neulinge in dem Thema wäre hier ggf. (vor allem da demnächst vermutlich einige Leute auf andere Hardware umsteigen werden) ein kleiner Hinweis ganz gut, wann welche Firmware zu verwende ist. ;-) 

Jedenfalls trat mit dem Release #1310 bei mir das Verhalten auf, dass bei Aktiviertem Ausgleich von Verschattung die Regelung total sprunghaft wurde und ganz oft trotz Sonne der WR so weit runter geregelt wurde, dass er Strom aus dem Netz zog, obwohl die Module ausreichend hätten liefern können:

![Vergleich_1](https://github.com/helgeerbe/OpenDTU-OnBattery/assets/60253043/6aca0e9b-9aa1-4404-894b-6d29f82c4840)

Noch deutlicher hier:

![Vergleich_2](https://github.com/helgeerbe/OpenDTU-OnBattery/assets/60253043/defdd647-10d4-48c8-ae11-dead8471ec7d)

Ich habe dann wieder den Release #1291 von hier: https://github.com/helgeerbe/OpenDTU-OnBattery/actions/runs/9345299744 installiert, da dieser vor dem Boardwechsel problemlos lief. 

Leider scheint seitdem die letzten Tage die Sonne kaum bis gar nicht, so dass ich nicht sehe, ob der Wechsel etwas bewirkt hat oder ob das Problem mit am Fusion Board liegt.

Ich vermute aber, dass beim Aufräumen und Mergen von @AndreasBoehm irgendetwas schief gelaufen ist und ab des Releses #1310 irgendwas hakt.

2024-07-03 10:28 UTC, Dozer-hh commented
Ich kann das Fehlverhalten bestätigen, allerdings aus dem Release # 1310 von hier: https://github.com/helgeerbe/OpenDTU-OnBattery/actions/runs/9596676383.

Ich habe vor ein paar Tagen auf die Fusion openDTU von 3PrintD Solution gewechselt.
Da für mich auf dem Fusion-Board die PIO Umgebung nicht eindeutig war (steht irgendwas mit Fusion in der Bezeichnung), habe ich wegen des ESP32-S3 Chips erst die falsche Firmware geflasht und die "opendtu-onbattery-generic_esp32s3" verwendet. Hier kam es dann aber bei aktiviertem DPL zu seltsamem Verhalten der openDTU.

Zum Glück bin ich dann unter: https://github.com/markusdd/OpenDTUFusionDocs/blob/main/BLANK_START.md auf den Hinweis gestoßen: _For the Fusion board, you need the USB version._

Für Neulinge in dem Thema wäre hier ggf. (vor allem da demnächst vermutlich einige Leute auf andere Hardware umsteigen werden) ein kleiner Hinweis ganz gut, wann welche Firmware zu verwende ist. ;-) 

Jedenfalls trat mit dem Release # 1310 bei mir das Verhalten auf, dass bei Aktiviertem Ausgleich von Verschattung die Regelung total sprunghaft wurde und ganz oft trotz Sonne der WR so weit runter geregelt wurde, dass er Strom aus dem Netz zog, obwohl die Module ausreichend hätten liefern können:

![Vergleich_1](https://github.com/helgeerbe/OpenDTU-OnBattery/assets/60253043/6aca0e9b-9aa1-4404-894b-6d29f82c4840)


Noch deutlicher hier:

![Vergleich_2](https://github.com/helgeerbe/OpenDTU-OnBattery/assets/60253043/defdd647-10d4-48c8-ae11-dead8471ec7d)

Ich habe dann wieder den Release # 1291 von hier: https://github.com/helgeerbe/OpenDTU-OnBattery/actions/runs/9345299744 installiert, da dieser vor dem Boardwechsel problemlos lief. 

Leider scheint seitdem die letzten Tage die Sonne kaum bis gar nicht, so dass ich nicht sehe, ob der Wechsel etwas bewirkt hat oder ob das Problem mit am Fusion Board liegt.

Ich vermute daher, dass beim Aufräumen und Mergen von @AndreasBoehm irgendetwas schief gelaufen ist und ab des Releses # 1310 irgendwas hakt.

2024-07-03 11:00 UTC, AndreasBoehm commented
Danke für deinen input @Dozer-hh, es wäre ganz wichtig neben dem aktuellen Limit auch das gewünschte Limit und vorallem auch die aktuelle Leistung pro Kanal zu sehen, denn diese ist entscheidend dafür ob skaliert wird oder nicht.

Ich konnte bisher mit meinem Setup kein Vergleichbares Problem feststellen.

2024-07-03 11:30 UTC, Dozer-hh commented
@AndreasBoehm Im Falle der Scrennshots waren es 2.000 W Limit bei aktiviertem DPL. 
Da ich noch im Testmodus bin, ob und in welcher Dimension sich ein Speicher bei mir lohn, läuft das Limit bei aktiviertem DPL meist auf 2.000 W. Ich vergleiche diese Werte dann tageweise mit dem Ertrag ohne DPL und einem Limit von 2.000 W bzw. mit DPL und einem Limit von 800 W.

Leider habe ich keine aussagekräftigen Scrennshots von der einzelnen Modulleistung.
Was mit aber parallel aufgefallen ist, ist der Effekt, dass der angestrebte Netzbezug (habe -10W eingestellt) teilweise deutlich überschritten wurde und manchmal auf bis zu -350W ging.

Ich bin derzeit krank geschrieben und morgen soll es teils sonnig werden. Ich kann morgen gerne mal die beiden Releases gegeneinander testen und endsprechende Scrennshots der einzelnen Kanäle und Settings machen.

2024-07-03 11:39 UTC, AndreasBoehm commented
Ich weiß das es schwer ist das so zu Beschreiben das alle wissen was passiert ist und was erwartet wurde, aber ich kann aktuell nicht nachvollziehen was du erwartest und was passiert ist, denn es ist auf den Screenshots auch nicht ersichtlich welche Einstellung gerade aktiv war (mit/ohne DPL, Modulleistung, Limits, etc).

Grundsätzlich muss man mit overscaling auch damit rechnen das Kurzzeitig sehr viel Strom eingespeist wird wenn wir von starker verschattung zu 100% Sonne wechseln.

Wäre super wenn du einen Issue öffnen könntest und dort versuchst exakt die verschiedenen Szenarien bzw übergange zwischen Szenarien zu beschrieben um es nachvollziehbar zu machen.

2024-07-03 11:45 UTC, Dozer-hh commented
Okay, werde ich mal genauer dokumentieren. Also nicht hier fortführen?

2024-07-05 09:13 UTC, AndreasBoehm commented
Hallo @robbe1912 ,

ich würde dich darum bitten wie in meinem früheren Kommentar beschrieben eine Ausführliche Beschreibung inklusive Logs und relevanten Daten bereit zu stellen, ohne diese Infos können wir nicht nachvollziehen ob ein Problem vorliegt und wo.

Bitte erstelle einen Issue mit den geforderten Infos dann können wir uns das anschauen.

2024-07-05 09:15 UTC, AndreasBoehm commented
@schlimmchen Kannst du hier zu machen? Danke